<?php
declare(strict_types=1);
namespace DataForm5\Packages\Core;
use DataForm5\Core\Container\ServiceContainer;
use DataForm5\Core\Filesystem\Filesystem;
use DataForm5\Packages\Contracts\PackageLifecycleInterface;
use DataForm5\Packages\Exceptions\PackageException;
final class PackageManager
{
 public function __construct(private readonly string $installPath,private readonly Filesystem $fs,private readonly PackageRegistry $registry,private readonly PackageIntegrity $integrity,private readonly ServiceContainer $container){}
 public function install(string $source):PackageManifest{$m=PackageManifest::fromFile(rtrim($source,'/\\').'/package.json');$payload=rtrim($source,'/\\').'/payload';if(!is_dir($payload))throw new PackageException('Paketordner payload fehlt.');if($this->registry->get($m->name)!==null)throw new PackageException("Paket '{$m->name}' ist bereits installiert.");$this->assertDependencies($m);$this->integrity->verify($payload,$m);$target=$this->target($m->name);$this->fs->copy($payload,$target);$this->runLifecycle($m,$source,'install');$this->registry->put($m->name,['version'=>$m->version,'type'=>$m->type,'installed_at'=>date(DATE_ATOM),'path'=>$target]);return$m;}
 public function update(string $source):PackageManifest{$m=PackageManifest::fromFile(rtrim($source,'/\\').'/package.json');$old=$this->registry->get($m->name);if($old===null)throw new PackageException("Paket '{$m->name}' ist nicht installiert.");$from=(string)$old['version'];if(!version_compare($m->version,$from,'>'))throw new PackageException('Neue Paketversion muss größer als die installierte Version sein.');$this->assertDependencies($m);$payload=rtrim($source,'/\\').'/payload';$this->integrity->verify($payload,$m);$target=$this->target($m->name);$backup=$target.'.backup';if(is_dir($backup))$this->fs->delete($backup);$this->fs->move($target,$backup);try{$this->fs->copy($payload,$target);$this->runLifecycle($m,$source,'update',$from);$this->fs->delete($backup);}catch(\Throwable $e){if(is_dir($target))$this->fs->delete($target);$this->fs->move($backup,$target);throw $e;}$this->registry->put($m->name,['version'=>$m->version,'type'=>$m->type,'installed_at'=>$old['installed_at']??date(DATE_ATOM),'updated_at'=>date(DATE_ATOM),'path'=>$target]);return$m;}
 public function uninstall(string $name,?string $source=null):void{$old=$this->registry->get($name);if($old===null)throw new PackageException("Paket '{$name}' ist nicht installiert.");if($source!==null){$m=PackageManifest::fromFile(rtrim($source,'/\\').'/package.json');$this->runLifecycle($m,$source,'uninstall');}$target=$this->target($name);if(is_dir($target))$this->fs->delete($target);$this->registry->remove($name);}
 /** @return array<string,array<string,mixed>> */ public function installed():array{return$this->registry->all();}
 private function target(string $name):string{return rtrim($this->installPath,'/\\').'/'.$name;}
 private function assertDependencies(PackageManifest $m):void{foreach($m->dependencies as $name=>$constraint){$d=$this->registry->get((string)$name);if($d===null)throw new PackageException("Abhängigkeit fehlt: {$name}");if(!VersionConstraint::matches((string)$d['version'],(string)$constraint))throw new PackageException("Abhängigkeit {$name} erfüllt {$constraint} nicht.");}}
 private function runLifecycle(PackageManifest $m,string $source,string $action,string $from=''):void{if($m->lifecycle===null)return;$file=rtrim($source,'/\\').'/lifecycle.php';if(!is_file($file))throw new PackageException('Lifecycle-Datei fehlt.');require_once $file;if(!class_exists($m->lifecycle))throw new PackageException('Lifecycle-Klasse wurde nicht gefunden.');$obj=new ($m->lifecycle)();if(!$obj instanceof PackageLifecycleInterface)throw new PackageException('Lifecycle-Klasse implementiert den Vertrag nicht.');$action==='install'?$obj->install($this->container):($action==='update'?$obj->update($this->container,$from):$obj->uninstall($this->container));}
}
