<?php
declare(strict_types=1);
$r=__DIR__;
$rt=(string)file_get_contents($r.'/products/dataform/runtime.php');
$mgr=(string)file_get_contents($r.'/products/dataform/system/DataSourceManager.php');
$wc=(string)file_get_contents($r.'/products/dataform/system/WorkspaceController.php');
$mig=(string)file_get_contents($r.'/installer/schema/project/003_data_sources.php');
$c=[];$f=function(string $n,bool $ok)use(&$c):void{$c[]=['check'=>$n,'status'=>$ok?'PASS':'FAIL'];};
$f('sources no longer placeholder',!str_contains($wc,'folgt in einer späteren Phase')&&str_contains($wc,'MySQL/MariaDB, SQLite, CSV und Oracle'));
$f('data source schema',str_contains($mig,'CREATE TABLE IF NOT EXISTS data_sources')&&str_contains($mgr,'ensureSchema'));
$f('drivers supported',str_contains($mgr,"'mysql'")&&str_contains($mgr,"'sqlite'")&&str_contains($mgr,"'csv'")&&str_contains($mgr,"'oracle'"));
$f('CRUD actions',str_contains($rt,'save_source')&&str_contains($rt,'delete_source')&&str_contains($rt,'test_source'));
$f('connection test uses factory',str_contains($mgr,'DatabaseFactory::create'));
$f('secrets encrypted',str_contains($mgr,'aes-256-gcm')&&str_contains($mgr,'DATAFORM_APP_KEY')&&str_contains($mgr,'APP_KEY'));
$f('password not stored in config json',!str_contains($mgr,"\$config['password']=\$password"));
$f('project database shown as system source',str_contains($rt,'Projekt-Datenbank')&&str_contains($rt,'Systemquelle'));
$f('source edit UI',str_contains($rt,'data-source-form')&&str_contains($rt,'data-source-driver'));
$f('password eye',str_contains($rt,'data-password-toggle'));
$f('HF23 marker',str_contains($rt,'HF36 DATAFORM RUNTIME ACTIVE'));
$failed=count(array_filter($c,static fn(array $x):bool=>$x['status']==='FAIL'));
echo json_encode(['release'=>'RC1.8','hotfix'=>'HF34','status'=>$failed?'FAIL':'PASS','checks'=>$c,'summary'=>['checks'=>count($c),'failed'=>$failed]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;
exit($failed?1:0);
