<?php
declare(strict_types=1);
$root=__DIR__;
$fail=0;$pass=0;
$check=function(string $name,bool $ok)use(&$fail,&$pass):void{echo ($ok?'PASS':'FAIL')." - $name\n";$ok?$pass++:$fail++;};
require_once $root.'/system/ui/ButtonRegistry.php';
$registry=easyit_button_registry();
$css=(string)file_get_contents($root.'/assets/css/easyit-crud-3d-buttons.css');
$js=(string)file_get_contents($root.'/assets/js/easyit-button-registry.js');
$check('extended central buttons registered',count($registry)>=56);
$check('all buttons have central title',count(array_filter($registry,fn($d)=>trim((string)($d['title']??''))!==''))===count($registry));
$check('all registered PNG files exist',count(array_filter($registry,fn($d)=>is_file($root.'/'.($d['image']??''))))===count($registry));
$check('hard image rendering CSS layer exists',str_contains($css,'HF76-FIX5 – HARD IMAGE RENDERING LAYER'));
$check('registered button containers are transparent',str_contains($css,'background-image:none!important'));
$check('real image node CSS exists',str_contains($css,'.easyit-button-image{'));
$check('JS creates real IMG nodes',str_contains($js,"document.createElement('img')")&&str_contains($js,"img.className='easyit-button-image'"));
$check('JS resolves assets from global script path',str_contains($js,'PROJECT_ROOT=SCRIPT_URL'));
$check('input fallback uses canonical image variable',str_contains($css,'input.easyit-image-button-input[data-button]')&&str_contains($css,'background-image:var(--easyit-button-image)!important'));
$check('CSS no visual pseudo icon for registered buttons',str_contains($css,'.easyit-image-button::before')&&str_contains($css,'.easyit-image-button::after')&&str_contains($css,'content:none!important'));
$check('DataForm open is form image',($registry['formular']['image']??'')==='assets/img/formular.png');
$check('DataForm records uses anzeigen image',($registry['anzeigen']['image']??'')==='assets/img/anzeigen.png');
$check('new uses supplied buttonset image',($registry['neu']['image']??'')==='assets/img/neu.png');
$check('delete uses supplied buttonset image',($registry['loeschen']['image']??'')==='assets/img/loeschen.png');
echo "RESULT: $pass PASS / $fail FAIL\n";
exit($fail?1:0);
