<?php
declare(strict_types=1);
$root=__DIR__;
$runtime=(string)file_get_contents($root.'/products/dataform/runtime.php');
$checks=[];
$check=function(string $name,bool $ok)use(&$checks){$checks[]=[$name,$ok?'PASS':'FAIL'];};
$check('list edit button',str_contains($runtime,"easyit_button_attributes('bearbeiten','dataform')")&&str_contains($runtime,'#dataform-settings'));
$check('settings action handler',str_contains($runtime,"update_dataform_settings"));
$check('settings schema ensured',str_contains($runtime,'DataFormManager::ensureRuntimeSettingsSchema($projectPdo)'));
$check('name editable',str_contains($runtime,'name="name" required maxlength="160"'));
$check('slug editable and unique',str_contains($runtime,"SELECT COUNT(*) FROM dataforms WHERE slug=? AND id<>?"));
$check('description editable',str_contains($runtime,'name="description" rows="4"'));
$check('status editable',str_contains($runtime,'name="status"'));
$check('save mode editable',str_contains($runtime,'name="table_save_mode"'));
$check('success message editable',str_contains($runtime,'name="show_save_success"'));
$check('settings persisted',str_contains($runtime,'UPDATE dataforms SET name=?,slug=?,description=?,status=?,table_save_mode=?,show_save_success=? WHERE id=?'));
$check('binding shown read only',str_contains($runtime,'Physische Tabellenbindung:'));
$check('advanced settings links',str_contains($runtime,'Layout &amp; Verhalten')&&str_contains($runtime,'Workflow')&&str_contains($runtime,'Beziehungen'));
foreach($checks as [$n,$st]) echo $st.' '.$n.PHP_EOL;
$failed=count(array_filter($checks,fn($x)=>$x[1]!=='PASS'));
echo 'TOTAL '.count($checks).' FAILED '.$failed.PHP_EOL;
exit($failed?1:0);
