<?php
declare(strict_types=1);
$root=__DIR__;
require_once $root.'/system/app/project_distribution.php';
$checks=[];$c=function(string $n,bool $ok)use(&$checks){$checks[]=['name'=>$n,'ok'=>$ok];};
$src=(string)file_get_contents($root.'/system/app/project_distribution.php');
$runtime=(string)file_get_contents($root.'/system/app/project_runtime/DataFormApp.php');
$setup=(string)file_get_contents($root.'/system/app/project_runtime/setup.php');
$index=(string)file_get_contents($root.'/app/projects/index.php');
$c('minimal bundle format',str_contains($src,'easyit-dataform-html5-application'));
$c('does not add enterprise tree',!str_contains($src,'enterprise_project_distribution_add_tree('));
$c('creates dataform directory',str_contains($src,"/dataforms/"));
$c('generated page renders HTML5 runtime',str_contains(enterprise_project_distribution_dataform_page(7),'df_render_dataform(7)'));
$c('runtime outputs doctype html',str_contains($runtime,'<!doctype html>'));
$c('runtime supports create',str_contains($runtime,"\$action==='create'"));
$c('runtime supports update',str_contains($runtime,"\$action==='update'"));
$c('runtime supports delete',str_contains($runtime,"\$action==='delete'"));
$c('runtime supports bulk delete',str_contains($runtime,"\$action==='bulk_delete'"));
$c('runtime supports physical table binding',str_contains($runtime,'dataform_table_bindings'));
$c('runtime supports generic records',str_contains($runtime,'dataform_records'));
$c('runtime supports lookup',str_contains($runtime,'df_lookup_options'));
$c('runtime supports derived multienum',str_contains($runtime,'df_derived_options'));
$c('runtime supports media',str_contains($runtime,'df_store_upload'));
$c('runtime supports search',str_contains($runtime,'type="search"'));
$c('runtime supports pagination',str_contains($runtime,'Seite '));
$c('runtime supports record pointers',str_contains($runtime,'data-record-pointer'));
$c('setup writes config.php',str_contains($setup,"'/config.php'"));
$c('setup imports database snapshot',str_contains($setup,'install/database.sql'));
$c('bundle includes only project uploads',str_contains($src,'storage/dataform/uploads/project-'));
$c('bundle ships selected button assets',str_contains($src,'easyit-epManager-logo.png')&&str_contains($src,'normaler_ds.png'));
$c('project UI describes HTML5 export',str_contains($index,'eigenständige HTML5-DataForm-Anwendung'));
$tmp=sys_get_temp_dir().'/df-page-'.bin2hex(random_bytes(4)).'.php';file_put_contents($tmp,enterprise_project_distribution_dataform_page(12));$lint=shell_exec('php -l '.escapeshellarg($tmp).' 2>&1');@unlink($tmp);$c('generated dataform page PHP syntax',is_string($lint)&&str_contains($lint,'No syntax errors'));
foreach($checks as $x)echo ($x['ok']?'PASS':'FAIL').' '.$x['name'].PHP_EOL;
$failed=array_filter($checks,fn($x)=>!$x['ok']);exit($failed?1:0);
