<?php
declare(strict_types=1);
$root=__DIR__;
$runtime=(string)file_get_contents($root.'/products/dataform/runtime.php');
$workflow=(string)file_get_contents($root.'/products/dataform/workflow.php');
$visual=(string)file_get_contents($root.'/products/dataform/workflow-visual.php');
$checks=[];
$check=function(string $name,bool $ok)use(&$checks){$checks[]=['name'=>$name,'status'=>$ok?'PASS':'FAIL'];};
$check('workspace workflow preserves selected dataform',str_contains($runtime,"=== 'workflow' && \$selectedDataformId > 0")&&str_contains($runtime,"'&dataform=' . (int)\$selectedDataformId"));
$check('workflow has project-level chooser',str_contains($workflow,'DataForm für Workflow auswählen'));
$check('workflow chooser lists dataforms',str_contains($workflow,'SELECT id,name,slug FROM dataforms ORDER BY name,id'));
$check('workflow selected form validated',str_contains($workflow,'Das ausgewählte DataForm wurde nicht gefunden. Bitte wählen Sie ein vorhandenes DataForm.'));
$check('workflow chooser does not render invalid workflow forms',str_contains($workflow,'<?php if(!$dataform): ?>')&&str_contains($workflow,'<?php else: ?>'));
$check('breadcrumb uses DataForms plural',str_contains($workflow,"['label'=>'DataForms'"));
$check('workflow phase badge removed',!str_contains($workflow,'Phase 15'));
$check('visual workflow phase badge removed',!str_contains($visual,'Phase 16 · Visual Designer'));
$check('runtime editor phase removed',!str_contains($runtime,'<small>Phase 12</small>'));
foreach($checks as $c)echo $c['status'].' '.$c['name'].PHP_EOL;
$failed=array_filter($checks,fn($c)=>$c['status']==='FAIL');
exit($failed?1:0);
