<?php
declare(strict_types=1);
$r=__DIR__;
$checks=[];
$c=function(string $n,bool $ok)use(&$checks){$checks[]=['check'=>$n,'status'=>$ok?'PASS':'FAIL'];};
$del=(string)file_get_contents($r.'/app/projects/delete.php');
$idx=(string)file_get_contents($r.'/app/projects/index.php');
$c('delete dialog exposes optional database delete checkbox',str_contains($del,'name="delete_database"')&&str_contains($del,'Projektdatenbank ebenfalls endgültig löschen'));
$c('database deletion remains opt in',str_contains($del, "\$deleteDatabaseRequested = (string)(\$_POST['delete_database'] ?? '') === '1'")&&str_contains($del, "\$deleteDatabaseRequested ? 'checked' : ''"));
$c('danger warning names irreversible database deletion',str_contains($del,'endgültige Datenlöschung')&&str_contains($del,'unwiderruflich gelöscht'));
$c('database name is strictly validated',str_contains($del,'enterprise_project_delete_valid_db_name')&&str_contains($del,"/^[A-Za-z][A-Za-z0-9_]{1,62}$/"));
$c('system and admin databases are protected',str_contains($del,"'information_schema'")&&str_contains($del,"'performance_schema'")&&str_contains($del,"ADMIN_DB_DATABASE"));
$c('shared project databases are protected',str_contains($del,'database_name = ? AND id <> ?'));
$c('drop database is conditional and verified',str_contains($del,'if ($deleteDatabaseRequested)')&&str_contains($del,"DROP DATABASE ")&&substr_count($del,'enterprise_project_delete_database_exists')>=3);
$c('drop failure keeps registration',str_contains($del,'Die Projektregistrierung bleibt erhalten')&&strpos($del,'DROP DATABASE')<strpos($del,'DELETE FROM projects WHERE id = ?'));
$c('registry delete remains available without database drop',str_contains($del,"'database_deleted' => false")&&str_contains($del,'Die Datenbank bleibt erhalten'));
$c('audit distinguishes requested deleted and missing states',str_contains($del,"'database_delete_requested'")&&str_contains($del,"'database_deleted'")&&str_contains($del,"'database_already_missing'"));
$c('project list help documents deletion choice',str_contains($idx,'ob die Projektdatenbank erhalten bleibt oder zusätzlich endgültig gelöscht wird'));
$f=count(array_filter($checks,fn($x)=>$x['status']!=='PASS'));
echo json_encode(['release'=>'RC1.8','hotfix'=>'HF71','status'=>$f?'FAIL':'PASS','checks'=>$checks,'summary'=>['checks'=>count($checks),'failed'=>$f]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).PHP_EOL;
exit($f?1:0);
