<?php
declare(strict_types=1);
$root=__DIR__;
require_once $root.'/system/ui/ButtonRegistry.php';
$registry=easyit_button_registry();
$css=(string)file_get_contents($root.'/assets/css/easyit-crud-3d-buttons.css');
$js=(string)file_get_contents($root.'/assets/js/easyit-button-registry.js');
$layout=(string)file_get_contents($root.'/system/ui/layout.php');
$workspace=(string)file_get_contents($root.'/products/dataform/system/WorkspaceLayout.php');
$runtime=(string)file_get_contents($root.'/products/dataform/runtime.php');
$records=(string)file_get_contents($root.'/products/dataform/records.php');
$keys=['neu','bearbeiten','loeschen','speichern','abbrechen','anzeigen','kopieren','duplizieren','schliessen','mehr','suchen','filter','filter_loeschen','aktualisieren','sortieren_auf','sortieren_ab','spalten','tabelle','formular','importieren','exportieren','hochladen','herunterladen','drucken','erster_ds','vorheriger_ds','aktueller_ds','naechster_ds','letzter_ds','neuer_ds','normaler_ds','auswaehlen','beziehung','beziehung_neu','beziehung_loeschen','lookup','backup','restore','archivieren','wiederherstellen','sperren','entsperren','einstellungen','hilfe','info','warnung','bestaetigen','start','anmelden','abmelden','verlauf','favorit'];
$checks=[];
$check=function(string $name,bool $ok)use(&$checks){echo ($ok?'PASS':'FAIL')." - $name\n";$checks[]=$ok;};
$check('extended registry contains original 52 plus publication buttons',count($registry)>=56);
$check('original registry keys retained',array_diff($keys,array_keys($registry))===[]);
foreach($keys as $key){$check('image '.$key,is_file($root.'/assets/img/'.$key.'.png'));}
$check('canonical overview',is_file($root.'/assets/img/buttonset.png'));
$check('global JS loaded',str_contains($layout,'easyit-button-registry.js'));
$check('DataForm JS loaded',str_contains($workspace,'easyit-button-registry.js'));
$check('runtime JS loaded',str_contains($runtime,'easyit-button-registry.js'));
$check('global central registry data injected',str_contains($layout,'easyit_button_registry_data_tag()'));
$check('DataForm central registry data injected',str_contains($workspace,'easyit_button_registry_data_tag()'));
$check('runtime central registry data injected',str_contains($runtime,'easyit_button_registry_data_tag()'));
$check('no coloured button rule marker',str_contains($css,'Keine farbigen/gradienten Button-Hintergründe mehr'));
$check('transparent button reset',str_contains($css,'background-color:transparent!important'));
$check('all registry CSS mappings',count(array_filter(array_keys($registry),fn($k)=>str_contains($css,'data-button="'.$k.'"')))===count($registry));
$check('JS consumes central PHP registry payload',str_contains($js,"getElementById('easyit-button-registry-data')"));
$check('JS has no duplicated full registry literal',!str_contains($js,'const REGISTRY={"neu"'));
$check('normal pointer uses central helper',str_contains($records,"easyit_button_attributes(\$isActive?'aktueller_ds':'normaler_ds')"));
$check('new pointer uses central helper',str_contains($records,"easyit_button_attributes('neuer_ds')"));
$check('first record uses central helper',str_contains($records,"easyit_button_attributes('erster_ds')"));
$check('last record uses central helper',str_contains($records,"easyit_button_attributes('letzter_ds')"));
exit(in_array(false,$checks,true)?1:0);
