<?php
declare(strict_types=1);
$r=__DIR__;
$css=(string)file_get_contents($r.'/assets/css/easyit-crud-3d-buttons.css');
$layout=(string)file_get_contents($r.'/system/ui/layout.php');
$runtime=(string)file_get_contents($r.'/products/dataform/runtime.php');
$workspace=(string)file_get_contents($r.'/products/dataform/system/WorkspaceLayout.php');
$c=[];$f=function(string $name,bool $ok)use(&$c):void{$c[]=['check'=>$name,'status'=>$ok?'PASS':'FAIL'];};
$f('global CRUD compatibility stylesheet exists',is_file($r.'/assets/css/easyit-crud-3d-buttons.css'));
$f('global layout loads canonical button stylesheet',str_contains($layout,'easyit-global-crud-3d-css')&&str_contains($layout,'easyit-crud-3d-buttons.css'));
$f('button CSS loads after page styles',strpos($layout,'easyit-global-crud-3d-css')>strpos($layout,"page['styles']"));
$f('standalone DataForm runtime loads canonical button stylesheet',str_contains($runtime,'easyit-global-crud-3d-css'));
$f('WorkspaceLayout loads canonical button stylesheet',str_contains($workspace,'easyit-global-crud-3d-css'));
$f('HF35 3D skin superseded by canonical image policy',str_contains($css,'HF76-FIX7')&&str_contains($css,'supplied PNG buttonset is the only visual source'));
$f('no gradient button paint remains',!str_contains($css,'linear-gradient(')&&!str_contains($css,'radial-gradient('));
$f('registered containers transparent',str_contains($css,'background-color:transparent!important')&&str_contains($css,'box-shadow:none!important'));
$f('explicit data-button supported',str_contains($css,'button[data-button]')&&str_contains($css,'a[data-button]'));
$f('explicit CRUD remains discoverable by JS',str_contains((string)file_get_contents($r.'/assets/js/easyit-button-registry.js'),'const CRUD='));
$f('runtime marker retained',str_contains($runtime,'HF36 DATAFORM RUNTIME ACTIVE')&&str_contains($runtime,'X-EasyIT-DataForm-Runtime: HF36'));
$failed=count(array_filter($c,static fn(array $row):bool=>$row['status']==='FAIL'));
echo json_encode(['release'=>'RC1.8','hotfix'=>'HF35-superseded-by-HF76-FIX7','status'=>$failed===0?'PASS':'FAIL','checks'=>$c,'summary'=>['checks'=>count($c),'failed'=>$failed]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).PHP_EOL;
exit($failed===0?0:1);
