<?php
declare(strict_types=1);
$root=__DIR__;$fail=[];
$check=function(bool $ok,string $msg)use(&$fail){echo($ok?'PASS ':'FAIL ').$msg.PHP_EOL;if(!$ok)$fail[]=$msg;};
$recovery=(string)file_get_contents($root.'/recovery.php');
$index=(string)file_get_contents($root.'/index.php');
$dashboard=(string)file_get_contents($root.'/app/dashboard.php');
$check(str_contains($index,'recovery.php'),'Startseite verlinkt Recovery Console');
$check(str_contains($dashboard,'../recovery.php'),'Enterprise Dashboard verlinkt Recovery Console');
$check(str_contains($recovery,"['127.0.0.1','::1']"),'Recovery besitzt localhost-Fallback');
$check(str_contains($recovery,"enterprise_is_admin"),'Remote Recovery verlangt Admin-Session');
$check(str_contains($recovery,"enterprise_check_csrf"),'Recovery POST ist CSRF-geschützt');
$check(str_contains($recovery,"RESET SETUP"),'Setup-Reset verlangt explizite Bestätigung');
$check(str_contains($recovery,"RESET EASYIT"),'Vollreset verlangt explizite Bestätigung');
$check(str_contains($recovery,"destroy_databases"),'Vollreset verlangt separate Datenbankbestätigung');
$check(str_contains($recovery,"DROP DATABASE IF EXISTS"),'Vollreset besitzt DB-Löschpfad');
$check(str_contains($recovery,"destruktive Vollreset ist ausschließlich über localhost"),'Vollreset ist auf localhost beschränkt');
$check(str_contains($recovery,"databasePreview"),'Vollreset zeigt ermittelte Datenbanken vor Bestätigung');
$check(str_contains($recovery,"storage/recovery/factory-reset"),'Reset archiviert Konfiguration/Lock');
$check(str_contains($recovery,"installed.json"),'Reset kennt Install-Lock');
$check(str_contains($recovery,"DataForm5-Core/.env"),'Reset kennt .env');
exit($fail?1:0);
