<?php
declare(strict_types=1);
$r=__DIR__;
$runtime=(string)file_get_contents($r.'/products/dataform/runtime.php');
$manager=(string)file_get_contents($r.'/products/dataform/system/TableWorkspaceManager.php');
$dfmanager=(string)file_get_contents($r.'/products/dataform/system/DataFormManager.php');
$css=(string)file_get_contents($r.'/products/dataform/assets/workspace.css');
$c=[];$f=function(string $n,bool $ok)use(&$c):void{$c[]=['check'=>$n,'status'=>$ok?'PASS':'FAIL'];};
$f('move action accepted',str_contains($runtime,"'move_managed_column'"));
$f('up control',str_contains($runtime,'name="direction" value="up"'));
$f('down control',str_contains($runtime,'name="direction" value="down"'));
$f('boundary disable',str_contains($runtime,"\$canMoveUp?'':'disabled'")&&str_contains($runtime,"\$canMoveDown?'':'disabled'"));
$f('id fixed',str_contains($manager,'id bleibt an erster Stelle'));
$f('direction whitelist',str_contains($manager,"['up','down']"));
$f('ordinal order',str_contains($manager,'ordinal_position'));
$f('physical modify',str_contains($manager,' MODIFY COLUMN '));
$f('after positioning',str_contains($manager,".' AFTER '"));
$f('exact definition',str_contains($manager,'SHOW CREATE TABLE'));
$f('reconstruction guard',str_contains($manager,'exakte Definition des Feldes'));
$f('binding sync',str_contains($dfmanager,'syncFieldPositionsFromTable'));
$f('sync physical order',str_contains($dfmanager,'SHOW FULL COLUMNS FROM'));
$f('sync positions',str_contains($dfmanager,'UPDATE dataform_fields SET position=?'));
$f('runtime sync call',str_contains($runtime,'DataFormManager::syncFieldPositionsFromTable'));
$f('UI help',str_contains($runtime,'real verschoben werden'));
$f('protected non-id can still move',str_contains($runtime,'<?php if(!$isIdColumn): ?>'));
$f('order CSS',str_contains($css,'.df-column-order-actions'));
$f('HF32 marker',str_contains($runtime,'HF36 DATAFORM RUNTIME ACTIVE'));
$failed=count(array_filter($c,static fn(array $x):bool=>$x['status']==='FAIL'));
echo json_encode(['release'=>'RC1.8','hotfix'=>'HF34','status'=>$failed?'FAIL':'PASS','checks'=>$c,'summary'=>['checks'=>count($c),'failed'=>$failed]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).PHP_EOL;
exit($failed?1:0);
