<?php
declare(strict_types=1);
$root=__DIR__; require_once $root.'/system/ui/ButtonRegistry.php';
$checks=[];$c=function(string $n,bool $ok)use(&$checks){$checks[$n]=$ok?'PASS':'FAIL';};
$index=(string)file_get_contents($root.'/app/projects/index.php');
$dist=(string)file_get_contents($root.'/system/app/project_distribution.php');
$export=(string)file_get_contents($root.'/app/projects/export.php');
$runtime=(string)file_get_contents($root.'/system/app/project_runtime/DataFormApp.php');
$setup=(string)file_get_contents($root.'/system/app/project_runtime/setup.php');
$c('project list export button',str_contains($index,"easyit_button_attributes('exportieren','project_package')")&&str_contains($index,'action="export.php"'));
$c('central export title',easyit_button_title('exportieren','project_package')==='HTML5-Anwenderanwendung exportieren');
$c('minimal runtime zip builder',str_contains($dist,'easyit-dataform-html5-application')&&str_contains($dist,'install/database.sql'));
$c('enterprise tree not bundled',!str_contains($dist,'enterprise_project_distribution_add_tree('));
$c('project uploads scoped',str_contains($dist,'storage/dataform/uploads/project-'));
$c('one HTML5 page per dataform',str_contains($dist,"'/dataforms/'")&&str_contains($runtime,'<!doctype html>'));
$c('standalone database setup',str_contains($setup,'config.php')&&str_contains($setup,'install/database.sql'));
$c('runtime supports CRUD',str_contains($runtime,"\$action==='create'")&&str_contains($runtime,"\$action==='update'")&&str_contains($runtime,"\$action==='delete'"));
$c('runtime supports lookups and media',str_contains($runtime,'df_lookup_options')&&str_contains($runtime,'df_store_upload'));
$c('only selected runtime images',str_contains($dist,"\$imageNames=['easyit-epManager-logo.png'"));
$c('download sha header',str_contains($export,'X-Checksum-SHA256'));
foreach($checks as $n=>$s) echo $s.' '.$n.PHP_EOL;
$failed=count(array_filter($checks,fn($s)=>$s==='FAIL'));
echo 'RESULT '.($failed?'FAIL':'PASS').' '.(count($checks)-$failed).'/'.count($checks).PHP_EOL;exit($failed?1:0);
