<?php
declare(strict_types=1);
$root=__DIR__;
$runtime=(string)file_get_contents($root.'/products/dataform/runtime.php');
$records=(string)file_get_contents($root.'/products/dataform/records.php');
$checks=[];
$c=static function(string $name,bool $ok)use(&$checks):void{$checks[$name]=$ok?'PASS':'FAIL';};
$c('preview iframe receives stored view mode',str_contains($runtime,'&amp;runtime_view=<?= e(in_array((string)($selectedDataform[\'view_mode\']??\'table\')'));
$c('settings form is addressable by preview script',str_contains($runtime,'data-dataform-settings-form'));
$c('preview script reads view mode control',str_contains($runtime,'function selectedViewMode()')&&str_contains($runtime,"querySelector('[name=\"view_mode\"]')"));
$c('preview script forces runtime_view',str_contains($runtime,"u.searchParams.set('runtime_view',mode)"));
$c('view mode change refreshes preview live',str_contains($runtime,"viewControl.addEventListener('change'")&&str_contains($runtime,'loadPreview({unsaved:true})'));
$c('unsaved preview status is explicit',str_contains($runtime,'noch nicht gespeicherte Auswahl'));
$c('manual refresh keeps selected mode',str_contains($runtime,'function loadPreview(options)')&&str_contains($runtime,"document.addEventListener('click'"));
$c('normal runtime subnav is hidden in preview',str_contains($records,'<?php if(!$previewMode): ?>')&&str_contains($records,'<nav class="df-subnav">'));
$c('preview state is explicitly identified',str_contains($records,'Realvorschau der aktuell gewählten DataForm-Ansicht'));
$c('form view normalization remains active',str_contains($records,"if(\$viewMode==='form' && \$mode==='list')"));
$c('configured view still comes from dataform',str_contains($records,'$configuredViewMode')&&str_contains($records,"\$viewMode=\$runtimeViewOverride!==''?\$runtimeViewOverride:\$configuredViewMode"));
foreach($checks as $name=>$status) echo "$status $name\n";
$fail=count(array_filter($checks,static fn(string $v):bool=>$v==='FAIL'));
echo 'RESULT '.(count($checks)-$fail).'/'.count($checks).' PASS'.($fail?", $fail FAIL":"")."\n";
exit($fail?1:0);
