<?php
declare(strict_types=1);
$root=__DIR__;
$records=file_get_contents($root.'/products/dataform/records.php');
$runtime=file_get_contents($root.'/products/dataform/runtime.php');
$app=file_get_contents($root.'/system/app/project_runtime/DataFormApp.php');
$js=file_get_contents($root.'/system/app/project_runtime/assets/app.js');
$css=file_get_contents($root.'/system/app/project_runtime/assets/app.css');
$checks=[];
$c=function(string $n,bool $v)use(&$checks){$checks[$n]=$v?'PASS':'FAIL';};
$c('configured view mode is read',str_contains($records,'$configuredViewMode')&&str_contains($records,"['form','table','dialog']"));
$c('form standard view overrides list mode',str_contains($records,"if(\$viewMode==='form' && \$mode==='list')")&&str_contains($records,"\$mode=\$allowEdit?'edit':'detail'"));
$c('form view has record navigator',str_contains($records,'df-form-record-nav')&&str_contains($records,"easyit_button_attributes('vorheriger_ds')")&&str_contains($records,"easyit_button_attributes('naechster_ds')"));
$c('dialog view has real modal',str_contains($records,'df-runtime-record-dialog')&&str_contains($records,'data-dialog-frame')&&str_contains($records,'data-dialog-record'));
$c('dialog opens editable embedded form',str_contains($records,"u.searchParams.set('runtime_view','form')")&&str_contains($records,"u.searchParams.set('dialog_embed','1')"));
$c('dialog embed is writable outside preview',str_contains($records,'else if(dialogEmbed)')&&str_contains($records,"const preview=<?= \$previewMode?'true':'false' ?>"));
$c('child preview inherits child standard view',str_contains($records,"u.searchParams.delete('mode')")&&!str_contains($records,"u.searchParams.set('mode','list');"));
$c('per page accepts one in runtime save',str_contains($runtime,"max(1,min(200,(int)(\$_POST['default_per_page']??20)))")&&str_contains($runtime,'name="default_per_page" min="1"'));
$c('per page accepts one in enterprise records',str_contains($records,"max(1,min(200,(int)(\$dataform['default_per_page']??20)))")&&str_contains($records,'foreach([1,5,10,20,50,100] as $n)'));
$c('export runtime has separate form branch',str_contains($app,"if(\$viewMode==='form')")&&str_contains($app,'form-record-nav')&&str_contains($app,'runtime-record-form'));
$c('export runtime has separate dialog branch',str_contains($app,"elseif(\$viewMode==='dialog')")||str_contains($app,"if(\$viewMode==='dialog')"));
$c('export dialog uses templates',str_contains($app,'dialog-record-')&&str_contains($app,'dialog-new-record')&&str_contains($app,'runtime-dialog'));
$c('export runtime per page accepts one',str_contains($app,"max(1,min(200,(int)(\$form['default_per_page']??20)))")&&str_contains($app,"max(1,min(200,(int)(\$_GET['per_page']??\$defaultPer)))"));
$c('export JS opens actual dialog templates',str_contains($js,'openTemplate')&&str_contains($js,'data-dialog-record')&&str_contains($js,"settings.view_mode!=='dialog'"));
$c('obsolete fake form hiding removed',!str_contains($css,'.view-form .table-wrap{display:none}'));
$c('form and dialog CSS exist',str_contains($css,'.form-record-nav')&&str_contains($css,'.runtime-dialog.size-fullscreen'));
foreach($checks as $n=>$v)echo "$v $n\n";
$fail=count(array_filter($checks,fn($v)=>$v==='FAIL'));
echo 'RESULT '.(count($checks)-$fail).'/'.count($checks).' PASS'.($fail?", $fail FAIL":"")."\n";
exit($fail?1:0);
