<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/system/app/bootstrap.php';
require dirname(__DIR__,2).'/system/ui/layout.php';
use DataForm5\Modules\Config\{ModuleConfigSchema,ModuleConfigRepository,ModuleConfigManager};
$user=enterprise_require_auth('../../');
enterprise_require_capability($user,'modules.configure');
$pdo=enterprise_pdo(); enterprise_upgrade($pdo); $base=dirname(__DIR__,2);
$module=preg_replace('/[^a-zA-Z0-9._-]/','',(string)($_GET['module']??$_POST['module']??''));
$scope=(string)($_GET['scope']??$_POST['scope']??'enterprise'); if(!in_array($scope,['enterprise','product','project'],true))$scope='enterprise';
$scopeId=trim((string)($_GET['scope_id']??$_POST['scope_id']??'global')); if($scopeId==='')$scopeId='global';
$modulePath=$base.'/modules/'.$module; if($module===''||!is_dir($modulePath)){http_response_code(404);exit('Modul nicht gefunden.');}
$env=enterprise_env($base.'/DataForm5-Core/.env'); $key=(string)($env['DATAFORM_APP_KEY']??$env['APP_KEY']??'');
$repo=new ModuleConfigRepository($pdo,$key); $manager=new ModuleConfigManager($repo); $schema=ModuleConfigSchema::fromModule($modulePath); $message='';$error='';$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{enterprise_check_csrf((string)($_POST['csrf']??''));$values=[];foreach($schema->fields as $name=>$def){$type=(string)($def['type']??'string');if($type==='bool')$values[$name]=isset($_POST['cfg'][$name])?'1':'0';else $values[$name]=(string)($_POST['cfg'][$name]??'');} $result=$manager->save($module,$modulePath,$values,$scope,$scopeId);if(!$result['valid']){$errors=$result['errors'];throw new RuntimeException('Bitte Konfiguration prüfen.');}enterprise_audit($pdo,(int)($user['id']??0),'module.config.update','module',$module,['scope'=>$scope,'scope_id'=>$scopeId]);enterprise_event_dispatch('module.config.updated',['name'=>$module,'scope'=>$scope,'scope_id'=>$scopeId],['user_id'=>$user['id']??null]);$message='Konfiguration gespeichert.';}catch(Throwable $e){$error=$e->getMessage();}
}
$current=$manager->get($module,$modulePath,$scope,$scopeId);$secretNames=$schema->secrets();
ob_start();render_breadcrumbs([['label'=>'Enterprise','href'=>'../dashboard.php'],['label'=>'Module','href'=>'index.php'],['label'=>$module,'href'=>'']]);?>
<section class="hero"><span class="badge">RC1.7 · Phase K</span><h1>Modulkonfiguration: <?=e($module)?></h1><p>Typisierte Einstellungen mit Enterprise-, Produkt- oder Projekt-Scope. Secret-Werte werden getrennt verschlüsselt gespeichert.</p></section>
<?php if($message):?><div class="card"><strong><?=e($message)?></strong></div><?php endif;?><?php if($error):?><div class="card"><strong>Fehler:</strong> <?=e($error)?></div><?php endif;?>
<section class="card"><form method="get"><input type="hidden" name="module" value="<?=e($module)?>"><label>Scope <select name="scope"><option value="enterprise" <?=$scope==='enterprise'?'selected':''?>>Enterprise</option><option value="product" <?=$scope==='product'?'selected':''?>>Produkt</option><option value="project" <?=$scope==='project'?'selected':''?>>Projekt</option></select></label> <label>Scope-ID <input name="scope_id" value="<?=e($scopeId)?>"></label> <button class="button secondary" type="submit">Laden</button></form></section>
<section class="card"><h2>Einstellungen</h2><?php if($schema->fields===[]):?><p>Dieses Modul definiert noch kein <code>config/schema.php</code>.</p><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="module" value="<?=e($module)?>"><input type="hidden" name="scope" value="<?=e($scope)?>"><input type="hidden" name="scope_id" value="<?=e($scopeId)?>">
<?php foreach($schema->fields as $name=>$def):$type=(string)($def['type']??'string');$secret=in_array($name,$secretNames,true);$value=$current[$name]??($def['default']??'');?><p><label><strong><?=e((string)($def['label']??$name))?></strong><br><?php if($type==='bool'):?><input type="checkbox" name="cfg[<?=e($name)?>]" value="1" <?=$value?'checked':''?>> aktiviert<?php elseif(isset($def['options'])&&is_array($def['options'])):?><select name="cfg[<?=e($name)?>]"><?php foreach($def['options'] as $opt):?><option value="<?=e((string)$opt)?>" <?=$value===$opt?'selected':''?>><?=e((string)$opt)?></option><?php endforeach;?></select><?php else:?><input type="<?=$secret?'password':($type==='int'||$type==='float'?'number':'text')?>" name="cfg[<?=e($name)?>]" value="<?=$secret?'':e((string)$value)?>" <?=$secret?'placeholder="Unverändert lassen oder neuen Wert eingeben"':''?>><?php endif;?><?php if(isset($errors[$name])):?><br><strong><?=e((string)$errors[$name])?></strong><?php endif;?></label></p><?php endforeach;?><button class="button" type="submit">Konfiguration speichern</button></form><?php endif;?></section>
<?php $content=ob_get_clean();render_page(['title'=>'Modulkonfiguration','active'=>'modules','base'=>'../../','content'=>$content,'app_nav'=>true,'user'=>$user,'help'=>['title'=>'Modulkonfiguration','location'=>'Enterprise → Module → Konfiguration','short'=>'Verwaltet typisierte Modulwerte getrennt vom Paket.','goal'=>'Modulwerte sicher pro Scope konfigurieren.','next'=>'Scope wählen, Werte setzen und speichern.','steps'=>['Scope auswählen.','Werte prüfen.','Secrets bei Bedarf neu eingeben.','Speichern.'],'tips'=>['Secrets benötigen APP_KEY oder DATAFORM_APP_KEY.','Leere Secret-Felder überschreiben bestehende Secrets nicht.']]]);
