<?php
declare(strict_types=1);
namespace DataForm5\Http\Core;
use DataForm5\Core\Container\ServiceContainer; use DataForm5\Http\Exceptions\HttpException; use Throwable;
final class Router {
    /** @var list<Route> */ private array $routes=[]; /** @var array<string,Route> */ private array $named=[]; /** @var list<mixed> */ private array $globalMiddleware=[];
    public function __construct(private readonly ServiceContainer $container){}
    public function add(array|string $methods,string $path,mixed $handler):Route{$route=new Route(array_map('strtoupper',(array)$methods),$this->normalizePath($path),$handler);$this->routes[]=$route;return $route;} public function get(string $p,mixed $h):Route{return $this->add('GET',$p,$h);} public function post(string $p,mixed $h):Route{return $this->add('POST',$p,$h);} public function put(string $p,mixed $h):Route{return $this->add('PUT',$p,$h);} public function patch(string $p,mixed $h):Route{return $this->add('PATCH',$p,$h);} public function delete(string $p,mixed $h):Route{return $this->add('DELETE',$p,$h);} public function middleware(mixed ...$m):self{array_push($this->globalMiddleware,...$m);return $this;}
    public function dispatch(Request $request):Response{try{foreach($this->routes as $route){if(!in_array($request->method(),$route->methods,true))continue;$params=$this->match($route->path,$request->uri());if($params===null)continue;if($route->name)$this->named[$route->name]=$route;$r=$request;foreach($params as $k=>$v)$r=$r->withAttribute($k,$v);$pipeline=new MiddlewarePipeline($this->container);return $pipeline->process($r,array_merge($this->globalMiddleware,$route->middleware),fn(Request $req)=>$this->invoke($route->handler,$req,$params));}throw new HttpException(404,'Route nicht gefunden.');}catch(HttpException $e){return Response::json(['error'=>$e->getMessage()],$e->status);}catch(Throwable $e){return Response::json(['error'=>$e->getMessage()],500);}}
    public function url(string $name,array $params=[]):string{foreach($this->routes as $route)if($route->name===$name){$url=$route->path;foreach($params as $k=>$v)$url=str_replace('{'.$k.'}',rawurlencode((string)$v),$url);if(preg_match('/\{[^}]+\}/',$url))throw new \InvalidArgumentException('Fehlender Routenparameter.');return $url;}throw new \InvalidArgumentException('Unbekannte Route: '.$name);}
    private function invoke(mixed $handler,Request $request,array $params):mixed{if(is_array($handler)&&is_string($handler[0]))$handler=[$this->container->get($handler[0]),$handler[1]];return $handler($request,...array_values($params));}
    private function match(string $route,string $uri):?array{$names=[];$offset=0;$regex='';if(preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/',$route,$tokens,PREG_OFFSET_CAPTURE)){foreach($tokens[0] as $i=>$token){$literal=substr($route,$offset,$token[1]-$offset);$regex.=preg_quote($literal,'#').'([^/]+)';$names[]=$tokens[1][$i][0];$offset=$token[1]+strlen($token[0]);}}$regex.=preg_quote(substr($route,$offset),'#');if(!preg_match('#^'.$regex.'$#',$uri,$matches))return null;array_shift($matches);$out=[];foreach($names as $i=>$n)$out[$n]=rawurldecode($matches[$i]??'');return $out;}
    private function normalizePath(string $p):string{$p='/'.trim($p,'/');return $p==='/'?'/':rtrim($p,'/');}
}
