<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';
require_once dirname(__DIR__,2).'/system/ui/layout.php';
require_once __DIR__.'/system/ApiDesigner.php';
$user=enterprise_require_auth('../../');
$projectId=(int)($_GET['project']??$_POST['project']??($_SESSION['active_project_id']??0));$apiId=(int)($_GET['api_id']??$_POST['api_id']??0);$error='';$success='';$newKey='';$project=null;$apis=[];$api=null;$endpoints=[];$keys=[];$logs=[];$dataforms=[];
try{
 $admin=enterprise_pdo();enterprise_upgrade($admin);$s=$admin->prepare('SELECT * FROM projects WHERE id=? AND product_type=? LIMIT 1');$s->execute([$projectId,'dataform']);$project=$s->fetch();if(!$project)throw new RuntimeException('DataForm-Projekt wurde nicht gefunden.');$_SESSION['active_project_id']=$projectId;
 $env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');$pdo=new PDO('mysql:host='.($env['PROJECT_DB_HOST']??'127.0.0.1').';port='.(int)($env['PROJECT_DB_PORT']??3306).';dbname='.$project['database_name'].';charset='.($env['PROJECT_DB_CHARSET']??'utf8mb4'),(string)($env['PROJECT_DB_USERNAME']??''),(string)($env['PROJECT_DB_PASSWORD']??''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);ApiDesigner::ensureSchema($pdo);
 if($_SERVER['REQUEST_METHOD']==='POST'){enterprise_check_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');
  if($action==='create_api'){$name=trim((string)($_POST['name']??''));$slug=ApiDesigner::slug((string)($_POST['slug']??$name));if($name===''||$slug==='')throw new RuntimeException('Name und interner API-Name sind erforderlich.');$version=trim((string)($_POST['version']??'1.0.0'));if(!preg_match('/^\d+\.\d+\.\d+$/',$version))throw new RuntimeException('Die Version muss dem Muster 1.0.0 entsprechen.');$stmt=$pdo->prepare('INSERT INTO api_definitions(name,slug,version,description,base_path,created_by) VALUES(?,?,?,?,?,?)');$stmt->execute([$name,$slug,$version,trim((string)($_POST['description']??''))?:null,'/api/'.$slug,$user['id']??null]);$apiId=(int)$pdo->lastInsertId();$success='API wurde angelegt.';}
  elseif($action==='add_endpoint'){$apiId=(int)$_POST['api_id'];$name=trim((string)$_POST['name']);$slug=ApiDesigner::slug((string)($_POST['slug']??$name));$method=in_array($_POST['http_method']??'', ['GET','POST','PATCH','DELETE'],true)?(string)$_POST['http_method']:'GET';$operation=in_array($_POST['operation']??'', ['list','detail','create','update','delete'],true)?(string)$_POST['operation']:'list';$expected=['list'=>'GET','detail'=>'GET','create'=>'POST','update'=>'PATCH','delete'=>'DELETE'];if($method!==$expected[$operation])throw new RuntimeException('HTTP-Methode und Operation passen nicht zusammen.');$df=(int)($_POST['dataform_id']??0);if($df<1)throw new RuntimeException('Bitte wählen Sie ein DataForm.');$fields=array_values(array_filter(array_map('strval',(array)($_POST['fields']??[]))));$stmt=$pdo->prepare('INSERT INTO api_endpoints(api_id,dataform_id,name,slug,http_method,operation,requires_auth,rate_limit_per_minute,fields_json) VALUES(?,?,?,?,?,?,?,?,?)');$stmt->execute([$apiId,$df,$name,$slug,$method,$operation,isset($_POST['requires_auth'])?1:0,max(1,min(10000,(int)($_POST['rate_limit']??60))),json_encode($fields,JSON_UNESCAPED_UNICODE)]);$success='API-Endpunkt wurde angelegt.';}
  elseif($action==='delete_endpoint'){$apiId=(int)$_POST['api_id'];$pdo->prepare('DELETE FROM api_endpoints WHERE id=? AND api_id=?')->execute([(int)$_POST['endpoint_id'],$apiId]);$success='Endpunkt wurde gelöscht.';}
  elseif($action==='create_key'){$apiId=(int)$_POST['api_id'];$name=trim((string)($_POST['key_name']??''));if($name==='')throw new RuntimeException('Bitte benennen Sie den API-Schlüssel.');$generated=ApiDesigner::generateKey();$expires=trim((string)($_POST['expires_at']??''))?:null;$pdo->prepare('INSERT INTO api_keys(api_id,name,key_prefix,key_hash,role_name,expires_at) VALUES(?,?,?,?,?,?)')->execute([$apiId,$name,$generated['prefix'],$generated['hash'],trim((string)($_POST['role_name']??'api'))?:'api',$expires]);$newKey=$generated['plain'];$success='API-Schlüssel wurde erstellt. Kopieren Sie ihn jetzt; später wird er nicht erneut angezeigt.';}
  elseif($action==='revoke_key'){$apiId=(int)$_POST['api_id'];$pdo->prepare('UPDATE api_keys SET is_active=0 WHERE id=? AND api_id=?')->execute([(int)$_POST['key_id'],$apiId]);$success='API-Schlüssel wurde widerrufen.';}
 }
 $apis=$pdo->query('SELECT * FROM api_definitions ORDER BY name')->fetchAll();if($apiId<1&&$apis)$apiId=(int)$apis[0]['id'];
 $dataforms=$pdo->query('SELECT id,name,slug FROM dataforms ORDER BY name')->fetchAll();foreach($dataforms as &$df){$q=$pdo->prepare('SELECT name,label,field_type,is_required,configuration_json FROM dataform_fields WHERE dataform_id=? ORDER BY position,id');$q->execute([(int)$df['id']]);$df['fields']=$q->fetchAll();}unset($df);
 if($apiId>0){$q=$pdo->prepare('SELECT * FROM api_definitions WHERE id=?');$q->execute([$apiId]);$api=$q->fetch();if($api){$q=$pdo->prepare('SELECT e.*,d.name AS dataform_name,d.slug AS dataform_slug FROM api_endpoints e LEFT JOIN dataforms d ON d.id=e.dataform_id WHERE e.api_id=? ORDER BY e.slug,e.http_method');$q->execute([$apiId]);$endpoints=$q->fetchAll();$q=$pdo->prepare('SELECT id,name,key_prefix,role_name,is_active,expires_at,last_used_at,created_at FROM api_keys WHERE api_id=? ORDER BY id DESC');$q->execute([$apiId]);$keys=$q->fetchAll();$q=$pdo->prepare('SELECT l.*,e.name AS endpoint_name FROM api_request_log l LEFT JOIN api_endpoints e ON e.id=l.endpoint_id WHERE l.api_id=? ORDER BY l.id DESC LIMIT 50');$q->execute([$apiId]);$logs=$q->fetchAll();}}
 if($api && isset($_GET['openapi'])){$base=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']),'/').'/api-runtime.php/'.$projectId.'/'.rawurlencode((string)$api['slug']);$spec=ApiDesigner::openApi($api,$endpoints,$dataforms,$base);header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="'.ApiDesigner::slug((string)$api['name']).'-openapi.json"');echo json_encode($spec,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
}catch(Throwable $e){$error=$e->getMessage();}
ob_start();
?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs([['label'=>'Enterprise','href'=>'../../app/dashboard.php'],['label'=>'Projekte','href'=>'../../app/projects/index.php'],['label'=>(string)($project['name']??'DataForm'),'href'=>$project?'../../app/projects/view.php?id='.(int)$project['id']:''],['label'=>'DataForm Workspace','href'=>'index.php?project='.$projectId],['label'=>'REST API Designer','href'=>'']]);?></div>
<div class="df-workspace"><header class="df-workspace-header"><div><span class="badge">DataForm Workspace</span><h1>REST API Designer</h1><p>Versionierte REST-Endpunkte, Bearer-Schlüssel, Rate-Limits und OpenAPI-Dokumentation konfigurieren.</p></div><div class="actions"><a class="button secondary" href="index.php?project=<?=$projectId?>">Zum Workspace</a></div></header>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif;?><?php if($newKey):?><div class="notice warning"><strong>Neuer API-Schlüssel – nur jetzt sichtbar:</strong><pre><?=e($newKey)?></pre></div><?php endif;?>
<div class="df-workspace-grid"><aside class="df-explorer"><div class="df-pane-title">APIs</div><nav><a href="index.php?project=<?=$projectId?>">Workspace</a><a class="<?=!$apiId?'active':''?>" href="api.php?project=<?=$projectId?>">+ Neue API</a><?php foreach($apis as $a):?><a class="<?=$apiId===(int)$a['id']?'active':''?>" href="api.php?project=<?=$projectId?>&api_id=<?=(int)$a['id']?>">⌁ <?=e((string)$a['name'])?> <small>v<?=e((string)$a['version'])?></small></a><?php endforeach;?></nav></aside>
<main class="df-main">
<?php if(!$api):?><section class="card"><h2>Neue API anlegen</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="action" value="create_api"><label>Name<input name="name" required placeholder="z. B. Kunden-API"></label><label>Interner Name<input name="slug" placeholder="kunden-api"></label><label>Version<input name="version" value="1.0.0" required></label><label class="full">Beschreibung<textarea name="description" rows="3"></textarea></label><div class="full"><button class="button">API anlegen</button></div></form></section>
<?php else:?>
<section class="card"><div class="report-toolbar"><div><h2><?=e((string)$api['name'])?> <small>v<?=e((string)$api['version'])?></small></h2><p><?=e((string)($api['description']??''))?></p></div><div class="actions"><a class="button secondary" href="api.php?project=<?=$projectId?>&api_id=<?=$apiId?>&openapi=1">OpenAPI JSON</a></div></div><p><strong>Basis:</strong> <code>api-runtime.php?project=<?=$projectId?>&api=<?=e((string)$api['slug'])?>&endpoint=…</code></p></section>
<section class="card"><h2>Endpunkt anlegen</h2><form method="post" class="form-grid" id="endpoint-form"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="api_id" value="<?=$apiId?>"><input type="hidden" name="action" value="add_endpoint"><label>Name<input name="name" required placeholder="Kunden auflisten"></label><label>Pfadname<input name="slug" required placeholder="customers"></label><label>Operation<select name="operation" id="operation"><option value="list">Liste lesen</option><option value="detail">Detail lesen</option><option value="create">Datensatz anlegen</option><option value="update">Datensatz ändern</option><option value="delete">Datensatz löschen</option></select></label><label>HTTP-Methode<select name="http_method" id="http-method"><option>GET</option><option>POST</option><option>PATCH</option><option>DELETE</option></select></label><label>DataForm<select name="dataform_id" id="api-dataform" onchange="showApiFields()"><?php foreach($dataforms as $d):?><option value="<?=(int)$d['id']?>"><?=e((string)$d['name'])?></option><?php endforeach;?></select></label><label>Rate-Limit pro Minute<input type="number" min="1" max="10000" name="rate_limit" value="60"></label><label class="full"><input type="checkbox" name="requires_auth" checked> Bearer-Schlüssel erforderlich</label><?php foreach($dataforms as $d):?><div class="full api-fields" data-dataform="<?=(int)$d['id']?>" style="display:none"><strong>Freigegebene Felder</strong><div class="query-field-grid"><?php foreach($d['fields'] as $f):?><label><input type="checkbox" name="fields[]" value="<?=e((string)$f['name'])?>"> <?=e((string)$f['label'])?></label><?php endforeach;?></div><small>Ohne Auswahl werden alle Felder freigegeben.</small></div><?php endforeach;?><div class="full"><button class="button">Endpunkt anlegen</button></div></form></section>
<section class="card"><h2>Endpunkte</h2><?php if(!$endpoints):?><div class="empty-state">Noch keine Endpunkte.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Methode</th><th>Pfad</th><th>Operation</th><th>DataForm</th><th>Schutz</th><th>Limit</th><th></th></tr></thead><tbody><?php foreach($endpoints as $ep):?><tr><td><strong><?=e((string)$ep['http_method'])?></strong></td><td><code>/<?=e((string)$ep['slug'])?><?=in_array($ep['operation'],['detail','update','delete'],true)?'/{id}':''?></code></td><td><?=e((string)$ep['operation'])?></td><td><?=e((string)$ep['dataform_name'])?></td><td><?=(int)$ep['requires_auth']?'Bearer':'öffentlich'?></td><td><?=(int)$ep['rate_limit_per_minute']?>/min</td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="api_id" value="<?=$apiId?>"><input type="hidden" name="endpoint_id" value="<?=(int)$ep['id']?>"><button class="link-danger" name="action" value="delete_endpoint" onclick="return confirm('Endpunkt löschen?')">Löschen</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="card"><h2>API-Schlüssel</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="api_id" value="<?=$apiId?>"><input type="hidden" name="action" value="create_key"><label>Name<input name="key_name" required placeholder="Entwicklung"></label><label>Rolle<input name="role_name" value="api"></label><label>Ablaufdatum<input type="datetime-local" name="expires_at"></label><div><button class="button">Schlüssel erzeugen</button></div></form><?php if($keys):?><div class="table-wrap"><table><thead><tr><th>Name</th><th>Präfix</th><th>Rolle</th><th>Status</th><th>Letzte Nutzung</th><th></th></tr></thead><tbody><?php foreach($keys as $k):?><tr><td><?=e((string)$k['name'])?></td><td><code><?=e((string)$k['key_prefix'])?>…</code></td><td><?=e((string)$k['role_name'])?></td><td><?=(int)$k['is_active']?'aktiv':'widerrufen'?></td><td><?=e((string)($k['last_used_at']??'–'))?></td><td><?php if((int)$k['is_active']):?><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="api_id" value="<?=$apiId?>"><input type="hidden" name="key_id" value="<?=(int)$k['id']?>"><button class="link-danger" name="action" value="revoke_key">Widerrufen</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="card"><h2>Letzte API-Aufrufe</h2><?php if(!$logs):?><div class="empty-state">Noch keine Aufrufe protokolliert.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Methode</th><th>Endpunkt</th><th>Status</th><th>Dauer</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><?=e((string)$l['created_at'])?></td><td><?=e((string)$l['request_method'])?></td><td><?=e((string)($l['endpoint_name']??'–'))?></td><td><?=(int)$l['response_status']?></td><td><?=(int)$l['duration_ms']?> ms</td><td><?=e((string)($l['client_ip']??'–'))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php endif;?></main><aside class="df-properties"><div class="df-pane-title">Kontexthilfe</div><h3>Ziel</h3><p>DataForms als versionierte REST-Schnittstellen veröffentlichen.</p><h3>Authentifizierung</h3><p>API-Schlüssel werden nur gehasht gespeichert und als Bearer-Token übertragen.</p><h3>Rate-Limit</h3><p>Jeder Endpunkt begrenzt Aufrufe pro Schlüssel und Minute.</p><h3>OpenAPI</h3><p>Die generierte JSON-Datei kann in Swagger UI, Postman oder andere Werkzeuge importiert werden.</p></aside></div></div>
<script>const op=document.getElementById('operation'),method=document.getElementById('http-method');if(op&&method){op.addEventListener('change',()=>{method.value={list:'GET',detail:'GET',create:'POST',update:'PATCH',delete:'DELETE'}[op.value]||'GET';});}function showApiFields(){const id=document.getElementById('api-dataform')?.value;document.querySelectorAll('.api-fields').forEach(el=>el.style.display=el.dataset.dataform===id?'block':'none');}showApiFields();</script>
<?php $content=ob_get_clean();render_page(['title'=>'REST API Designer','active'=>'projects','base'=>'../../','content'=>$content,'app_nav'=>true,'body_class'=>'workspace-page','help'=>['title'=>'REST API Designer','location'=>'DataForm → REST API Designer','short'=>'REST-Endpunkte, Schlüssel und OpenAPI-Dokumentation konfigurieren.','goal'=>'Eine gesicherte, dokumentierte API für ein DataForm bereitstellen.','next'=>'API anlegen, Endpunkt konfigurieren und Bearer-Schlüssel erzeugen.','steps'=>['API und Version anlegen.','Endpunkt und DataForm wählen.','Felder und Rate-Limit festlegen.','Schlüssel erzeugen und OpenAPI-Datei testen.'],'duration'=>'ca. 10 Minuten']]);
