<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';
require_once dirname(__DIR__,2).'/system/ui/layout.php';
require_once __DIR__.'/system/ApplicationBuilder.php';
$user=enterprise_require_auth('../../');
$projectId=(int)($_GET['project']??$_POST['project']??($_SESSION['active_project_id']??0));
$appId=(int)($_GET['app']??$_POST['app']??0); $error='';$success='';$project=null;$application=null;$applications=[];$navigation=[];$widgets=[];$builds=[];
try{
 $admin=enterprise_pdo();enterprise_upgrade($admin);$s=$admin->prepare('SELECT * FROM projects WHERE id=? AND product_type=? LIMIT 1');$s->execute([$projectId,'dataform']);$project=$s->fetch();if(!$project)throw new RuntimeException('DataForm-Projekt wurde nicht gefunden.');$_SESSION['active_project_id']=$projectId;
 $env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');$pdo=new PDO('mysql:host='.($env['PROJECT_DB_HOST']??'127.0.0.1').';port='.(int)($env['PROJECT_DB_PORT']??3306).';dbname='.$project['database_name'].';charset='.($env['PROJECT_DB_CHARSET']??'utf8mb4'),(string)($env['PROJECT_DB_USERNAME']??''),(string)($env['PROJECT_DB_PASSWORD']??''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);ApplicationBuilder::ensureSchema($pdo);
 if($_SERVER['REQUEST_METHOD']==='POST'){
  enterprise_check_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');
  if($action==='create_app'){$name=trim((string)($_POST['name']??''));if($name==='')throw new RuntimeException('Anwendungsname fehlt.');$slug=ApplicationBuilder::slug((string)($_POST['slug']??$name));$stmt=$pdo->prepare('INSERT INTO applications(project_id,name,slug,version,description,environment,created_by) VALUES(?,?,?,?,?,?,?)');$stmt->execute([$projectId,$name,$slug,trim((string)($_POST['version']??'1.0.0'))?:'1.0.0',trim((string)($_POST['description']??''))?:null,(string)($_POST['environment']??'development'),$user['id']??null]);$appId=(int)$pdo->lastInsertId();$success='Anwendung wurde angelegt.';}
  elseif($action==='add_nav'){$stmt=$pdo->prepare('INSERT INTO application_navigation(application_id,label,target_type,target_value,icon,role_name,position,is_visible) VALUES(?,?,?,?,?,?,?,1)');$stmt->execute([$appId,trim((string)$_POST['label']),(string)($_POST['target_type']??'dataform'),trim((string)($_POST['target_value']??''))?:null,trim((string)($_POST['icon']??''))?:null,trim((string)($_POST['role_name']??''))?:null,(int)($_POST['position']??10)]);$success='Navigationseintrag wurde gespeichert.';}
  elseif($action==='add_widget'){$cfg=['source'=>trim((string)($_POST['source']??''))];$stmt=$pdo->prepare('INSERT INTO application_dashboard(application_id,widget_type,title,configuration_json,position,width) VALUES(?,?,?,?,?,?)');$stmt->execute([$appId,(string)($_POST['widget_type']??'metric'),trim((string)$_POST['title']),json_encode($cfg,JSON_UNESCAPED_UNICODE), (int)($_POST['position']??10),(string)($_POST['width']??'50')]);$success='Dashboard-Widget wurde gespeichert.';}
  elseif($action==='delete_nav'){$pdo->prepare('DELETE FROM application_navigation WHERE id=? AND application_id=?')->execute([(int)$_POST['id'],$appId]);$success='Navigationseintrag wurde gelöscht.';}
  elseif($action==='delete_widget'){$pdo->prepare('DELETE FROM application_dashboard WHERE id=? AND application_id=?')->execute([(int)$_POST['id'],$appId]);$success='Widget wurde gelöscht.';}
  elseif($action==='build'){$q=$pdo->prepare('SELECT * FROM applications WHERE id=? AND project_id=?');$q->execute([$appId,$projectId]);$application=$q->fetch();if(!$application)throw new RuntimeException('Anwendung wurde nicht gefunden.');$result=ApplicationBuilder::build($pdo,$application,$project,$user,dirname(__DIR__,2));header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.$result['filename'].'"');header('Content-Length: '.$result['size']);header('X-Checksum-SHA256: '.$result['sha256']);readfile($result['path']);exit;}
 }
 $applications=$pdo->prepare('SELECT * FROM applications WHERE project_id=? ORDER BY name');$applications->execute([$projectId]);$applications=$applications->fetchAll();if($appId<1&&$applications)$appId=(int)$applications[0]['id'];if($appId>0){$q=$pdo->prepare('SELECT * FROM applications WHERE id=? AND project_id=?');$q->execute([$appId,$projectId]);$application=$q->fetch();if($application){$q=$pdo->prepare('SELECT * FROM application_navigation WHERE application_id=? ORDER BY position,id');$q->execute([$appId]);$navigation=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM application_dashboard WHERE application_id=? ORDER BY position,id');$q->execute([$appId]);$widgets=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM application_builds WHERE application_id=? ORDER BY created_at DESC LIMIT 20');$q->execute([$appId]);$builds=$q->fetchAll();}}
}catch(Throwable $e){$error=$e->getMessage();}
ob_start();
?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs([['label'=>'Enterprise','href'=>'../../app/dashboard.php'],['label'=>'Projekte','href'=>'../../app/projects/index.php'],['label'=>(string)($project['name']??'DataForm'),'href'=>$project?'../../app/projects/view.php?id='.(int)$project['id']:''],['label'=>'DataForm Workspace','href'=>'index.php?project='.$projectId],['label'=>'Application Builder','href'=>'']]);?></div>
<div class="df-workspace"><header class="df-workspace-header"><div><span class="badge">DataForm Workspace</span><h1>Application Builder</h1><p>Aus dem DataForm-Projekt eine veröffentlichbare Anwendung konfigurieren und als Build erzeugen.</p></div><div class="actions"><a class="button secondary" href="index.php?project=<?=$projectId?>">Zum Workspace</a></div></header>
<?php if($error):?><div class="notice error" role="alert"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice success" role="status"><?=e($success)?></div><?php endif;?>
<div class="df-workspace-grid"><aside class="df-explorer"><div class="df-pane-title">Anwendungen</div><nav><a href="index.php?project=<?=$projectId?>">Workspace</a><a class="active" href="applications.php?project=<?=$projectId?>">Application Builder</a><?php foreach($applications as $a):?><a class="<?=$appId===(int)$a['id']?'active':''?>" href="applications.php?project=<?=$projectId?>&app=<?=(int)$a['id']?>">↳ <?=e((string)$a['name'])?></a><?php endforeach;?></nav></aside>
<main class="df-main">
<section class="card"><h2>Neue Anwendung</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="action" value="create_app"><label>Name<input name="name" required placeholder="z. B. Kundenverwaltung"></label><label>Interner Name<input name="slug" placeholder="wird automatisch erzeugt"></label><label>Version<input name="version" value="1.0.0"></label><label>Zielumgebung<select name="environment"><option value="development">Entwicklung</option><option value="test">Test</option><option value="production">Produktion</option></select></label><label class="full">Beschreibung<textarea name="description" rows="3"></textarea></label><div class="full actions"><button class="button">Anwendung anlegen</button></div></form></section>
<?php if($application):?>
<section class="card"><div class="df-toolbar"><div><h2><?=e((string)$application['name'])?></h2><p><code><?=e((string)$application['slug'])?></code> · Version <?=e((string)$application['version'])?> · <?=e((string)$application['environment'])?></p></div><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="app" value="<?=$appId?>"><input type="hidden" name="action" value="build"><button class="button">Build-ZIP erzeugen</button></form></div></section>
<div class="application-builder-grid">
<section class="card"><h3>Navigation</h3><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="app" value="<?=$appId?>"><input type="hidden" name="action" value="add_nav"><label>Bezeichnung<input name="label" required></label><label>Zieltyp<select name="target_type"><option value="dataform">DataForm</option><option value="dashboard">Dashboard</option><option value="url">URL</option></select></label><label>Ziel<input name="target_value" placeholder="Slug oder URL"></label><label>Symbol<input name="icon" placeholder="z. B. ▣"></label><label>Rolle<input name="role_name" placeholder="optional"></label><label>Position<input type="number" name="position" value="10"></label><div class="full"><button class="button">Navigation hinzufügen</button></div></form><?php if($navigation):?><div class="table-wrap"><table><thead><tr><th>Pos.</th><th>Eintrag</th><th>Ziel</th><th>Rolle</th><th></th></tr></thead><tbody><?php foreach($navigation as $n):?><tr><td><?=(int)$n['position']?></td><td><?=e((string)$n['label'])?></td><td><?=e((string)$n['target_type'])?>: <?=e((string)$n['target_value'])?></td><td><?=e((string)$n['role_name'])?></td><td><form method="post" onsubmit="return confirm('Eintrag löschen?')"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="app" value="<?=$appId?>"><input type="hidden" name="action" value="delete_nav"><input type="hidden" name="id" value="<?=(int)$n['id']?>"><button class="link-danger">Löschen</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="card"><h3>Dashboard</h3><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="app" value="<?=$appId?>"><input type="hidden" name="action" value="add_widget"><label>Titel<input name="title" required></label><label>Widgettyp<select name="widget_type"><option value="metric">Kennzahl</option><option value="list">Liste</option><option value="chart">Diagramm</option><option value="text">Text</option></select></label><label>Quelle<input name="source" placeholder="DataForm-Slug oder SQL-Alias"></label><label>Breite<select name="width"><option value="25">25 %</option><option value="50" selected>50 %</option><option value="100">100 %</option></select></label><label>Position<input type="number" name="position" value="10"></label><div class="full"><button class="button">Widget hinzufügen</button></div></form><?php if($widgets):?><div class="application-widget-list"><?php foreach($widgets as $w):?><article><strong><?=e((string)$w['title'])?></strong><span><?=e((string)$w['widget_type'])?> · <?=e((string)$w['width'])?> %</span><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="app" value="<?=$appId?>"><input type="hidden" name="action" value="delete_widget"><input type="hidden" name="id" value="<?=(int)$w['id']?>"><button class="link-danger">Löschen</button></form></article><?php endforeach;?></div><?php endif;?></section>
</div>
<section class="card"><h3>Build-Historie</h3><?php if(!$builds):?><div class="empty-state">Noch kein Build erzeugt.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Version</th><th>Umgebung</th><th>Datei</th><th>SHA-256</th></tr></thead><tbody><?php foreach($builds as $b):?><tr><td><?=e((string)$b['created_at'])?></td><td><?=e((string)$b['version'])?></td><td><?=e((string)$b['environment'])?></td><td><?=e((string)$b['file_name'])?></td><td><code><?=e(substr((string)$b['sha256'],0,16))?>…</code></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php endif;?></main><aside class="df-properties"><div class="df-pane-title">Kontexthilfe</div><h3>Ziel</h3><p>Eine eigenständige Oberfläche aus DataForms, Navigation und Dashboard zusammenstellen.</p><h3>Build</h3><p>Der Build enthält Manifest, Konfiguration, DataForm-Metadaten und eine lauffähige Startoberfläche.</p><h3>Umgebungen</h3><p>Entwicklung, Test und Produktion werden in jedem Build dokumentiert.</p><h3>Hinweis</h3><p>Der Application Builder erzeugt eine portable Anwendungsstruktur für die konfigurierte Zielumgebung.</p></aside></div></div>
<?php $content=ob_get_clean();render_page(['title'=>'Application Builder','active'=>'projects','base'=>'../../','content'=>$content,'app_nav'=>true,'body_class'=>'workspace-page','help'=>['title'=>'Application Builder','location'=>'DataForm → Application Builder','short'=>'Konfigurieren Sie Navigation, Dashboard und Zielumgebung Ihrer Anwendung.','goal'=>'Aus dem Projekt ein versioniertes Build-ZIP erzeugen.','next'=>'Build prüfen und bei Bedarf Abfragen im Visual Query Builder ergänzen.','steps'=>['Anwendung anlegen.','Navigation definieren.','Dashboard-Widgets ergänzen.','Build-ZIP erzeugen.'],'duration'=>'ca. 5–10 Minuten']]);
