<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';
require_once dirname(__DIR__,2).'/system/ui/layout.php';
require_once __DIR__.'/system/VisualQueryBuilder.php';
$user=enterprise_require_auth('../../');
$projectId=(int)($_GET['project']??$_POST['project']??($_SESSION['active_project_id']??0));
$dataformId=(int)($_GET['dataform']??$_POST['dataform']??0);$queryId=(int)($_GET['query']??$_POST['query']??0);
$error='';$success='';$project=null;$dataforms=[];$fields=[];$queries=[];$definition=['fields'=>[],'filters'=>[],'sort_field'=>'id','sort_direction'=>'ASC','limit'=>25];$result=null;
try{
 $admin=enterprise_pdo();enterprise_upgrade($admin);$s=$admin->prepare('SELECT * FROM projects WHERE id=? AND product_type=? LIMIT 1');$s->execute([$projectId,'dataform']);$project=$s->fetch();if(!$project)throw new RuntimeException('DataForm-Projekt wurde nicht gefunden.');$_SESSION['active_project_id']=$projectId;
 $env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');$pdo=enterprise_project_store_for_project($env,$project);VisualQueryBuilder::ensureSchema($pdo);
 $dataforms=$pdo->query('SELECT id,name,slug FROM dataforms ORDER BY name')->fetchAll();if($dataformId<1&&$dataforms)$dataformId=(int)$dataforms[0]['id'];
 if($dataformId>0){$q=$pdo->prepare('SELECT id,label,name,field_type FROM dataform_fields WHERE dataform_id=? ORDER BY position,id');$q->execute([$dataformId]);$fields=$q->fetchAll();$fieldMap=[];foreach($fields as $f)$fieldMap[(string)$f['name']]=$f;
  if($queryId>0){$q=$pdo->prepare('SELECT * FROM dataform_queries WHERE id=? AND dataform_id=?');$q->execute([$queryId,$dataformId]);if($saved=$q->fetch())$definition=json_decode((string)$saved['definition_json'],true)?:$definition;}
  if($_SERVER['REQUEST_METHOD']==='POST'){enterprise_check_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'preview');
   $raw=['fields'=>(array)($_POST['fields']??[]),'filters'=>[],'sort_field'=>(string)($_POST['sort_field']??'id'),'sort_direction'=>(string)($_POST['sort_direction']??'ASC'),'limit'=>(int)($_POST['limit']??25)];
   foreach((array)($_POST['filter_field']??[]) as $i=>$ff)$raw['filters'][]=['field'=>$ff,'operator'=>(string)(($_POST['filter_operator'][$i]??'equals')),'value'=>(string)(($_POST['filter_value'][$i]??''))];
   $definition=VisualQueryBuilder::normalizeDefinition($raw,$fieldMap);
   if($action==='save'){$name=trim((string)($_POST['query_name']??''));if($name==='')throw new RuntimeException('Bitte geben Sie einen Namen für die Abfrage ein.');$stmt=$pdo->prepare('INSERT INTO dataform_queries(dataform_id,name,description,definition_json,created_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE description=VALUES(description),definition_json=VALUES(definition_json),updated_at=CURRENT_TIMESTAMP');$stmt->execute([$dataformId,$name,trim((string)($_POST['description']??''))?:null,json_encode($definition,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$user['id']??null]);$success='Abfrage wurde gespeichert.';}
   elseif($action==='delete'){$pdo->prepare('DELETE FROM dataform_queries WHERE id=? AND dataform_id=?')->execute([(int)$_POST['query_id'],$dataformId]);$queryId=0;$success='Abfrage wurde gelöscht.';}
   else{$result=VisualQueryBuilder::execute($pdo,$dataformId,$definition);}
  }
  $q=$pdo->prepare('SELECT * FROM dataform_queries WHERE dataform_id=? ORDER BY name');$q->execute([$dataformId]);$queries=$q->fetchAll();
 }
}catch(Throwable $e){$error=$e->getMessage();}
$selected=array_flip($definition['fields']??[]);ob_start();
?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs([['label'=>'Enterprise','href'=>'../../app/dashboard.php'],['label'=>'Projekte','href'=>'../../app/projects/index.php'],['label'=>(string)($project['name']??'DataForm'),'href'=>$project?'../../app/projects/view.php?id='.(int)$project['id']:''],['label'=>'DataForm Workspace','href'=>'index.php?project='.$projectId],['label'=>'Visual Query Builder','href'=>'']]);?></div>
<div class="df-workspace"><header class="df-workspace-header"><div><span class="badge">DataForm Workspace</span><h1>Visual Query Builder</h1><p>Abfragen ohne handgeschriebenes SQL zusammenstellen, prüfen und wiederverwenden.</p></div><div class="actions"><a class="button secondary" href="index.php?project=<?=$projectId?>">Zum Workspace</a></div></header>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif;?>
<div class="df-workspace-grid"><aside class="df-explorer"><div class="df-pane-title">Abfragen</div><nav><a href="index.php?project=<?=$projectId?>">Workspace</a><a class="active" href="queries.php?project=<?=$projectId?>">Visual Query Builder</a><?php foreach($queries as $q):?><a class="<?=$queryId===(int)$q['id']?'active':''?>" href="queries.php?project=<?=$projectId?>&dataform=<?=$dataformId?>&query=<?=(int)$q['id']?>">↳ <?=e((string)$q['name'])?></a><?php endforeach;?></nav></aside>
<main class="df-main"><section class="card"><form method="get" class="form-grid"><input type="hidden" name="project" value="<?=$projectId?>"><label>DataForm<select name="dataform" onchange="this.form.submit()"><?php foreach($dataforms as $d):?><option value="<?=(int)$d['id']?>" <?=$dataformId===(int)$d['id']?'selected':''?>><?=e((string)$d['name'])?></option><?php endforeach;?></select></label></form></section>
<?php if($dataformId>0):?><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="dataform" value="<?=$dataformId?>"><section class="card"><h2>1. Ausgabefelder</h2><div class="query-field-grid"><?php foreach($fields as $f):?><label><input type="checkbox" name="fields[]" value="<?=e((string)$f['name'])?>" <?=isset($selected[(string)$f['name']])?'checked':''?>> <?=e((string)$f['label'])?> <small><code><?=e((string)$f['name'])?></code></small></label><?php endforeach;?></div></section>
<section class="card"><h2>2. Filter</h2><div id="query-filters"><?php $rows=$definition['filters']?:[['field'=>'','operator'=>'equals','value'=>'']];foreach($rows as $r):?><div class="query-filter-row"><select name="filter_field[]"><option value="">– kein Feld –</option><?php foreach($fields as $f):?><option value="<?=e((string)$f['name'])?>" <?=$r['field']===$f['name']?'selected':''?>><?=e((string)$f['label'])?></option><?php endforeach;?></select><select name="filter_operator[]"><?php foreach(['equals'=>'gleich','not_equals'=>'ungleich','contains'=>'enthält','starts_with'=>'beginnt mit','empty'=>'ist leer','not_empty'=>'ist nicht leer','greater'=>'größer','less'=>'kleiner'] as $k=>$v):?><option value="<?=$k?>" <?=$r['operator']===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select><input name="filter_value[]" value="<?=e((string)$r['value'])?>" placeholder="Vergleichswert"></div><?php endforeach;?></div><button type="button" class="button secondary" onclick="addQueryFilter()">+ Filterzeile</button></section>
<section class="card"><h2>3. Sortierung und Limit</h2><div class="form-grid"><label>Sortierfeld<select name="sort_field"><option value="id">ID</option><option value="updated_at" <?=$definition['sort_field']==='updated_at'?'selected':''?>>Geändert am</option><?php foreach($fields as $f):?><option value="<?=e((string)$f['name'])?>" <?=$definition['sort_field']===$f['name']?'selected':''?>><?=e((string)$f['label'])?></option><?php endforeach;?></select></label><label>Richtung<select name="sort_direction"><option value="ASC">Aufsteigend</option><option value="DESC" <?=$definition['sort_direction']==='DESC'?'selected':''?>>Absteigend</option></select></label><label>Maximale Treffer<input type="number" min="1" max="200" name="limit" value="<?=(int)$definition['limit']?>"></label></div></section>
<section class="card"><h2>4. Vorschau oder speichern</h2><div class="form-grid"><label>Abfragename<input name="query_name" placeholder="z. B. Aktive Kunden"></label><label class="full">Beschreibung<textarea name="description" rows="2"></textarea></label><div class="full actions"><button class="button" name="action" value="preview">Vorschau ausführen</button><button class="button secondary" name="action" value="save">Abfrage speichern</button><?php if($queryId):?><input type="hidden" name="query_id" value="<?=$queryId?>"><button class="link-danger" name="action" value="delete" onclick="return confirm('Abfrage löschen?')">Löschen</button><?php endif;?></div></div></section></form>
<?php if($result):?><section class="card"><h2>Ergebnisvorschau</h2><p><?=count($result['rows'])?> Treffer. Es wurden ausschließlich lesende SELECT-Abfragen ausgeführt.</p><details><summary>Generiertes SQL anzeigen</summary><pre><?=e($result['sql'])?></pre></details><?php if($result['rows']):?><div class="table-wrap"><table><thead><tr><?php foreach(array_keys($result['rows'][0]) as $c):?><th><?=e($c)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($result['rows'] as $row):?><tr><?php foreach($row as $v):?><td><?=e((string)$v)?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="empty-state">Keine Treffer.</div><?php endif;?></section><?php endif;?><?php endif;?></main>
<aside class="df-properties"><div class="df-pane-title">Kontexthilfe</div><h3>Ziel</h3><p>Felder, Filter und Sortierung visuell zu einer sicheren Leseabfrage kombinieren.</p><h3>Sicherheit</h3><p>Der Builder erzeugt ausschließlich SELECT-Abfragen. Tabellen- und Feldnamen stammen aus dem DataForm-Modell.</p><h3>Filter</h3><p>Mehrere Filter werden mit UND verknüpft.</p><h3>Nächster Schritt</h3><p>Gespeicherte Abfragen können später als Quelle für Dashboard, Reports und API verwendet werden.</p></aside></div></div>
<script>function addQueryFilter(){const box=document.getElementById('query-filters');const row=box.querySelector('.query-filter-row');if(row)box.appendChild(row.cloneNode(true));}</script>
<?php $content=ob_get_clean();render_page(['title'=>'Visual Query Builder','active'=>'projects','base'=>'../../','content'=>$content,'app_nav'=>true,'body_class'=>'workspace-page','help'=>['title'=>'Visual Query Builder','location'=>'DataForm → Visual Query Builder','short'=>'Erstellen Sie sichere Abfragen ohne SQL-Code.','goal'=>'Eine wiederverwendbare Datenabfrage konfigurieren und testen.','next'=>'Abfrage speichern und später in Reports oder Dashboards verwenden.','steps'=>['DataForm wählen.','Ausgabefelder markieren.','Filter und Sortierung einstellen.','Vorschau ausführen und speichern.'],'duration'=>'ca. 5 Minuten']]);
