<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';
require_once dirname(__DIR__,2).'/system/ui/layout.php';
require_once __DIR__.'/system/ReportDesigner.php';
$user=enterprise_require_auth('../../');
$projectId=(int)($_GET['project']??$_POST['project']??($_SESSION['active_project_id']??0));
$reportId=(int)($_GET['report']??$_POST['report']??0);$error='';$success='';$project=null;$reports=[];$report=null;$elements=[];$dataforms=[];$queries=[];$rows=[];
try{
 $admin=enterprise_pdo();enterprise_upgrade($admin);$s=$admin->prepare('SELECT * FROM projects WHERE id=? AND product_type=? LIMIT 1');$s->execute([$projectId,'dataform']);$project=$s->fetch();if(!$project)throw new RuntimeException('DataForm-Projekt wurde nicht gefunden.');$_SESSION['active_project_id']=$projectId;
 $env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');$pdo=enterprise_project_store_for_project($env,$project);ReportDesigner::ensureSchema($pdo);
 $dataforms=$pdo->query('SELECT id,name,slug FROM dataforms ORDER BY name')->fetchAll();
 $queries=$pdo->query('SELECT q.id,q.name,d.name AS dataform_name FROM dataform_queries q JOIN dataforms d ON d.id=q.dataform_id ORDER BY q.name')->fetchAll();
 if($_SERVER['REQUEST_METHOD']==='POST'){enterprise_check_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');
  if($action==='create_report'){$name=trim((string)$_POST['name']);if($name==='')throw new RuntimeException('Bitte geben Sie einen Berichtsnamen ein.');$sourceType=in_array($_POST['source_type']??'',['dataform','query'],true)?(string)$_POST['source_type']:'dataform';$sourceId=(int)($_POST['source_id']??0);if($sourceId<1)throw new RuntimeException('Bitte wählen Sie eine Datenquelle.');$stmt=$pdo->prepare('INSERT INTO reports(name,slug,description,source_type,source_id,page_format,orientation,created_by) VALUES(?,?,?,?,?,?,?,?)');$stmt->execute([$name,ReportDesigner::slug($name),trim((string)($_POST['description']??''))?:null,$sourceType,$sourceId,'A4',(($_POST['orientation']??'portrait')==='landscape'?'landscape':'portrait'),$user['id']??null]);$reportId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO report_pages(report_id,title,position) VALUES(?,?,1)')->execute([$reportId,'Seite 1']);$success='Bericht wurde angelegt.';}
  elseif($action==='add_element'){$reportId=(int)$_POST['report'];$type=(string)($_POST['element_type']??'text');$allowed=['title','text','table','chart','kpi','line','page_break'];if(!in_array($type,$allowed,true))throw new RuntimeException('Unbekannter Elementtyp.');$config=['text'=>(string)($_POST['text']??''),'fields'=>array_values(array_filter(array_map('trim',explode(',',(string)($_POST['fields']??''))))),'field'=>(string)($_POST['field']??'')];$pos=(int)$pdo->query('SELECT COALESCE(MAX(position),0)+1 FROM report_elements WHERE report_id='.(int)$reportId)->fetchColumn();$pdo->prepare('INSERT INTO report_elements(report_id,element_type,title,config_json,position) VALUES(?,?,?,?,?)')->execute([$reportId,$type,trim((string)($_POST['title']??''))?:null,json_encode($config,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$pos]);$success='Berichtselement wurde hinzugefügt.';}
  elseif($action==='delete_element'){$reportId=(int)$_POST['report'];$pdo->prepare('DELETE FROM report_elements WHERE id=? AND report_id=?')->execute([(int)$_POST['element_id'],$reportId]);$success='Berichtselement wurde gelöscht.';}
  elseif($action==='delete_report'){$reportId=(int)$_POST['report'];$pdo->beginTransaction();$pdo->prepare('DELETE FROM report_elements WHERE report_id=?')->execute([$reportId]);$pdo->prepare('DELETE FROM report_pages WHERE report_id=?')->execute([$reportId]);$pdo->prepare('DELETE FROM report_parameters WHERE report_id=?')->execute([$reportId]);$pdo->prepare('DELETE FROM reports WHERE id=?')->execute([$reportId]);$pdo->commit();$reportId=0;$success='Bericht wurde gelöscht.';}
 }
 $reports=$pdo->query('SELECT * FROM reports ORDER BY name')->fetchAll();
 if($reportId>0){$q=$pdo->prepare('SELECT * FROM reports WHERE id=?');$q->execute([$reportId]);$report=$q->fetch();if(!$report){$reportId=0;}else{$q=$pdo->prepare('SELECT * FROM report_elements WHERE report_id=? ORDER BY position,id');$q->execute([$reportId]);$elements=$q->fetchAll();$rows=ReportDesigner::sourceRows($pdo,$report);}}
 if($report && isset($_GET['export'])){$format=(string)$_GET['export'];$safe=ReportDesigner::slug((string)$report['name']).'-'.date('Ymd-His');
  if($format==='csv'){$fields=$rows?array_keys($rows[0]):[];header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$safe.'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,$fields,';');foreach($rows as $row)fputcsv($out,array_map(fn($f)=>(string)($row[$f]??''),$fields),';');exit;}
  if($format==='json'){header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$safe.'.json"');echo json_encode(['report'=>$report,'rows'=>$rows],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
  $html='<!doctype html><html lang="de"><meta charset="utf-8"><title>'.e((string)$report['name']).'</title><style>body{font:14px Arial;margin:32px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:6px;text-align:left}.report-kpi{display:inline-flex;flex-direction:column;padding:16px;border:1px solid #bbb;margin:8px}.report-kpi span{font-size:24px}.report-page-break{page-break-after:always}.report-chart-row{display:grid;grid-template-columns:180px 1fr 50px;gap:8px;align-items:center;margin:5px}.report-chart-row i{display:block;background:#777;height:16px}</style>'.ReportDesigner::renderHtml($report,$elements,$rows).'</html>';
  $ext=$format==='word'?'doc':'html';header('Content-Type: '.($format==='word'?'application/msword':'text/html').'; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$safe.'.'.$ext.'"');echo $html;exit;
 }
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
ob_start();
?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs([['label'=>'Enterprise','href'=>'../../app/dashboard.php'],['label'=>'Projekte','href'=>'../../app/projects/index.php'],['label'=>(string)($project['name']??'DataForm'),'href'=>$project?'../../app/projects/view.php?id='.(int)$project['id']:''],['label'=>'DataForm Workspace','href'=>'index.php?project='.$projectId],['label'=>'Report Designer','href'=>'']]);?></div>
<div class="df-workspace"><header class="df-workspace-header"><div><span class="badge">DataForm Workspace</span><h1>Report Designer</h1><p>Berichte aus DataForms oder gespeicherten Visual Queries gestalten, prüfen und exportieren.</p></div><div class="actions"><a class="button secondary" href="index.php?project=<?=$projectId?>">Zum Workspace</a></div></header>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif;?>
<div class="df-workspace-grid"><aside class="df-explorer"><div class="df-pane-title">Reports</div><nav><a href="index.php?project=<?=$projectId?>">Workspace</a><a class="<?=!$reportId?'active':''?>" href="reports.php?project=<?=$projectId?>">+ Neuer Bericht</a><?php foreach($reports as $r):?><a class="<?=$reportId===(int)$r['id']?'active':''?>" href="reports.php?project=<?=$projectId?>&report=<?=(int)$r['id']?>">▤ <?=e((string)$r['name'])?></a><?php endforeach;?></nav></aside>
<main class="df-main">
<?php if(!$report):?><section class="card"><h2>Neuen Bericht anlegen</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="action" value="create_report"><label>Berichtsname<input name="name" required placeholder="z. B. Kundenliste"></label><label>Datenquellentyp<select name="source_type" id="source-type"><option value="dataform">DataForm</option><option value="query">Visual Query</option></select></label><label>DataForm<select name="source_id" id="source-dataform"><?php foreach($dataforms as $d):?><option value="<?=(int)$d['id']?>"><?=e((string)$d['name'])?></option><?php endforeach;?></select></label><label>Visual Query<select id="source-query" disabled><?php foreach($queries as $q):?><option value="<?=(int)$q['id']?>"><?=e((string)$q['name'])?> · <?=e((string)$q['dataform_name'])?></option><?php endforeach;?></select></label><label>Ausrichtung<select name="orientation"><option value="portrait">Hochformat</option><option value="landscape">Querformat</option></select></label><label class="full">Beschreibung<textarea name="description" rows="3"></textarea></label><div class="full"><button class="button">Bericht anlegen</button></div></form></section>
<?php else:?>
<section class="card report-toolbar"><div><h2><?=e((string)$report['name'])?></h2><p><?=e((string)($report['description']??''))?></p></div><div class="actions"><a class="button secondary" <?= easyit_button_attributes('drucken') ?> target="_blank" href="reports.php?project=<?=$projectId?>&report=<?=$reportId?>&print=1">Druck-/PDF-Vorschau</a><a class="button secondary" <?= easyit_button_attributes('export_csv') ?> href="reports.php?project=<?=$projectId?>&report=<?=$reportId?>&export=csv">CSV</a><a class="button secondary" <?= easyit_button_attributes('export_word') ?> href="reports.php?project=<?=$projectId?>&report=<?=$reportId?>&export=word">Word</a><a class="button secondary" <?= easyit_button_attributes('export_html') ?> href="reports.php?project=<?=$projectId?>&report=<?=$reportId?>&export=html">HTML</a><a class="button secondary" <?= easyit_button_attributes('export_json') ?> href="reports.php?project=<?=$projectId?>&report=<?=$reportId?>&export=json">JSON</a></div></section>
<section class="card"><h2>Element hinzufügen</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="report" value="<?=$reportId?>"><input type="hidden" name="action" value="add_element"><label>Elementtyp<select name="element_type"><option value="title">Titel</option><option value="text">Text</option><option value="table">Tabelle</option><option value="chart">Diagramm</option><option value="kpi">Kennzahl/Summe</option><option value="line">Trennlinie</option><option value="page_break">Seitenumbruch</option></select></label><label>Titel<input name="title" placeholder="Überschrift des Elements"></label><label class="full">Text<textarea name="text" rows="2"></textarea></label><label>Felder (Komma-getrennt)<input name="fields" placeholder="name,email,status"></label><label>Einzelfeld für Diagramm/KPI<input name="field" placeholder="status oder betrag"></label><div class="full"><button class="button">Element hinzufügen</button></div></form></section>
<section class="card"><h2>Live-Vorschau</h2><?php if(!$elements):?><div class="empty-state">Noch keine Berichtselemente. Fügen Sie zuerst Titel, Tabelle oder Diagramm hinzu.</div><?php else:?><?=ReportDesigner::renderHtml($report,$elements,$rows)?><?php endif;?></section>
<section class="card"><h2>Elementstruktur</h2><?php foreach($elements as $el):?><article class="report-element-row"><div><strong><?=e((string)($el['title']?:$el['element_type']))?></strong><small><?=e((string)$el['element_type'])?> · Position <?=(int)$el['position']?></small></div><form method="post" onsubmit="return confirm('Element löschen?')"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="report" value="<?=$reportId?>"><input type="hidden" name="element_id" value="<?=(int)$el['id']?>"><button class="link-danger" name="action" value="delete_element">Löschen</button></form></article><?php endforeach;?></section>
<form method="post" onsubmit="return confirm('Bericht vollständig löschen?')"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="report" value="<?=$reportId?>"><button class="link-danger" name="action" value="delete_report">Bericht löschen</button></form>
<?php endif;?></main>
<aside class="df-properties"><div class="df-pane-title">Kontexthilfe</div><h3>Datenquelle</h3><p>Ein Bericht verwendet entweder ein DataForm oder eine gespeicherte Visual Query.</p><h3>Elemente</h3><p>Titel, Text, Tabellen, Diagramme, Kennzahlen und Seitenumbrüche werden in Reihenfolge gerendert.</p><h3>PDF</h3><p>Öffnen Sie die Druckvorschau und wählen Sie im Browser „Als PDF speichern“.</p><h3>Export</h3><p>CSV und JSON exportieren Daten; Word und HTML exportieren den gestalteten Bericht.</p></aside></div>
<footer class="df-statusbar"><span>Berichte: <strong><?=count($reports)?></strong></span><span>Elemente: <strong><?=count($elements)?></strong></span><span>Treffer: <strong><?=count($rows)?></strong></span><span>Produkt: <strong>DataForm 5</strong></span></footer></div>
<script>const st=document.getElementById('source-type');if(st){const df=document.getElementById('source-dataform'),q=document.getElementById('source-query');const sync=()=>{const isQ=st.value==='query';df.disabled=isQ;q.disabled=!isQ;if(isQ)q.name='source_id';else{df.name='source_id';q.removeAttribute('name')}};st.addEventListener('change',sync);sync();}</script>
<?php
$content=ob_get_clean();
if($report && isset($_GET['print'])){echo '<!doctype html><html lang="de"><meta charset="utf-8"><title>'.e((string)$report['name']).'</title><style>body{font:14px Arial;margin:20mm}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:6px}.report-page-break{page-break-after:always}.report-kpi{border:1px solid #bbb;padding:15px;display:inline-flex;flex-direction:column}.report-kpi span{font-size:24px}.report-chart-row{display:grid;grid-template-columns:160px 1fr 50px;gap:8px;align-items:center}.report-chart-row i{height:14px;background:#666}@media print{button{display:none}}</style><button onclick="print()">Drucken / als PDF speichern</button>'.ReportDesigner::renderHtml($report,$elements,$rows).'</html>';exit;}
render_page(['title'=>'Report Designer','active'=>'projects','base'=>'../../','content'=>$content,'app_nav'=>true,'user'=>$user,'body_class'=>'workspace-page','help'=>['title'=>'Report Designer','location'=>'Enterprise → Projekt → DataForm → Reports','short'=>'Berichte aus DataForms und gespeicherten Abfragen gestalten und exportieren.','goal'=>'Wiederverwendbare Berichte ohne manuelles PHP oder SQL erzeugen.','next'=>'Bei Bedarf kann derselbe Datenbestand anschließend über den REST API Designer veröffentlicht werden.','steps'=>['Datenquelle wählen.','Bericht anlegen.','Elemente hinzufügen.','Live-Vorschau prüfen.','Bericht exportieren.'],'tips'=>['Für PDF die Druckvorschau verwenden.','Tabellenfelder werden kommasepariert angegeben.','Visual Queries übernehmen die gespeicherten Filter- und Sortiereinstellungen.']]]);
