<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';require_once dirname(__DIR__,2).'/system/ui/layout.php';$user=enterprise_require_auth('../../');$projectId=(int)($_GET['project']??$_POST['project']??0);$dataformId=(int)($_GET['dataform']??$_POST['dataform']??0);$error='';$project=null;$dataform=null;$states=[];$transitions=[];
try{$a=enterprise_pdo();enterprise_upgrade($a);$q=$a->prepare('SELECT * FROM projects WHERE id=?');$q->execute([$projectId]);$project=$q->fetch();if(!$project)throw new RuntimeException('Projekt nicht gefunden.');$env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');$pdo=new PDO('mysql:host='.($env['PROJECT_DB_HOST']??'127.0.0.1').';port='.(int)($env['PROJECT_DB_PORT']??3306).';dbname='.$project['database_name'].';charset=utf8mb4',(string)($env['PROJECT_DB_USERNAME']??''),(string)($env['PROJECT_DB_PASSWORD']??''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$q=$pdo->prepare('SELECT * FROM dataforms WHERE id=?');$q->execute([$dataformId]);$dataform=$q->fetch();if(!$dataform)throw new RuntimeException('DataForm nicht gefunden.');if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='save_positions'){enterprise_check_csrf((string)($_POST['csrf']??''));$positions=json_decode((string)($_POST['positions']??'[]'),true);$u=$pdo->prepare('UPDATE workflow_states SET x_pos=?,y_pos=? WHERE id=? AND dataform_id=?');foreach((array)$positions as $p)$u->execute([(int)$p['x'],(int)$p['y'],(int)$p['id'],$dataformId]);header('Content-Type: application/json');echo json_encode(['ok'=>true]);exit;}$q=$pdo->prepare('SELECT * FROM workflow_states WHERE dataform_id=? ORDER BY position');$q->execute([$dataformId]);$states=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM workflow_transitions WHERE dataform_id=? AND is_enabled=1');$q->execute([$dataformId]);$transitions=$q->fetchAll();}catch(Throwable $e){$error=$e->getMessage();}
ob_start();?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs([['label'=>'Enterprise','href'=>'../../app/dashboard.php'],['label'=>'DataForm','href'=>'index.php?project='.$projectId],['label'=>'Workflow','href'=>'workflow.php?project='.$projectId.'&dataform='.$dataformId],['label'=>'Grafischer Designer','href'=>'']]);?></div>
<header class="df-workspace-header"><div><span class="badge">DataForm Workspace · Visual Designer</span><h1>Grafischer Workflow-Designer</h1><p>Ziehen Sie Status frei auf der Arbeitsfläche an ihre gewünschte Position.</p></div><div class="actions"><a class="button secondary" href="workflow.php?project=<?=$projectId?>&dataform=<?=$dataformId?>">Konfiguration</a><button id="save">Positionen speichern</button></div></header><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<div id="canvas" style="position:relative;min-height:620px;border:1px solid #cbd5e1;border-radius:12px;background-image:linear-gradient(#eef2f7 1px,transparent 1px),linear-gradient(90deg,#eef2f7 1px,transparent 1px);background-size:24px 24px;overflow:auto">
<svg id="lines" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none"></svg>
<?php foreach($states as $s):?><div class="wf-node" data-id="<?=$s['id']?>" style="position:absolute;left:<?=(int)$s['x_pos']?>px;top:<?=(int)$s['y_pos']?>px;width:170px;padding:16px;border:2px solid #64748b;border-radius:12px;background:white;cursor:move;box-shadow:0 8px 20px rgba(0,0,0,.08)"><strong><?=e(($s['icon']?:'○').' '.$s['name'])?></strong><div class="muted"><?= $s['is_start']?'Start ':''?><?= $s['is_end']?'Ende':''?></div></div><?php endforeach;?></div>
<script>
const transitions=<?=json_encode($transitions,JSON_UNESCAPED_UNICODE)?>;const nodes=[...document.querySelectorAll('.wf-node')],canvas=document.getElementById('canvas'),svg=document.getElementById('lines');let drag=null,dx=0,dy=0;
function draw(){svg.innerHTML='';for(const t of transitions){const a=document.querySelector(`[data-id="${t.from_state_id}"]`),b=document.querySelector(`[data-id="${t.to_state_id}"]`);if(!a||!b)continue;const x1=a.offsetLeft+a.offsetWidth/2,y1=a.offsetTop+a.offsetHeight/2,x2=b.offsetLeft+b.offsetWidth/2,y2=b.offsetTop+b.offsetHeight/2;svg.insertAdjacentHTML('beforeend',`<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#64748b" stroke-width="2" marker-end="url(#arrow)"/><text x="${(x1+x2)/2}" y="${(y1+y2)/2-6}" font-size="12">${t.name}</text>`)} }
nodes.forEach(n=>n.addEventListener('pointerdown',e=>{drag=n;dx=e.clientX-n.offsetLeft;dy=e.clientY-n.offsetTop;n.setPointerCapture(e.pointerId)}));document.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect();drag.style.left=Math.max(0,e.clientX-r.left-dx+canvas.scrollLeft)+'px';drag.style.top=Math.max(0,e.clientY-r.top-dy+canvas.scrollTop)+'px';draw()});document.addEventListener('pointerup',()=>drag=null);draw();
document.getElementById('save').onclick=async()=>{const fd=new FormData();fd.set('action','save_positions');fd.set('csrf','<?=e(enterprise_csrf())?>');fd.set('project','<?=$projectId?>');fd.set('dataform','<?=$dataformId?>');fd.set('positions',JSON.stringify(nodes.map(n=>({id:+n.dataset.id,x:n.offsetLeft,y:n.offsetTop}))));const r=await fetch(location.href,{method:'POST',body:fd});const j=await r.json();alert(j.ok?'Positionen gespeichert.':'Fehler beim Speichern.');};
</script><?php $content=ob_get_clean();render_page(['title'=>'Grafischer Workflow-Designer','content'=>$content,'base'=>'../../','active'=>'projects','app_nav'=>true,'user'=>$user,'body_class'=>'workspace-page']);
