<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/system/app/bootstrap.php';
require_once dirname(__DIR__,2).'/system/ui/layout.php';
require_once __DIR__.'/system/DataFormConfigNavigation.php';
$user=enterprise_require_auth('../../');
$projectId=(int)($_GET['project']??$_POST['project']??($_SESSION['active_project_id']??0));
$dataformId=(int)($_GET['dataform']??$_POST['dataform']??0);
$error='';$success='';$project=null;$dataform=null;$states=[];$transitions=[];$actions=[];$availableDataforms=[];
try{
 $admin=enterprise_pdo(); enterprise_upgrade($admin);
 $s=$admin->prepare('SELECT * FROM projects WHERE id=? AND product_type=?');$s->execute([$projectId,'dataform']);$project=$s->fetch(); if(!$project)throw new RuntimeException('Projekt nicht gefunden.');
 $env=enterprise_env(dirname(__DIR__,2).'/DataForm5-Core/.env');
 $pdo=enterprise_project_store_for_project($env,$project);
 $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_states(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,dataform_id BIGINT UNSIGNED NOT NULL,name VARCHAR(190) NOT NULL,slug VARCHAR(190) NOT NULL,color VARCHAR(30) NOT NULL DEFAULT 'neutral',icon VARCHAR(40) NULL,is_start TINYINT(1) NOT NULL DEFAULT 0,is_end TINYINT(1) NOT NULL DEFAULT 0,position INT NOT NULL DEFAULT 10,x_pos INT NOT NULL DEFAULT 40,y_pos INT NOT NULL DEFAULT 40,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_state(dataform_id,slug),INDEX idx_state_df(dataform_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_transitions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,dataform_id BIGINT UNSIGNED NOT NULL,name VARCHAR(190) NOT NULL,from_state_id BIGINT UNSIGNED NOT NULL,to_state_id BIGINT UNSIGNED NOT NULL,required_role VARCHAR(100) NULL,requires_confirmation TINYINT(1) NOT NULL DEFAULT 0,comment_mode VARCHAR(20) NOT NULL DEFAULT 'optional',is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_trans_df(dataform_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_actions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,transition_id BIGINT UNSIGNED NOT NULL,action_type VARCHAR(50) NOT NULL,action_order INT NOT NULL DEFAULT 10,configuration_json LONGTEXT NULL,is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_action_transition(transition_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,dataform_id BIGINT UNSIGNED NOT NULL,record_id BIGINT UNSIGNED NOT NULL,transition_id BIGINT UNSIGNED NULL,from_state_id BIGINT UNSIGNED NULL,to_state_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NULL,comment_text TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_wlog_record(dataform_id,record_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_permissions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,dataform_id BIGINT UNSIGNED NOT NULL,object_type VARCHAR(30) NOT NULL,object_id BIGINT UNSIGNED NOT NULL,role_slug VARCHAR(100) NOT NULL,can_read TINYINT(1) NOT NULL DEFAULT 1,can_write TINYINT(1) NOT NULL DEFAULT 0,can_execute TINYINT(1) NOT NULL DEFAULT 0,UNIQUE KEY uq_perm(dataform_id,object_type,object_id,role_slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $availableDataforms=$pdo->query('SELECT id,name,slug FROM dataforms ORDER BY name,id')->fetchAll();
 if($dataformId>0){
  $d=$pdo->prepare('SELECT * FROM dataforms WHERE id=?');$d->execute([$dataformId]);$dataform=$d->fetch();
  if(!$dataform)throw new RuntimeException('Das ausgewählte DataForm wurde nicht gefunden. Bitte wählen Sie ein vorhandenes DataForm.');
  if($_SERVER['REQUEST_METHOD']==='POST'){
   enterprise_check_csrf((string)($_POST['csrf']??''));$a=(string)($_POST['action']??'');
   if($a==='add_state'){
    $name=trim((string)($_POST['name']??''));$slug=strtolower(trim((string)($_POST['slug']??'')));$slug=preg_replace('/[^a-z0-9-]+/','-',$slug?:$name);$slug=trim((string)$slug,'-');if($name===''||$slug==='')throw new RuntimeException('Name ist erforderlich.');
    if(isset($_POST['is_start']))$pdo->prepare('UPDATE workflow_states SET is_start=0 WHERE dataform_id=?')->execute([$dataformId]);
    $pos=(int)$pdo->query('SELECT COALESCE(MAX(position),0)+10 FROM workflow_states WHERE dataform_id='.(int)$dataformId)->fetchColumn();
    $pdo->prepare('INSERT INTO workflow_states(dataform_id,name,slug,color,icon,is_start,is_end,position,x_pos,y_pos) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$dataformId,$name,$slug,(string)($_POST['color']??'neutral'),trim((string)($_POST['icon']??'')),isset($_POST['is_start'])?1:0,isset($_POST['is_end'])?1:0,$pos,40+($pos%4)*180,40+intdiv($pos,40)*130]);$success='Status angelegt.';
   }elseif($a==='add_transition'){
    $from=(int)($_POST['from_state_id']??0);$to=(int)($_POST['to_state_id']??0);$name=trim((string)($_POST['name']??''));if($name===''||$from<1||$to<1||$from===$to)throw new RuntimeException('Übergang unvollständig.');
    $pdo->prepare('INSERT INTO workflow_transitions(dataform_id,name,from_state_id,to_state_id,required_role,requires_confirmation,comment_mode) VALUES(?,?,?,?,?,?,?)')->execute([$dataformId,$name,$from,$to,trim((string)($_POST['required_role']??''))?:null,isset($_POST['requires_confirmation'])?1:0,(string)($_POST['comment_mode']??'optional')]);$success='Übergang angelegt.';
   }elseif($a==='add_action'){
    $tid=(int)($_POST['transition_id']??0);$type=(string)($_POST['action_type']??'log');if($tid<1)throw new RuntimeException('Übergang fehlt.');
    $cfg=['target'=>trim((string)($_POST['target']??'')),'template'=>trim((string)($_POST['template']??''))];$order=(int)$pdo->query('SELECT COALESCE(MAX(action_order),0)+10 FROM workflow_actions WHERE transition_id='.(int)$tid)->fetchColumn();
    $pdo->prepare('INSERT INTO workflow_actions(transition_id,action_type,action_order,configuration_json) VALUES(?,?,?,?)')->execute([$tid,$type,$order,json_encode($cfg,JSON_UNESCAPED_UNICODE)]);$success='Aktion angelegt.';
   }elseif($a==='delete_state'){$pdo->prepare('DELETE FROM workflow_states WHERE id=? AND dataform_id=?')->execute([(int)$_POST['id'],$dataformId]);$success='Status gelöscht.';}
   elseif($a==='toggle_transition'){$pdo->prepare('UPDATE workflow_transitions SET is_enabled=IF(is_enabled=1,0,1) WHERE id=? AND dataform_id=?')->execute([(int)$_POST['id'],$dataformId]);$success='Übergang geändert.';}
  }
  $q=$pdo->prepare('SELECT * FROM workflow_states WHERE dataform_id=? ORDER BY position,id');$q->execute([$dataformId]);$states=$q->fetchAll();
  $q=$pdo->prepare('SELECT t.*,a.name from_name,b.name to_name FROM workflow_transitions t JOIN workflow_states a ON a.id=t.from_state_id JOIN workflow_states b ON b.id=t.to_state_id WHERE t.dataform_id=? ORDER BY t.id');$q->execute([$dataformId]);$transitions=$q->fetchAll();
  if($transitions){$ids=implode(',',array_map(fn($x)=>(int)$x['id'],$transitions));$actions=$pdo->query("SELECT * FROM workflow_actions WHERE transition_id IN ($ids) ORDER BY transition_id,action_order")->fetchAll();}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$breadcrumbs=[
 ['label'=>'Enterprise','href'=>'../../app/dashboard.php'],
 ['label'=>'Projekte','href'=>'../../app/projects/index.php'],
 ['label'=>(string)($project['name']??'Projekt'),'href'=>'../../app/projects/view.php?id='.$projectId],
 ['label'=>'DataForms','href'=>'index.php?project='.$projectId.'&section=dataforms'],
];
if($dataform){$breadcrumbs[]=['label'=>(string)$dataform['name'],'href'=>'index.php?project='.$projectId.'&section=dataform&dataform='.$dataformId];}
$breadcrumbs[]=['label'=>'Workflow','href'=>''];
ob_start();?>
<div class="workspace-breadcrumbs"><?php render_breadcrumbs($breadcrumbs);?></div>
<div class="df-workspace">
<header class="df-workspace-header"><div><span class="badge">DataForm Workspace</span><h1>Workflow & Aktionen</h1><p><?= $dataform ? 'Status, Übergänge, Rollen und Folgeaktionen für dieses DataForm konfigurieren.' : 'Wählen Sie zuerst das DataForm, dessen Workflow Sie konfigurieren möchten.' ?></p></div><div class="actions"><?php if($dataform): ?><a class="button secondary" href="workflow-visual.php?project=<?=$projectId?>&amp;dataform=<?=$dataformId?>">Grafischer Designer</a><a class="button secondary" <?= easyit_button_attributes('zurueck') ?> href="index.php?project=<?=$projectId?>&amp;section=dataform&amp;dataform=<?=$dataformId?>">Zurück</a><?php else: ?><a class="button secondary" <?= easyit_button_attributes('zurueck') ?> href="index.php?project=<?=$projectId?>&amp;section=dataforms">DataForms</a><?php endif; ?></div></header>
<?php if($dataform): ?><?= dataform_config_map($projectId,$dataformId,'workflow') ?><?php endif; ?>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif;?>
<div class="df-workspace-grid">
<aside class="df-explorer"><div class="df-pane-title">Explorer</div><nav><?php if($dataform): ?><a href="index.php?project=<?=$projectId?>&amp;section=dataform&amp;dataform=<?=$dataformId?>">Datenmodell</a><a href="foundation.php?project=<?=$projectId?>&amp;dataform=<?=$dataformId?>">Layout & Verhalten</a><a class="active" href="workflow.php?project=<?=$projectId?>&amp;dataform=<?=$dataformId?>">Workflow</a><a href="records.php?project=<?=$projectId?>&amp;dataform=<?=$dataformId?>">Datensätze</a><?php else: ?><a href="index.php?project=<?=$projectId?>&amp;section=dataforms">DataForms</a><a class="active" href="workflow.php?project=<?=$projectId?>">Workflow</a><?php endif; ?></nav></aside>
<main class="df-main">
<?php if($dataform): ?><?= dataform_config_related($projectId,$dataformId,'workflow') ?><?php endif; ?>
<?php if(!$dataform): ?>
<section class="card"><h2>DataForm für Workflow auswählen</h2><p class="muted">Workflow-Status und Übergänge gehören immer genau zu einem DataForm.</p><?php if(!$availableDataforms): ?><div class="empty-state"><h3>Noch keine DataForms</h3><p>Legen Sie zuerst ein DataForm an.</p></div><?php else: ?><div class="df-form-list"><?php foreach($availableDataforms as $form): ?><article class="df-form-item"><div><h3><?=e((string)$form['name'])?></h3><?php if(!empty($form['slug'])):?><div class="df-form-meta"><code><?=e((string)$form['slug'])?></code></div><?php endif;?></div><a class="button" <?= easyit_button_attributes('auswaehlen') ?> href="workflow.php?project=<?=$projectId?>&amp;dataform=<?=(int)$form['id']?>">Workflow öffnen</a></article><?php endforeach;?></div><?php endif;?></section>
<?php else: ?>
<section class="card"><h2>Status anlegen</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="action" value="add_state"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="dataform" value="<?=$dataformId?>"><label>Name<input name="name" required></label><label>Interner Name<input name="slug"></label><label>Farbe<select name="color"><option>neutral</option><option>blue</option><option>green</option><option>orange</option><option>red</option></select></label><label>Symbol<input name="icon" placeholder="z. B. ✓"></label><label><input type="checkbox" name="is_start"> Startstatus</label><label><input type="checkbox" name="is_end"> Endstatus</label><div><button>Status anlegen</button></div></form></section>
<section class="card"><h2>Status</h2><?php if(!$states):?><p class="muted">Noch kein Workflow definiert.</p><?php else:?><div class="cards"><?php foreach($states as $st):?><article class="card"><h3><?=e($st['icon'].' '.$st['name'])?></h3><p><code><?=e($st['slug'])?></code></p><p><?= $st['is_start']?'Startstatus ':''?><?= $st['is_end']?'Endstatus':''?></p><form method="post"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="action" value="delete_state"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="dataform" value="<?=$dataformId?>"><input type="hidden" name="id" value="<?=(int)$st['id']?>"><button class="button secondary" onclick="return confirm('Status löschen?')">Löschen</button></form></article><?php endforeach;?></div><?php endif;?></section>
<section class="card"><h2>Übergang anlegen</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="action" value="add_transition"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="dataform" value="<?=$dataformId?>"><label>Name<input name="name" required placeholder="Einreichen"></label><label>Von<select name="from_state_id" required><option value="">–</option><?php foreach($states as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach;?></select></label><label>Nach<select name="to_state_id" required><option value="">–</option><?php foreach($states as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach;?></select></label><label>Erforderliche Rolle<input name="required_role" placeholder="editor"></label><label>Kommentar<select name="comment_mode"><option value="optional">optional</option><option value="required">Pflicht</option><option value="none">kein Kommentar</option></select></label><label><input type="checkbox" name="requires_confirmation"> Bestätigung verlangen</label><div><button>Übergang anlegen</button></div></form></section>
<section class="card"><h2>Übergänge & Aktionen</h2><?php foreach($transitions as $t):?><article class="card"><h3><?=e($t['from_name'].' → '.$t['to_name'].' · '.$t['name'])?></h3><p>Rolle: <?=e($t['required_role']?:'alle')?> · <?= $t['is_enabled']?'aktiv':'inaktiv'?></p><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(enterprise_csrf())?>"><input type="hidden" name="action" value="add_action"><input type="hidden" name="project" value="<?=$projectId?>"><input type="hidden" name="dataform" value="<?=$dataformId?>"><input type="hidden" name="transition_id" value="<?=$t['id']?>"><label>Aktion<select name="action_type"><option value="log">Logeintrag</option><option value="email">E-Mail</option><option value="status">Status setzen</option><option value="webhook">Webhook</option><option value="pdf">PDF erzeugen</option></select></label><label>Ziel<input name="target"></label><label>Vorlage<input name="template"></label><div><button>Aktion hinzufügen</button></div></form><?php foreach($actions as $a)if((int)$a['transition_id']===(int)$t['id']):?><p>• <?=e($a['action_type'])?> <code><?=e($a['configuration_json']??'')?></code></p><?php endif;?></article><?php endforeach;?></section>
<?php endif; ?>
</main>
<aside class="df-properties"><div class="df-pane-title">Kontexthilfe</div><h3>Ziel</h3><p><?= $dataform ? 'Definieren Sie den Lebenszyklus eines Datensatzes.' : 'Wählen Sie das DataForm, für das ein Workflow gepflegt werden soll.' ?></p><?php if($dataform): ?><h3>Reihenfolge</h3><p>Erst Status, dann Übergänge, danach Folgeaktionen.</p><h3>Sicherheit</h3><p>Übergänge können auf Rollen beschränkt und bestätigungspflichtig gemacht werden.</p><?php endif; ?></aside>
</div></div>
<?php $content=ob_get_clean();render_page(['title'=>'Workflow – easyIT Enterprise','content'=>$content,'base'=>'../../','active'=>'projects','app_nav'=>true,'user'=>$user,'body_class'=>'workspace-page']);
