<?php
declare(strict_types=1);

namespace EasyIT\Assistant\Module;

final class ReleaseCatalogService
{
    private string $dir;
    private string $catalogPath;
    public function __construct(private DataFormModuleLibraryStore $store,private DataFormModulePackageService $packages,private ReleaseTrustStore $trust,private string $root){$this->root=rtrim($root,'/\\');$this->dir=$this->root.'/storage/assistant/release-catalog';$this->catalogPath=$this->dir.'/catalog.json';}

    /** @return array<string,mixed> */
    public function catalogReleased(string $moduleId,string $visibility='system',?string $ownerProject=null):array
    {
        $meta=$this->store->getInScope($moduleId,$visibility,$ownerProject);if($meta===[])throw new \RuntimeException('Modul wurde für Release-Katalog nicht gefunden.');$gate=(array)($meta['releaseGate']??[]);$status=(string)($gate['status']??'LEGACY_RELEASED');if($status!=='RELEASED'||empty($gate['installable'])||!empty($gate['legacy']))throw new \RuntimeException('Nur ein modernes RELEASED-Modul kann signiert katalogisiert werden.');$path=$this->store->packagePath($moduleId,$visibility,$ownerProject);if(!is_file($path))throw new \RuntimeException('Modulpaket fehlt.');$inspection=$this->packages->inspect($path);if(empty($inspection['ok']))throw new \RuntimeException('Modulpaket ist ungültig.');
        $version=SemVersion::normalize((string)($meta['release']['version']??'1.0.0'));$packageSha=(string)hash_file('sha256',$path);$fingerprint=$this->packages->releaseFingerprint($path);$gateFingerprint=(string)($gate['releaseFingerprint']??'');if($gateFingerprint===''||!hash_equals($gateFingerprint,$fingerprint))throw new \RuntimeException('Release-Fingerprint des Gate stimmt nicht mit dem Paket überein.');$reportSha=(string)($gate['reportSha256']??'');if(!preg_match('/^[a-f0-9]{64}$/',$reportSha))throw new \RuntimeException('Gate-Berichtsprüfsumme fehlt.');$reportId=(string)($gate['reportId']??'');$scope=$visibility==='project'?'project-'.$ownerProject:'system';$reportPath=$this->root.'/storage/assistant/module-release-gates/'.$scope.'/'.$moduleId.'/'.$reportId.'.json';if($reportId===''||!is_file($reportPath)||!hash_equals($reportSha,(string)hash_file('sha256',$reportPath)))throw new \RuntimeException('Originaler Gate-Bericht fehlt oder seine SHA-256 stimmt nicht.');
        $locator=$visibility==='project'?'project::'.$ownerProject.'::'.$moduleId:'system::'.$moduleId;$payload=['schema'=>'easyit.assistant.release-catalog-payload.v1','moduleId'=>$moduleId,'version'=>$version,'locator'=>$locator,'visibility'=>$visibility,'ownerProject'=>$visibility==='project'?$ownerProject:null,'packageSha256'=>$packageSha,'releaseFingerprint'=>$fingerprint,'gateReportId'=>$gate['reportId']??null,'gateReportSha256'=>$reportSha,'gateCheckedAt'=>$gate['checkedAt']??null,'releasedAt'=>$gate['releasedAt']??null];$canonical=$this->canonical($payload);$signed=$this->trust->sign($canonical);$entry=['schema'=>'easyit.assistant.release-catalog-entry.v1','catalogId'=>$this->catalogId($locator,$version),'payload'=>$payload,'payloadSha256'=>hash('sha256',$canonical),'signature'=>$signed,'catalogedAt'=>gmdate('c'),'status'=>'TRUSTED'];$this->put($entry);return $entry;
    }

    /** @return array<string,mixed> */
    public function verifyLibraryRelease(string $moduleId,string $visibility='system',?string $ownerProject=null):array
    {
        $meta=$this->store->getInScope($moduleId,$visibility,$ownerProject);if($meta===[])return $this->result(false,['Modul wurde nicht gefunden.']);$gate=(array)($meta['releaseGate']??[]);if(!empty($gate['legacy'])||($gate['status']??'')==='LEGACY_RELEASED')return $this->result(true,[],['Legacy-Release: Phase-25-Signaturprüfung aus Kompatibilitätsgründen übersprungen.'],['legacy'=>true]);if(($gate['status']??'')!=='RELEASED'||empty($gate['installable']))return $this->result(false,['Release ist nicht RELEASED/installierbar.']);$version=SemVersion::normalize((string)($meta['release']['version']??'1.0.0'));$locator=$visibility==='project'?'project::'.$ownerProject.'::'.$moduleId:'system::'.$moduleId;$id=$this->catalogId($locator,$version);$entry=$this->get($id);if($entry===[])return $this->result(false,['Freigegebenes Release besitzt keinen signierten Release-Katalogeintrag.'],[],['catalogId'=>$id]);$path=$this->store->packagePath($moduleId,$visibility,$ownerProject);if(!is_file($path))return $this->result(false,['Modulpaket fehlt.']);$payload=(array)($entry['payload']??[]);$errors=[];try{$inspection=$this->packages->inspect($path);if(empty($inspection['ok']))return $this->result(false,array_merge(['Modulpaket ist strukturell ungültig.'],(array)($inspection['errors']??[])));$packageSha=(string)hash_file('sha256',$path);$fingerprint=$this->packages->releaseFingerprint($path);}catch(\Throwable $e){return $this->result(false,['Modulpaket kann nicht sicher geprüft werden: '.$e->getMessage()]);}
        foreach([['moduleId',$moduleId],['version',$version],['locator',$locator],['packageSha256',$packageSha],['releaseFingerprint',$fingerprint],['gateReportSha256',(string)($gate['reportSha256']??'')]] as [$k,$expected])if((string)($payload[$k]??'')!==$expected)$errors[]='Katalogbindung stimmt für '.$k.' nicht überein.';$canonical=$this->canonical($payload);if(!hash_equals((string)($entry['payloadSha256']??''),hash('sha256',$canonical)))$errors[]='Katalog-Payload-SHA-256 stimmt nicht.';$sig=(array)($entry['signature']??[]);if(($sig['algorithm']??'')!=='Ed25519')$errors[]='Nicht unterstützter Signaturalgorithmus.';else{ $signatureVerification=$this->trust->verifyForPurpose($canonical,(string)($sig['signature']??''),(string)($sig['keyId']??''),'install'); if(empty($signatureVerification['ok']))$errors[]='Ed25519-Signatur oder Trust-Policy ist ungültig: '.implode(' ',(array)($signatureVerification['errors']??[])); } return $this->result($errors===[],$errors,[],['catalogId'=>$id,'keyId'=>$sig['keyId']??null,'packageSha256'=>$packageSha,'releaseFingerprint'=>$fingerprint,'entry'=>$entry,'signatureVerification'=>$signatureVerification??null]);
    }

    /** @return list<array<string,mixed>> */public function entries():array{$c=$this->catalog();$out=array_values((array)($c['entries']??[]));usort($out,static fn($a,$b)=>strcmp((string)($b['catalogedAt']??''),(string)($a['catalogedAt']??'')));return $out;}
    /** @return array<string,mixed> */public function get(string $catalogId):array{$c=$this->catalog();return is_array($c['entries'][$catalogId]??null)?(array)$c['entries'][$catalogId]:[];}
    /** @return array<string,mixed> */public function trustStatus():array{$s=$this->trust->status();$s['chainVerification']=$this->trust->verifyChain();return $s;}
    /** @return array<string,mixed> */public function rotateKey(string $confirmation):array{return $this->trust->rotate($confirmation);}
    /** @return array<string,mixed> */public function ensureKey():array{return $this->trust->ensureActiveKey();}
    /** @return array<string,mixed> */public function suspendKey(string $keyId,string $reason,string $confirmation):array{return $this->trust->suspend($keyId,$reason,$confirmation);}
    /** @return array<string,mixed> */public function reactivateKey(string $keyId,string $reason,string $confirmation):array{return $this->trust->reactivate($keyId,$reason,$confirmation);}
    /** @return array<string,mixed> */public function revokeKey(string $keyId,string $reason,string $confirmation):array{return $this->trust->revoke($keyId,$reason,$confirmation);}
    /** @return array<string,mixed> */public function setKeyTrustLevel(string $keyId,string $level,string $reason,string $confirmation):array{return $this->trust->setTrustLevel($keyId,$level,$reason,$confirmation);}
    /** @return array<string,mixed> */public function setKeyValidity(string $keyId,?string $validUntil,string $reason,string $confirmation):array{return $this->trust->setValidity($keyId,$validUntil,$reason,$confirmation);}
    /** @return list<array<string,mixed>> */public function trustAudit(int $limit=200):array{return $this->trust->auditEvents($limit);}
    /** @return array<string,mixed> */public function verifyTrustAudit():array{return $this->trust->verifyAuditChain();}
    /** @return array<string,mixed> */public function evaluateKey(string $keyId,string $purpose='install'):array{return $this->trust->evaluateKey($keyId,$purpose);}

    private function put(array $entry):void{$this->ensure();$c=$this->catalog();$c['schema']='easyit.assistant.release-catalog.v1';$c['entries'][(string)$entry['catalogId']]=$entry;$c['updatedAt']=gmdate('c');$j=json_encode($c,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($j===false)throw new \RuntimeException('Release-Katalog kann nicht serialisiert werden.');$tmp=$this->catalogPath.'.tmp.'.bin2hex(random_bytes(4));if(@file_put_contents($tmp,$j."\n",LOCK_EX)===false||!@rename($tmp,$this->catalogPath)){@unlink($tmp);throw new \RuntimeException('Release-Katalog kann nicht atomar gespeichert werden.');}}
    /** @return array<string,mixed> */private function catalog():array{if(!is_file($this->catalogPath))return ['schema'=>'easyit.assistant.release-catalog.v1','entries'=>[]];$d=json_decode((string)@file_get_contents($this->catalogPath),true);return is_array($d)?array_merge(['schema'=>'easyit.assistant.release-catalog.v1','entries'=>[]],$d):['schema'=>'easyit.assistant.release-catalog.v1','entries'=>[]];}
    private function ensure():void{if(!is_dir($this->dir)&&!@mkdir($this->dir,0770,true)&&!is_dir($this->dir))throw new \RuntimeException('Release-Katalogverzeichnis kann nicht erstellt werden.');}
    private function catalogId(string $locator,string $version):string{return substr(preg_replace('/[^A-Za-z0-9._-]+/','-',trim($locator.'@'.$version))??'',0,180).'-'.substr(hash('sha256',$locator.'@'.$version),0,12);}
    /** @param mixed $v */private function normalize($v){if(!is_array($v))return $v;if(array_is_list($v))return array_map(fn($x)=>$this->normalize($x),$v);ksort($v,SORT_STRING);foreach($v as $k=>$x)$v[$k]=$this->normalize($x);return $v;}
    private function canonical(array $payload):string{$j=json_encode($this->normalize($payload),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($j===false)throw new \RuntimeException('Katalogpayload kann nicht serialisiert werden.');return $j;}
    /** @return array<string,mixed> */private function result(bool $ok,array $errors=[],array $warnings=[],array $extra=[]):array{return array_merge(['schema'=>'easyit.assistant.release-trust-verification.v1','ok'=>$ok,'verdict'=>$ok?($warnings===[]?'PASS':'PASS_WITH_WARNINGS'):'FAIL','errors'=>array_values(array_unique($errors)),'warnings'=>array_values(array_unique($warnings)),'checkedAt'=>gmdate('c')],$extra);}
}
