<?php
declare(strict_types=1);
putenv('SESSION_DRIVER=array');
$kernel = require __DIR__ . '/../bootstrap/app.php';
use DataForm5\Core\Container\ServiceContainer;
use DataForm5\Security\Auth\AuthManager;
use DataForm5\Security\Auth\InMemoryUserProvider;
use DataForm5\Security\Auth\PasswordHasher;
use DataForm5\Security\Auth\User;
use DataForm5\Security\Authorization\Gate;
use DataForm5\Security\Contracts\UserProviderInterface;
use DataForm5\Security\Csrf\CsrfTokenManager;
$c=$kernel->container();
$hasher=$c->get(PasswordHasher::class);
$provider=$c->get(UserProviderInterface::class);
assert($provider instanceof InMemoryUserProvider);
$provider->add(new User(1,'admin@example.test',$hasher->hash('Secret!123'),['admin'],['projects.reset']));
$auth=$c->get(AuthManager::class);
assert($auth->attempt('admin@example.test','Secret!123'));
assert($auth->check());
$gate=$c->get(Gate::class);
assert($gate->hasRole('admin'));
assert($gate->allows('projects.reset'));
$csrf=$c->get(CsrfTokenManager::class);
$token=$csrf->token();
assert(strlen($token)===64 && $csrf->validate($token));
$auth->logout();
assert($auth->guest());
echo "PASS: Security Layer\n";
