<?php
declare(strict_types=1);
$root=null;foreach(array_slice($argv,1)as$a)if(str_starts_with($a,'--root='))$root=substr($a,7);if(!$root){fwrite(STDERR,"Usage: php apply_to_enterpriseManager.php --root=D:\\xampp\\htdocs\\enterpriseManager\n");exit(2);} $root=rtrim($root,'/\\');if(!is_file($root.'/setup.php')&&!is_dir($root.'/products/dataform')){fwrite(STDERR,"enterpriseManager root not recognized: $root\n");exit(3);} $src=dirname(__DIR__);$copy=function(string $from,string $to)use($src,$root){$s=$src.'/'.$from;$d=$root.'/'.$to;if(is_dir($s)){if(!is_dir($d))mkdir($d,0775,true);$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($s,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::SELF_FIRST);foreach($it as$f){$rel=substr($f->getPathname(),strlen($s)+1);$dst=$d.'/'.$rel;if($f->isDir()){if(!is_dir($dst))mkdir($dst,0775,true);}else{if(!is_dir(dirname($dst)))mkdir(dirname($dst),0775,true);copy($f->getPathname(),$dst);}}}else{if(!is_dir(dirname($d)))mkdir(dirname($d),0775,true);copy($s,$d);}};$copy('system/licensing','system/licensing');if(!is_file($root.'/config/licensing.php'))$copy('config/licensing.example.php','config/licensing.php');if(!is_dir($root.'/tools'))mkdir($root.'/tools',0775,true);$copy('tools/activate_license.php','tools/activate_license.php');$copy('tools/publish_dataform_definition.php','tools/publish_dataform_definition.php');
$records=$root.'/products/dataform/records.php';if(!is_file($records)){fwrite(STDERR,"records.php missing; client files copied but runtime patch not applied.\n");exit(4);} $code=file_get_contents($records);if(str_contains($code,'EnterpriseRuntimeBridge::boot(')){echo "Runtime bridge already installed.\n";exit(0);} $backup=$records.'.pre-license-'.date('Ymd-His').'.bak';copy($records,$backup);
$require="require_once dirname(__DIR__, 2) . '/system/licensing/Autoload.php';\n"; $anchor="require_once __DIR__ . '/system/DataFormRecordSet.php';";if(str_contains($code,$anchor))$code=str_replace($anchor,$anchor."\n".$require,$code);else{$pos=strpos($code,"$user = enterprise_require_auth('../../');");if($pos===false)throw new RuntimeException('PATCH_ANCHOR_REQUIRE_NOT_FOUND');$code=substr($code,0,$pos).$require.substr($code,$pos);} 
// Insert boot after projectId/dataformId assignments. Locate the first dataformId assignment semicolon after projectId.
if(!preg_match('/\\$dataformId\\s*=.*?;/s',$code,$m,PREG_OFFSET_CAPTURE))throw new RuntimeException('PATCH_ANCHOR_DATAFORMID_NOT_FOUND');$end=$m[0][1]+strlen($m[0][0]);$inject="\n// DataForm5 servergebundene Lizenz-/Runtime-Freigabe\n\$easyitDataFormManifest = \\EasyIT\\Enterprise\\Licensing\\EnterpriseRuntimeBridge::boot(dirname(__DIR__, 2), \$projectId, \$dataformId);\nif (\$_SERVER['REQUEST_METHOD'] === 'POST') { \\EasyIT\\Enterprise\\Licensing\\EnterpriseRuntimeBridge::authorizePost(\$_POST); }\n";$code=substr($code,0,$end).$inject.substr($code,$end);
// After known successful STAND-4 markers, mark remote action completed. These insertions do not alter local RecordSet semantics.
$successAnchors=["\$recordSetLastAction=\$saveOperation==='create'?'after_insert':'after_update';","\$recordSetLastAction='after_delete';"];foreach($successAnchors as$a){if(str_contains($code,$a))$code=str_replace($a,$a."\n            \\EasyIT\\Enterprise\\Licensing\\EnterpriseRuntimeBridge::finalize(true, 'OK');",$code);} 
file_put_contents($records,$code);echo "DATAFORM_LICENSE_PATCH_APPLIED\nbackup=$backup\n";
