<?php
declare(strict_types=1);

namespace EasyIT\Assistant\Assistants;

use EasyIT\Assistant\AssistantContext;
use EasyIT\Assistant\AssistantInterface;
use EasyIT\Assistant\AssistantResult;
use EasyIT\Assistant\AssistantStep;
use EasyIT\Assistant\State\AssistantStateStore;
use EasyIT\Assistant\Module\DataFormModuleLibraryService;
use EasyIT\Assistant\Module\ModuleInstallationRegistry;

final class DataFormModuleLibraryAssistant implements AssistantInterface
{
    public function __construct(private AssistantStateStore $stateStore,private DataFormModuleLibraryService $library,private ?ModuleInstallationRegistry $installations=null){}
    public function getId():string{return 'dataform.module-library';}
    public function getTitle():string{return 'DataForm-Modulbibliothek';}
    public function getDescription():string{return 'Speichert, versioniert, importiert/exportiert, kopiert und installiert komplette Mehrfach-DataForm-Module system- oder projektweit.';}

    public function getSteps(AssistantContext $c):array
    {
        $scope=$c->getProjectId()?:'global';$s=$this->stateStore->get($this->getId(),$scope);$op=(string)($s['operation']??'browse');
        $opts=[''=>'Bitte Modul auswählen'];foreach($this->library->list($c->getProjectId()) as $m){$v=(string)($m['visibility']??'system');$p=(string)($m['ownerProject']??'');$loc=$v==='project'?'project::'.$p.'::'.$m['id']:'system::'.$m['id'];$opts[$loc]=(string)$m['name'].' ['.($v==='project'?'Projekt '.$p:'System').']';}
        $steps=[new AssistantStep('operation','1. Bibliotheksvorgang','Aktion auswählen.',['fields'=>[['name'=>'operation','label'=>'Vorgang','type'=>'select','required'=>true,'options'=>[
            'browse'=>'Bibliothek anzeigen','create'=>'Modul aus Projekt erstellen','history'=>'Versionsverlauf anzeigen','rename'=>'Modul umbenennen/beschreiben','copy'=>'Modul kopieren','visibility'=>'Freigabe ändern','import'=>'Modulpaket importieren','export'=>'Modulpaket exportieren','install'=>'Modul in Projekt einspielen','delete'=>'Modul kontrolliert löschen']]]])];
        if($op==='browse'){return array_merge($steps,[new AssistantStep('result','2. Bibliothek','Sichtbare Module anzeigen.')]);}
        if($op==='create'){$steps[]=new AssistantStep('configure','2. Modul erzeugen','Projekt und Start-DataForms festlegen.',['fields'=>[
            ['name'=>'source_project','label'=>'Quellprojekt','type'=>'text','required'=>true],['name'=>'new_name','label'=>'Modulname','type'=>'text','required'=>true],['name'=>'new_description','label'=>'Beschreibung','type'=>'textarea','rows'=>4],['name'=>'root_dataforms','label'=>'Start-DataForms','type'=>'textarea','rows'=>7,'required'=>true],['name'=>'include_transitive','label'=>'Kind-DataForms transitiv aufnehmen','type'=>'checkbox'],['name'=>'include_datasource','label'=>'Datenquellen-Snapshot aufnehmen','type'=>'checkbox'],['name'=>'target_visibility','label'=>'Freigabe','type'=>'select','options'=>['project'=>'Projektbezogen','system'=>'Systemweit']],['name'=>'target_project','label'=>'Bibliotheksprojekt','type'=>'text']]]);$steps[]=new AssistantStep('result','3. Ergebnis','Modul speichern.');return $steps;}
        if($op==='import'){$steps[]=new AssistantStep('configure','2. Import','Phase-18-Modulpaket hochladen.',['fields'=>[
            ['name'=>'module_file','label'=>'*.dataform-module.zip','type'=>'file','accept'=>'.zip,application/zip','required'=>true],['name'=>'new_name','label'=>'Bibliotheksname (optional)','type'=>'text'],['name'=>'new_description','label'=>'Beschreibung','type'=>'textarea','rows'=>4],['name'=>'target_visibility','label'=>'Freigabe','type'=>'select','options'=>['project'=>'Projektbezogen','system'=>'Systemweit']],['name'=>'target_project','label'=>'Bibliotheksprojekt','type'=>'text']]]);$steps[]=new AssistantStep('result','3. Ergebnis','Import anzeigen.');return $steps;}
        $steps[]=new AssistantStep('select','2. Modul auswählen','Modul wählen.',['fields'=>[['name'=>'module_locator','label'=>'Modul','type'=>'select','required'=>true,'options'=>$opts]]]);
        if($op==='rename')$steps[]=new AssistantStep('configure','3. Metadaten','Name und Beschreibung ändern.',['fields'=>[['name'=>'new_name','label'=>'Neuer Modulname','type'=>'text','required'=>true],['name'=>'new_description','label'=>'Beschreibung','type'=>'textarea','rows'=>4]]]);
        elseif($op==='copy')$steps[]=new AssistantStep('configure','3. Kopie','Zielbereich festlegen.',['fields'=>[['name'=>'new_name','label'=>'Name der Kopie','type'=>'text','required'=>true],['name'=>'target_visibility','label'=>'Freigabe','type'=>'select','options'=>['project'=>'Projektbezogen','system'=>'Systemweit']],['name'=>'target_project','label'=>'Zielprojekt','type'=>'text']]]);
        elseif($op==='visibility')$steps[]=new AssistantStep('configure','3. Freigabe','Zielbereich festlegen.',['fields'=>[['name'=>'target_visibility','label'=>'Neue Freigabe','type'=>'select','options'=>['project'=>'Projektbezogen','system'=>'Systemweit']],['name'=>'target_project','label'=>'Zielprojekt','type'=>'text']]]);
        elseif($op==='delete')$steps[]=new AssistantStep('configure','3. Löschen bestätigen','Modul wird in den Papierkorb verschoben.',['fields'=>[['name'=>'delete_confirm_name','label'=>'Modulname exakt eingeben','type'=>'text','required'=>true],['name'=>'confirm_delete','label'=>'Modul jetzt löschen','type'=>'checkbox']]]);
        elseif($op==='install'){$steps[]=new AssistantStep('configure','3. Ziel und Mapping','Zielprojekt und Referenzen festlegen.',['fields'=>[
            ['name'=>'target_project','label'=>'Zielprojekt','type'=>'text','required'=>true],['name'=>'dataform_mapping','label'=>'DataForm-Mapping quelle|ziel','type'=>'textarea','rows'=>8],['name'=>'reference_mapping','label'=>'Weitere Referenzen alt|neu','type'=>'textarea','rows'=>8],['name'=>'allow_overwrite','label'=>'Vorhandene Konfiguration historisiert überschreiben','type'=>'checkbox'],['name'=>'apply_datasource','label'=>'Datenquellen-Snapshot übernehmen','type'=>'checkbox']]]);$steps[]=new AssistantStep('preview','4. Vorschau','Phase-18-Diagnose vor Installation.');$steps[]=new AssistantStep('apply','5. Übernehmen','Installation bestätigen.',['fields'=>[['name'=>'confirm_apply','label'=>'Geprüftes Modul jetzt einspielen','type'=>'checkbox']]]);$steps[]=new AssistantStep('result','6. Ergebnis','Installation und Diagnosen anzeigen.');return $steps;}
        $steps[]=new AssistantStep('result',(count($steps)+1).'. Ergebnis','Vorgang ausführen.');return $steps;
    }

    public function run(AssistantContext $c,?string $stepId=null):AssistantResult
    {
        $scope=$c->getProjectId()?:'global';if($this->bool($c,'reset'))$this->stateStore->clear($this->getId(),$scope);$s=$this->stateStore->get($this->getId(),$scope);$stepId=$stepId?:'operation';$method=strtoupper((string)$c->meta('requestMethod','GET'));$errors=[];$data=[];
        if($method==='POST'&&!$this->bool($c,'reset')){try{$s=$this->merge($s,$c,$stepId);if(($s['operation']??'')==='import'&&$stepId==='configure'&&empty($s['imported'])){[$v,$p]=$this->target($s,$c);$files=(array)$c->meta('files',[]);$s['imported']=$this->library->importUpload((array)($files['module_file']??[]),(string)($s['newName']??''),(string)($s['newDescription']??''),$v,$p);}$this->stateStore->put($this->getId(),$s,$scope);}catch(\Throwable $e){$errors[]=$e->getMessage();}}
        $steps=$this->getSteps($c);$ids=array_map(static fn(AssistantStep $x)=>$x->getId(),$steps);if(!in_array($stepId,$ids,true))$stepId=$ids[0];$op=(string)($s['operation']??'browse');$data+=['phase'=>19,'operation'=>$op,'moduleLibrary'=>$this->library->list($c->getProjectId()),'formValues'=>$this->formValues($s,$stepId,$c),'nextStep'=>$this->next($ids,$stepId),'previousStep'=>$this->prev($ids,$stepId)];
        try{
            if($stepId==='result'&&$op==='browse')$data['configurationReady']=true;
            elseif($op==='create'&&$stepId==='result'){if(!is_array($s['created']??null)){$roots=$this->dataForms((string)($s['rootDataForms']??''));[$v,$p]=$this->target($s,$c);$s['created']=$this->library->createFromProject((string)($s['sourceProject']??''),(string)($s['newName']??''),(string)($s['newDescription']??''),$roots,!empty($s['includeTransitive']),!empty($s['includeDatasource']),$v,$p);$this->stateStore->put($this->getId(),$s,$scope);}$data['moduleLibraryResult']=['action'=>'create','module'=>$s['created']];$data['configurationReady']=true;}
            elseif($op==='import'&&$stepId==='result'){if(!is_array($s['imported']??null))throw new \RuntimeException('Import wurde noch nicht ausgeführt.');$data['moduleLibraryResult']=['action'=>'import','module'=>$s['imported']];$data['configurationReady']=true;}
            elseif(!in_array($op,['browse','create','import'],true)&&in_array($stepId,['select','configure','preview','apply','result'],true)){
                if(trim((string)($s['moduleLocator']??''))==='')throw new \RuntimeException('Modul fehlt.');[$v,$p,$id]=$this->locator((string)$s['moduleLocator']);$selected=$this->library->getScoped($id,$v,$p);if($selected===[])throw new \RuntimeException('Modul wurde nicht gefunden.');$data['selectedModule']=$selected;
                if($op==='install'){
                    $release=is_array($selected['release']??null)?$selected['release']:['version'=>'1.0.0','dependencies'=>[]];$gate=is_array($selected['releaseGate']??null)?$selected['releaseGate']:['status'=>'LEGACY_RELEASED','installable'=>true,'legacy'=>true];if(empty($gate['installable']))throw new \RuntimeException('Dieses Release ist nicht installierbar. Release-Gate-Status: '.(string)($gate['status']??'DRAFT').'. Bitte zuerst das Migrations-Gate / die Release-Freigabe ausführen.');if((array)($release['dependencies']??[])!==[])throw new \RuntimeException('Dieses Modul besitzt deklarierte Modulabhängigkeiten. Bitte "Modulabhängigkeiten und Installation" verwenden.');
                    if(empty($s['installToken'])){$st=$this->library->stage($id,$v,$p);$s['installToken']=$st['token'];$this->stateStore->put($this->getId(),$s,$scope);}
                    if(in_array($stepId,['preview','apply','result'],true)){$df=$this->mapping((string)($s['dataFormMapping']??''));$ref=$this->mapping((string)($s['referenceMapping']??''));$preview=$this->library->previewInstall((string)$s['installToken'],(string)($s['targetProject']??''),$df,$ref,!empty($s['allowOverwrite']),!empty($s['applyDatasource']));$data['moduleInstallPreview']=$preview;if($stepId==='apply'&&!empty($s['confirmApply'])){$s['applyResult']=$this->library->applyInstall((string)$s['installToken'],(string)$s['targetProject'],$df,$ref,!empty($s['allowOverwrite']),!empty($s['applyDatasource']));if(!empty($s['applyResult']['applied'])&&$this->installations!==null){$mapped=[];foreach((array)($selected['module']['dataForms']??[]) as $source)$mapped[]=(string)($df[$source]??$source);$this->installations->register((string)$s['targetProject'],['id'=>$id,'name'=>(string)($selected['name']??$id),'version'=>(string)($release['version']??'1.0.0'),'sourceLocator'=>$v==='project'?'project::'.$p.'::'.$id:'system::'.$id,'packageSha256'=>(string)($selected['package']['sha256']??''),'dataForms'=>$mapped,'dependencies'=>[],'dependencyValidation'=>'not-required']);}$this->stateStore->put($this->getId(),$s,$scope);}$data['moduleInstallResult']=$s['applyResult']??null;if($stepId==='result'&&!is_array($s['applyResult']??null))throw new \RuntimeException('Modul wurde noch nicht eingespielt.');}
                }elseif($stepId==='result'){
                    if($op==='history')$data['moduleHistory']=$this->library->history($id,$v,$p);
                    elseif($op==='export'){$q=['id'=>$id,'visibility'=>$v];if($p)$q['project_id']=$p;$data['moduleLibraryExportUrl']='module-library-download.php?'.http_build_query($q);}
                    elseif($op==='rename')$data['moduleLibraryResult']=['action'=>'rename','module'=>$this->library->rename($id,(string)($s['newName']??''),(string)($s['newDescription']??''),$v,$p)];
                    elseif($op==='copy'){[$tv,$tp]=$this->target($s,$c);$data['moduleLibraryResult']=['action'=>'copy','module'=>$this->library->copy($id,(string)($s['newName']??''),$v,$p,$tv,$tp)];}
                    elseif($op==='visibility'){[$tv,$tp]=$this->target($s,$c);$data['moduleLibraryResult']=['action'=>'visibility','module'=>$this->library->changeVisibility($id,$v,$p,$tv,$tp)];}
                    elseif($op==='delete'){if(empty($s['confirmDelete']))throw new \RuntimeException('Löschen wurde nicht ausdrücklich bestätigt.');$data['moduleLibraryResult']=['action'=>'delete']+$this->library->softDelete($id,$v,$p,(string)($s['deleteConfirmName']??''));}
                    $data['configurationReady']=true;
                }
            }
        }catch(\Throwable $e){$errors[]=$e->getMessage();}
        $idx=array_search($stepId,$ids,true);$stateful=[];foreach($steps as $i=>$x)$stateful[]=$x->withState($i<$idx?AssistantStep::STATE_COMPLETE:($i===$idx?AssistantStep::STATE_CURRENT:AssistantStep::STATE_PENDING));
        if($errors!==[])return AssistantResult::failure($this->getId(),array_values(array_unique($errors)),$stepId,$stateful,$data);return AssistantResult::success($this->getId(),$stepId,$stateful,$data);
    }

    private function merge(array $s,AssistantContext $c,string $step):array
    {
        if($step==='operation')return ['operation'=>(string)$c->input('operation','browse')];if($step==='select'){$s['moduleLocator']=trim((string)$c->input('module_locator',''));unset($s['installToken'],$s['applyResult']);}
        if($step==='configure'){$s['sourceProject']=trim((string)$c->input('source_project',$s['sourceProject']??($c->getProjectId()??'')));$s['newName']=trim((string)$c->input('new_name',$s['newName']??''));$s['newDescription']=trim((string)$c->input('new_description',$s['newDescription']??''));$s['rootDataForms']=(string)$c->input('root_dataforms',$s['rootDataForms']??($c->getDataFormId()??''));$s['includeTransitive']=$this->bool($c,'include_transitive');$s['includeDatasource']=$this->bool($c,'include_datasource');$s['targetVisibility']=(string)$c->input('target_visibility',$s['targetVisibility']??'project');$s['targetProject']=trim((string)$c->input('target_project',$s['targetProject']??($c->getProjectId()??'')));$s['deleteConfirmName']=trim((string)$c->input('delete_confirm_name',''));$s['confirmDelete']=$this->bool($c,'confirm_delete');$s['dataFormMapping']=(string)$c->input('dataform_mapping',$s['dataFormMapping']??'');$s['referenceMapping']=(string)$c->input('reference_mapping',$s['referenceMapping']??'');$s['allowOverwrite']=$this->bool($c,'allow_overwrite');$s['applyDatasource']=$this->bool($c,'apply_datasource');}
        if($step==='apply')$s['confirmApply']=$this->bool($c,'confirm_apply');return $s;
    }
    private function formValues(array $s,string $step,AssistantContext $c):array{return match($step){'operation'=>['operation'=>$s['operation']??'browse'],'select'=>['module_locator'=>$s['moduleLocator']??''],'configure'=>['source_project'=>$s['sourceProject']??($c->getProjectId()??''),'new_name'=>$s['newName']??'','new_description'=>$s['newDescription']??'','root_dataforms'=>$s['rootDataForms']??($c->getDataFormId()??''),'include_transitive'=>array_key_exists('includeTransitive',$s)?!empty($s['includeTransitive']):true,'include_datasource'=>array_key_exists('includeDatasource',$s)?!empty($s['includeDatasource']):true,'target_visibility'=>$s['targetVisibility']??'project','target_project'=>$s['targetProject']??($c->getProjectId()??''),'delete_confirm_name'=>$s['deleteConfirmName']??'','confirm_delete'=>!empty($s['confirmDelete']),'dataform_mapping'=>$s['dataFormMapping']??'','reference_mapping'=>$s['referenceMapping']??'','allow_overwrite'=>!empty($s['allowOverwrite']),'apply_datasource'=>!empty($s['applyDatasource'])],'apply'=>['confirm_apply'=>!empty($s['confirmApply'])],default=>[]};}
    /** @return array{0:string,1:?string} */private function target(array $s,AssistantContext $c):array{$v=(string)($s['targetVisibility']??'project');if(!in_array($v,['system','project'],true))throw new \InvalidArgumentException('Ungültige Zielfreigabe.');$p=$v==='project'?trim((string)($s['targetProject']??($c->getProjectId()??''))):null;if($v==='project'&&$p==='')throw new \InvalidArgumentException('Zielprojekt fehlt.');return[$v,$p];}
    /** @return array{0:string,1:?string,2:string} */private function locator(string $l):array{$p=explode('::',$l);if(($p[0]??'')==='system'&&isset($p[1]))return['system',null,$p[1]];if(($p[0]??'')==='project'&&isset($p[1],$p[2]))return['project',$p[1],$p[2]];throw new \InvalidArgumentException('Ungültige Modulauswahl.');}
    private function bool(AssistantContext $c,string $k):bool{return in_array($c->input($k,false),[true,1,'1','true','yes','on'],true);}private function next(array $ids,string $cur):?string{$i=array_search($cur,$ids,true);return $i!==false&&isset($ids[$i+1])?$ids[$i+1]:null;}private function prev(array $ids,string $cur):?string{$i=array_search($cur,$ids,true);return $i!==false&&$i>0?$ids[$i-1]:null;}
    /** @return list<string> */private function dataForms(string $t):array{return array_values(array_filter(array_map('trim',preg_split('/[\r\n,;]+/',$t)?:[]),static fn($v)=>$v!==''));}
    /** @return array<string,string> */private function mapping(string $t):array{$m=[];foreach(preg_split('/\R/',$t)?:[] as $line){$line=trim($line);if($line==='')continue;$p=array_map('trim',explode('|',$line,2));if(($p[0]??'')!==''&&isset($p[1])&&$p[1]!=='')$m[$p[0]]=$p[1];}return $m;}
}
