<?php
declare(strict_types=1);

use EasyIT\Assistant\AssistantManager;
use EasyIT\Assistant\AssistantRegistry;
use EasyIT\Assistant\Assistants\CoreStatusAssistant;
use EasyIT\Assistant\Assistants\DataFormAssistant;
use EasyIT\Assistant\Assistants\RelationAssistant;
use EasyIT\Assistant\Assistants\EventAssistant;
use EasyIT\Assistant\DataForm\DataFormDraftValidator;
use EasyIT\Assistant\DataForm\DataFormConfigCompiler;
use EasyIT\Assistant\Relation\RelationDraftValidator;
use EasyIT\Assistant\Relation\RelationConfigCompiler;
use EasyIT\Assistant\Event\EventDraftValidator;
use EasyIT\Assistant\Event\EventConfigCompiler;
use EasyIT\Assistant\Action\DataFormActionRegistry;
use EasyIT\Assistant\Action\ActionDraftValidator;
use EasyIT\Assistant\Action\ActionConfigCompiler;
use EasyIT\Assistant\Assistants\ActionAssistant;
use EasyIT\Assistant\Assistants\DataSourceAssistant;
use EasyIT\Assistant\DataSource\DataSourceRegistry;
use EasyIT\Assistant\DataSource\DataSourceDraftValidator;
use EasyIT\Assistant\DataSource\DataSourceConfigCompiler;
use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;
use EasyIT\Assistant\State\AssistantStateStore;
use EasyIT\Assistant\Field\FieldTypeRegistry;
use EasyIT\Assistant\Field\FieldDraftValidator;
use EasyIT\Assistant\Field\FieldConfigCompiler;
use EasyIT\Assistant\Assistants\FieldAssistant;
use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;
use EasyIT\Assistant\Assistants\DiagnosticAssistant;
use EasyIT\Assistant\Assistants\ProjectAssistant;
use EasyIT\Assistant\Project\ProjectDraftValidator;
use EasyIT\Assistant\Project\ProjectConfigCompiler;
use EasyIT\Assistant\Project\ProjectProvisioner;
use EasyIT\Assistant\Assistants\ProjectRecoveryAssistant;
use EasyIT\Assistant\Recovery\ProjectArchiveService;
use EasyIT\Assistant\Assistants\WorkflowAssistant;
use EasyIT\Assistant\Workflow\WorkflowProgressService;
use EasyIT\Assistant\Workflow\WorkflowPersistenceService;
use EasyIT\Assistant\Template\DataFormTemplateStore;
use EasyIT\Assistant\Template\DataFormTemplateMapper;
use EasyIT\Assistant\Template\DataFormTemplateService;
use EasyIT\Assistant\Template\DataFormTemplateLibraryService;
use EasyIT\Assistant\Assistants\DataFormTemplateAssistant;
use EasyIT\Assistant\Assistants\DataFormTemplateLibraryAssistant;
use EasyIT\Assistant\Transport\DataFormPackageService;
use EasyIT\Assistant\Assistants\DataFormPackageAssistant;
use EasyIT\Assistant\Module\DataFormModulePackageService;
use EasyIT\Assistant\Module\DataFormModuleLibraryStore;
use EasyIT\Assistant\Module\DataFormModuleLibraryService;
use EasyIT\Assistant\Assistants\DataFormModulePackageAssistant;
use EasyIT\Assistant\Assistants\DataFormModuleLibraryAssistant;
use EasyIT\Assistant\Module\ModuleInstallationRegistry;
use EasyIT\Assistant\Module\ModuleDependencyService;
use EasyIT\Assistant\Module\ModuleUpdateService;
use EasyIT\Assistant\Module\ModuleMigrationService;
use EasyIT\Assistant\Module\ModuleMigrationAuditService;
use EasyIT\Assistant\Module\ModuleReleaseGateService;
use EasyIT\Assistant\Module\ReleaseTrustStore;
use EasyIT\Assistant\Module\ReleaseCatalogService;
use EasyIT\Assistant\Module\TrustRecoveryService;
use EasyIT\Assistant\Module\TrustFederationService;
use EasyIT\Assistant\Module\TrustFailoverService;
use EasyIT\Assistant\Module\TrustMembershipService;
use EasyIT\Assistant\Assistants\ModuleDependencyAssistant;
use EasyIT\Assistant\Assistants\ModuleUpdateAssistant;
use EasyIT\Assistant\Assistants\ModuleMigrationAssistant;
use EasyIT\Assistant\Assistants\ModuleMigrationHistoryAssistant;
use EasyIT\Assistant\Assistants\ModuleReleaseGateAssistant;
use EasyIT\Assistant\Assistants\ReleaseCatalogAssistant;
use EasyIT\Assistant\Assistants\TrustPolicyAssistant;
use EasyIT\Assistant\Assistants\TrustRecoveryAssistant;
use EasyIT\Assistant\Assistants\TrustFederationAssistant;
use EasyIT\Assistant\Assistants\TrustFailoverAssistant;
use EasyIT\Assistant\Assistants\TrustMembershipAssistant;

if (session_status() === PHP_SESSION_NONE && PHP_SAPI !== 'cli') {
    session_start();
}

require_once __DIR__ . '/AssistantInterface.php';
require_once __DIR__ . '/AssistantContext.php';
require_once __DIR__ . '/AssistantStep.php';
require_once __DIR__ . '/AssistantResult.php';
require_once __DIR__ . '/AssistantRegistry.php';
require_once __DIR__ . '/AssistantManager.php';
require_once __DIR__ . '/AssistantContextFactory.php';
require_once __DIR__ . '/integration/AssistantUrlBuilder.php';
require_once __DIR__ . '/integration/AssistantSurfaceResolver.php';
require_once __DIR__ . '/integration/AssistantCatalog.php';
require_once __DIR__ . '/integration/AssistantUiActionRegistry.php';
require_once __DIR__ . '/integration/AssistantPageNavigationRenderer.php';
require_once __DIR__ . '/integration/AssistantIntegrationRegistry.php';
require_once __DIR__ . '/integration/AssistantLauncherRenderer.php';
require_once __DIR__ . '/state/AssistantStateSanitizer.php';
require_once __DIR__ . '/state/AssistantHistoryStore.php';
require_once __DIR__ . '/state/AssistantScopeResolver.php';
require_once __DIR__ . '/state/AssistantHistoryActionRegistry.php';
require_once __DIR__ . '/state/AssistantStateStore.php';
require_once __DIR__ . '/dataform/DataFormDraft.php';
require_once __DIR__ . '/dataform/DataFormDraftValidator.php';
require_once __DIR__ . '/dataform/DataFormConfigCompiler.php';
require_once __DIR__ . '/relation/RelationDraft.php';
require_once __DIR__ . '/relation/RelationDraftValidator.php';
require_once __DIR__ . '/relation/RelationConfigCompiler.php';
require_once __DIR__ . '/relation/BoundValueResolver.php';
require_once __DIR__ . '/event/EventDraft.php';
require_once __DIR__ . '/event/EventDraftValidator.php';
require_once __DIR__ . '/event/EventConfigCompiler.php';
require_once __DIR__ . '/event/DataFormActionContextBuilder.php';
require_once __DIR__ . '/action/ActionDefinition.php';
require_once __DIR__ . '/action/DataFormActionRegistry.php';
require_once __DIR__ . '/action/ActionDraft.php';
require_once __DIR__ . '/action/ActionDraftValidator.php';
require_once __DIR__ . '/action/ActionConfigCompiler.php';
require_once __DIR__ . '/datasource/ConnectionTestResult.php';
require_once __DIR__ . '/datasource/DataSourceAdapterInterface.php';
require_once __DIR__ . '/datasource/DataFormDatabaseInterface.php';
require_once __DIR__ . '/datasource/CoreDatabaseBridge.php';
require_once __DIR__ . '/datasource/DataSourceRegistry.php';
require_once __DIR__ . '/datasource/DataSourceDraft.php';
require_once __DIR__ . '/datasource/DataSourceDraftValidator.php';
require_once __DIR__ . '/datasource/DataSourceConfigCompiler.php';
require_once __DIR__ . '/datasource/adapters/AbstractPdoAdapter.php';
require_once __DIR__ . '/datasource/adapters/MySqlDataSourceAdapter.php';
require_once __DIR__ . '/datasource/adapters/SQLiteDataSourceAdapter.php';
require_once __DIR__ . '/datasource/adapters/CsvDataSourceAdapter.php';
require_once __DIR__ . '/datasource/adapters/OracleDataSourceAdapter.php';
require_once __DIR__ . '/field/FieldTypeRegistry.php';
require_once __DIR__ . '/field/FieldDraft.php';
require_once __DIR__ . '/field/FieldDraftValidator.php';
require_once __DIR__ . '/field/FieldConfigCompiler.php';
require_once __DIR__ . '/field/DerivedEnumValueCodec.php';
require_once __DIR__ . '/field/LookupResolver.php';
require_once __DIR__ . '/diagnostic/DiagnosticCheck.php';
require_once __DIR__ . '/diagnostic/DiagnosticReport.php';
require_once __DIR__ . '/diagnostic/DataFormDiagnosticService.php';
require_once __DIR__ . '/project/ProjectDraft.php';
require_once __DIR__ . '/project/ProjectDraftValidator.php';
require_once __DIR__ . '/project/ProjectConfigCompiler.php';
require_once __DIR__ . '/project/ProjectProvisioningResult.php';
require_once __DIR__ . '/project/ProjectProvisioner.php';
require_once __DIR__ . '/recovery/ArchiveOperationResult.php';
require_once __DIR__ . '/recovery/RecoveryCheck.php';
require_once __DIR__ . '/recovery/RecoveryReport.php';
require_once __DIR__ . '/recovery/ProjectRecoveryDiagnosticService.php';
require_once __DIR__ . '/recovery/ProjectArchiveService.php';
require_once __DIR__ . '/workflow/WorkflowDefinition.php';
require_once __DIR__ . '/workflow/WorkflowProgressService.php';
require_once __DIR__ . '/workflow/WorkflowPersistenceService.php';
require_once __DIR__ . '/template/DataFormTemplateStore.php';
require_once __DIR__ . '/template/DataFormTemplateMapper.php';
require_once __DIR__ . '/template/DataFormTemplateService.php';
require_once __DIR__ . '/template/DataFormTemplateLibraryService.php';
require_once __DIR__ . '/transport/DataFormPackageService.php';
require_once __DIR__ . '/module/DataFormModulePackageService.php';
require_once __DIR__ . '/module/DataFormModuleLibraryStore.php';
require_once __DIR__ . '/module/SemVersion.php';
require_once __DIR__ . '/module/DataFormModuleLibraryService.php';
require_once __DIR__ . '/module/ModuleInstallationRegistry.php';
require_once __DIR__ . '/module/ModuleDependencyService.php';
require_once __DIR__ . '/module/ModuleUpdateService.php';
require_once __DIR__ . '/module/ModuleMigrationService.php';
require_once __DIR__ . '/module/ModuleMigrationAuditService.php';
require_once __DIR__ . '/module/TrustFailoverLeaseGuard.php';
require_once __DIR__ . '/module/ReleaseTrustStore.php';
require_once __DIR__ . '/module/ReleaseCatalogService.php';
require_once __DIR__ . '/module/TrustRecoveryService.php';
require_once __DIR__ . '/module/TrustFederationService.php';
require_once __DIR__ . '/module/TrustFailoverService.php';
require_once __DIR__ . '/module/TrustMembershipService.php';
require_once __DIR__ . '/module/ModuleReleaseGateService.php';
require_once __DIR__ . '/assistants/CoreStatusAssistant.php';
require_once __DIR__ . '/assistants/DataFormAssistant.php';
require_once __DIR__ . '/assistants/RelationAssistant.php';
require_once __DIR__ . '/assistants/EventAssistant.php';
require_once __DIR__ . '/assistants/ActionAssistant.php';
require_once __DIR__ . '/assistants/DataSourceAssistant.php';
require_once __DIR__ . '/assistants/FieldAssistant.php';
require_once __DIR__ . '/assistants/DiagnosticAssistant.php';
require_once __DIR__ . '/assistants/ProjectAssistant.php';
require_once __DIR__ . '/assistants/ProjectRecoveryAssistant.php';
require_once __DIR__ . '/assistants/WorkflowAssistant.php';
require_once __DIR__ . '/assistants/DataFormTemplateAssistant.php';
require_once __DIR__ . '/assistants/DataFormTemplateLibraryAssistant.php';
require_once __DIR__ . '/assistants/DataFormPackageAssistant.php';
require_once __DIR__ . '/assistants/DataFormModulePackageAssistant.php';
require_once __DIR__ . '/assistants/DataFormModuleLibraryAssistant.php';
require_once __DIR__ . '/assistants/ModuleDependencyAssistant.php';
require_once __DIR__ . '/assistants/ModuleUpdateAssistant.php';
require_once __DIR__ . '/assistants/ModuleMigrationAssistant.php';
require_once __DIR__ . '/assistants/ModuleMigrationHistoryAssistant.php';
require_once __DIR__ . '/assistants/ModuleReleaseGateAssistant.php';
require_once __DIR__ . '/assistants/ReleaseCatalogAssistant.php';
require_once __DIR__ . '/assistants/TrustPolicyAssistant.php';
require_once __DIR__ . '/assistants/TrustRecoveryAssistant.php';
require_once __DIR__ . '/assistants/TrustFederationAssistant.php';
require_once __DIR__ . '/assistants/TrustFailoverAssistant.php';
require_once __DIR__ . '/assistants/TrustMembershipAssistant.php';

$projectRoot = dirname(__DIR__, 2);
$stateStore = static fn (): AssistantStateStore => new AssistantStateStore('easyit_assistant', $projectRoot);

$assistantRegistry = new AssistantRegistry();
$assistantRegistry->register(new CoreStatusAssistant());
$assistantRegistry->register(new ProjectAssistant($stateStore(), new ProjectDraftValidator(), new ProjectConfigCompiler(), new ProjectProvisioner($projectRoot)));
$assistantRegistry->register(new ProjectRecoveryAssistant($stateStore(), new ProjectArchiveService($projectRoot)));
$dataSourceRegistry = new DataSourceRegistry([
    new MySqlDataSourceAdapter(),
    new SQLiteDataSourceAdapter($projectRoot),
    new CsvDataSourceAdapter($projectRoot),
    new OracleDataSourceAdapter(),
]);
$assistantRegistry->register(new DataSourceAssistant($stateStore(), $dataSourceRegistry, new DataSourceDraftValidator($dataSourceRegistry), new DataSourceConfigCompiler()));
$assistantRegistry->register(new DataFormAssistant($stateStore(), new DataFormDraftValidator(), new DataFormConfigCompiler()));
$fieldTypeRegistry = new FieldTypeRegistry();
$assistantRegistry->register(new FieldAssistant($stateStore(), $fieldTypeRegistry, new FieldDraftValidator($fieldTypeRegistry), new FieldConfigCompiler($fieldTypeRegistry)));
$assistantRegistry->register(new RelationAssistant($stateStore(), new RelationDraftValidator(), new RelationConfigCompiler()));
$assistantRegistry->register(new EventAssistant($stateStore(), new EventDraftValidator(), new EventConfigCompiler()));
$dataFormActionRegistry = new DataFormActionRegistry();
$assistantRegistry->register(new ActionAssistant($stateStore(), $dataFormActionRegistry, new ActionDraftValidator($dataFormActionRegistry), new ActionConfigCompiler($dataFormActionRegistry)));
$templateStoreState = $stateStore();
$templateStore = new DataFormTemplateStore($projectRoot);
$templateService = new DataFormTemplateService($templateStoreState, $templateStore, new DataFormTemplateMapper(), $fieldTypeRegistry, $dataFormActionRegistry, $projectRoot);
$assistantRegistry->register(new DataFormTemplateAssistant($templateStoreState, $templateService));
$templateLibraryStore = $stateStore();
$templateLibraryService = new DataFormTemplateLibraryService($templateStore, $projectRoot);
$assistantRegistry->register(new DataFormTemplateLibraryAssistant($templateLibraryStore, $templateLibraryService));
$transportStore = $stateStore();
$transportDiagnostics = new DataFormDiagnosticService($transportStore, $dataSourceRegistry, $dataFormActionRegistry, $fieldTypeRegistry);
$transportService = new DataFormPackageService($transportStore, $dataSourceRegistry, $fieldTypeRegistry, $dataFormActionRegistry, $transportDiagnostics, $projectRoot);
$assistantRegistry->register(new DataFormPackageAssistant($transportStore, $transportService));
$moduleStore = $stateStore();
$moduleDiagnostics = new DataFormDiagnosticService($moduleStore, $dataSourceRegistry, $dataFormActionRegistry, $fieldTypeRegistry);
$moduleService = new DataFormModulePackageService($moduleStore, $dataSourceRegistry, $fieldTypeRegistry, $dataFormActionRegistry, $moduleDiagnostics, $projectRoot);
$assistantRegistry->register(new DataFormModulePackageAssistant($moduleStore, $moduleService));
$moduleLibraryState = $stateStore();
$moduleLibraryStore = new DataFormModuleLibraryStore($projectRoot);
$releaseTrustStore = new ReleaseTrustStore($projectRoot);
$releaseCatalogService = new ReleaseCatalogService($moduleLibraryStore, $moduleService, $releaseTrustStore, $projectRoot);
$moduleLibraryService = new DataFormModuleLibraryService($moduleLibraryStore, $moduleService, $projectRoot, $releaseCatalogService);
$moduleInstallations = new ModuleInstallationRegistry($projectRoot);
$assistantRegistry->register(new DataFormModuleLibraryAssistant($moduleLibraryState, $moduleLibraryService, $moduleInstallations));
$moduleDependencyState = $stateStore();
$moduleDependencyService = new ModuleDependencyService($moduleLibraryStore, $moduleLibraryService, $moduleInstallations, $projectRoot);
$assistantRegistry->register(new ModuleDependencyAssistant($moduleDependencyState, $moduleLibraryService, $moduleDependencyService));
$moduleUpdateState = $stateStore();
$moduleUpdateService = new ModuleUpdateService($moduleLibraryStore, $moduleLibraryService, $moduleInstallations, $moduleDependencyService, new ProjectArchiveService($projectRoot), $projectRoot);
$assistantRegistry->register(new ModuleUpdateAssistant($moduleUpdateState, $moduleUpdateService));
$moduleMigrationState = $stateStore();
$moduleMigrationArchive = new ProjectArchiveService($projectRoot);
$moduleMigrationAudit = new ModuleMigrationAuditService($moduleMigrationState, $moduleInstallations, $moduleMigrationArchive, $projectRoot);
$moduleMigrationService = new ModuleMigrationService($moduleMigrationState, $moduleLibraryStore, $moduleInstallations, $moduleUpdateService, $moduleMigrationArchive, $projectRoot, $moduleMigrationAudit);
$assistantRegistry->register(new ModuleMigrationAssistant($moduleMigrationState, $moduleMigrationService));
$moduleMigrationHistoryState = $stateStore();
$assistantRegistry->register(new ModuleMigrationHistoryAssistant($moduleMigrationHistoryState, new ModuleMigrationAuditService($moduleMigrationHistoryState, $moduleInstallations, new ProjectArchiveService($projectRoot), $projectRoot)));
$moduleReleaseGateState = $stateStore();
$moduleReleaseGateAudit = new ModuleMigrationAuditService($moduleReleaseGateState, $moduleInstallations, new ProjectArchiveService($projectRoot), $projectRoot);
$moduleReleaseGateService = new ModuleReleaseGateService($moduleReleaseGateState, $moduleLibraryStore, $moduleLibraryService, $moduleService, $moduleInstallations, $moduleDependencyService, $moduleUpdateService, $moduleMigrationService, $moduleReleaseGateAudit, new ProjectArchiveService($projectRoot), $projectRoot, $releaseCatalogService);
$assistantRegistry->register(new ModuleReleaseGateAssistant($moduleReleaseGateState, $moduleLibraryService, $moduleReleaseGateService));
$releaseCatalogState = $stateStore();
$assistantRegistry->register(new ReleaseCatalogAssistant($releaseCatalogState, $moduleLibraryService, $releaseCatalogService));
$trustPolicyState = $stateStore();
$assistantRegistry->register(new TrustPolicyAssistant($trustPolicyState, $releaseCatalogService));
$trustRecoveryState = $stateStore();
$trustRecoveryService = new TrustRecoveryService($releaseTrustStore, $releaseCatalogService, $moduleLibraryStore, $projectRoot);
$assistantRegistry->register(new TrustRecoveryAssistant($trustRecoveryState, $trustRecoveryService));
$trustFederationState = $stateStore();
$trustFederationService = new TrustFederationService($releaseTrustStore, $trustRecoveryService, $projectRoot);
$assistantRegistry->register(new TrustFederationAssistant($trustFederationState, $trustFederationService));
$trustFailoverState = $stateStore();
$trustFailoverService = new TrustFailoverService($releaseTrustStore, $trustFederationService, $projectRoot);
$assistantRegistry->register(new TrustFailoverAssistant($trustFailoverState, $trustFailoverService));
$trustMembershipState = $stateStore();
$trustMembershipService = new TrustMembershipService($releaseTrustStore, $projectRoot);
$assistantRegistry->register(new TrustMembershipAssistant($trustMembershipState, $trustMembershipService));
$diagnosticStore = $stateStore();
$diagnosticService = new DataFormDiagnosticService($diagnosticStore, $dataSourceRegistry, $dataFormActionRegistry, $fieldTypeRegistry);
$assistantRegistry->register(new DiagnosticAssistant($diagnosticStore, $diagnosticService));
$workflowStore = $stateStore();
$assistantRegistry->register(new WorkflowAssistant(
    $workflowStore,
    new WorkflowProgressService(
        $workflowStore,
        $projectRoot,
        $dataSourceRegistry,
        $dataFormActionRegistry,
        $fieldTypeRegistry,
        $diagnosticService
    ),
    new WorkflowPersistenceService($workflowStore, $projectRoot)
));

$assistantManager = new AssistantManager($assistantRegistry);

return $assistantManager;
