<?php
declare(strict_types=1);

namespace DataForm\Database\Oracle;

use DataForm\Database\Pdo\AbstractPdoAdapter;

final class OracleAdapter extends AbstractPdoAdapter
{
    public function driver(): string { return 'oracle'; }
    protected function identifierQuote(): string { return '"'; }
    protected function dsn(): string
    {
        if (isset($this->config['dsn'])) return (string)$this->config['dsn'];
        $host = $this->config['host'] ?? '127.0.0.1';
        $port = (int)($this->config['port'] ?? 1521);
        $service = $this->config['service_name'] ?? 'FREEPDB1';
        $charset = $this->config['charset'] ?? 'AL32UTF8';
        return "oci:dbname=//{$host}:{$port}/{$service};charset={$charset}";
    }
    public function tableExists(string $table): bool
    {
        $stmt = $this->connection()->prepare('SELECT COUNT(*) FROM user_tables WHERE table_name = UPPER(:table)');
        $stmt->execute(['table' => $table]); return (int)$stmt->fetchColumn() > 0;
    }
    public function columns(string $table): array
    {
        $stmt = $this->connection()->prepare('SELECT column_name FROM user_tab_columns WHERE table_name = UPPER(:table) ORDER BY column_id');
        $stmt->execute(['table' => $table]); return array_map('strtolower', array_column($stmt->fetchAll(), 'COLUMN_NAME'));
    }
    public function createTable(string $table, array $columns): void
    {
        $defs = ['"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'];
        foreach ($columns as $column) { if ($column === 'id') continue; $defs[] = $this->qi((string)$column) . ' CLOB NULL'; }
        $this->connection()->exec('CREATE TABLE ' . $this->qi($table) . ' (' . implode(', ', $defs) . ')');
    }
    public function insert(string $table, array $data): int
    {
        unset($data['id']);
        $columns = array_keys($data);
        $sql = 'INSERT INTO ' . $this->qi($table) . ' (' . implode(', ', array_map(fn($c) => $this->qi((string)$c), $columns)) . ') VALUES (' . implode(', ', array_map(fn($c) => ':' . $c, $columns)) . ') RETURNING id INTO :__id';
        $stmt = $this->connection()->prepare($sql);
        $id = 0;
        foreach ($data as $key => $value) $stmt->bindValue(':' . $key, $value);
        $stmt->bindParam(':__id', $id, \PDO::PARAM_INT | \PDO::PARAM_INPUT_OUTPUT, 20);
        $stmt->execute(); return (int)$id;
    }
}
