<?php
declare(strict_types=1);
namespace DataForm5\Console\Providers;
use DataForm5\Console\Commands\{AboutCommand,HealthCommand,ListCommand};use DataForm5\Console\Core\{CommandRegistry,ConsoleApplication};use DataForm5\Core\Container\ServiceContainer;use DataForm5\Core\Contracts\ServiceProviderInterface;use DataForm5\Testing\Commands\{QualityCheckCommand,TestCommand};use DataForm5\Documentation\Commands\GenerateDocumentationCommand;use DataForm5\Documentation\Core\DocumentationGenerator;use DataForm5\Help\Commands\HelpShowCommand;use DataForm5\Help\Core\{HelpRenderer,HelpResolver};use DataForm5\Testing\Core\{LegacyScriptRunner,QualityGate,DeveloperQualityCenter};use DataForm5\Testing\Commands\QualityCenterCommand;use DataForm5\Modules\SDK\SdkGenerator;use DataForm5\Modules\SDK\Commands\{MakeModuleCommand,MakeArtifactCommand,MakeCrudCommand,ModuleValidateCommand,ModulePackageCommand};use DataForm5\Modules\SDK\ModuleQualityValidator;use DataForm5\Modules\SDK\ModulePackager;use DataForm5\Modules\SDK\CrudScaffolder;
final class ConsoleServiceProvider implements ServiceProviderInterface
{
    public function register(ServiceContainer $c):void{$c->singleton(CommandRegistry::class,fn()=>new CommandRegistry());$c->singleton(ConsoleApplication::class,fn(ServiceContainer $c)=>new ConsoleApplication($c->get(CommandRegistry::class),'DataForm5 Core','build0026'));}
    public function boot(ServiceContainer $c):void{$r=$c->get(CommandRegistry::class);$r->add(new QualityCenterCommand($c->get(DeveloperQualityCenter::class)));$generator=$c->get(SdkGenerator::class);$r->add(new MakeModuleCommand($generator));$r->add(new MakeCrudCommand($c->get(CrudScaffolder::class)));$r->add(new ModuleValidateCommand($c->get(ModuleQualityValidator::class)));$r->add(new ModulePackageCommand($c->get(ModulePackager::class)));foreach($generator->kinds() as $kind)$r->add(new MakeArtifactCommand($generator,$kind));$r->add(new AboutCommand());$r->add($c->build(HealthCommand::class));$r->add(new TestCommand($c->get(LegacyScriptRunner::class),dirname(__DIR__,3).'/tests'));$r->add(new QualityCheckCommand($c->get(QualityGate::class),dirname(__DIR__,3).'/storage/test-reports/latest.json'));$r->add(new GenerateDocumentationCommand($c->get(DocumentationGenerator::class)));$r->add(new HelpShowCommand($c->get(HelpResolver::class),$c->get(HelpRenderer::class)));$r->add(new ListCommand($r));}
}
