<?php
declare(strict_types=1);
$codeRoot=dirname(__DIR__,2);$manager=require $codeRoot.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\Module\ReleaseTrustStore;use EasyIT\Assistant\Module\TrustRecoveryService;use EasyIT\Assistant\Module\TrustFederationService;use EasyIT\Assistant\Module\TrustFailoverService;use EasyIT\Assistant\Module\TrustMembershipService;
function rrmdir30(string $dir):void{if(!is_dir($dir))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$p=$f->getPathname();$f->isDir()?@rmdir($p):@unlink($p);}@rmdir($dir);}function ok30(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rec30(ReleaseTrustStore $t,string $r,$c,$l):TrustRecoveryService{return new TrustRecoveryService($t,$c,$l,$r);}
$base=sys_get_temp_dir().'/easyit-phase30-'.bin2hex(random_bytes(4));$roots=['p'=>$base.'/primary','a'=>$base.'/a','b'=>$base.'/b','c'=>$base.'/c'];foreach($roots as $r)@mkdir($r,0770,true);
try{
    $obj=[];
    foreach($roots as $k=>$r){$trust=new ReleaseTrustStore($r);$rec=rec30($trust,$r,$releaseCatalogService,$moduleLibraryStore);$fed=new TrustFederationService($trust,$rec,$r);$role=$k==='p'?'PRIMARY':'SECONDARY';$name='Node '.strtoupper($k);$local=$fed->initializeLocal($name,$role,'INIT INSTANCE '.$role.' '.$name);$obj[$k]=compact('trust','rec','fed','local');}
    $pub=$obj['p']['rec']->exportPublicBundle();foreach(['a','b','c'] as $k){$imp=$obj[$k]['rec']->importPublicBundle((string)$pub['path'],true,false,'IMPORT PUBLIC ANCHORS AS RELEASE');ok30(!empty($imp['ok']),'Public Trust auf '.$k.' importiert');}
    $pass='Phase30-Strong-Passphrase!';$private=$obj['p']['rec']->createPrivateBackup($pass,'BACKUP PRIVATE KEYS');$restore=$obj['a']['rec']->restorePrivateBackup((string)$private['path'],$pass,'RESTORE PRIVATE KEYS','Standby A');ok30(!empty($restore['ok']),'Standby A besitzt Recovery-Signing-Key');
    foreach($roots as $k=>$r){$obj[$k]['fail']=new TrustFailoverService($obj[$k]['trust'],$obj[$k]['fed'],$r);$obj[$k]['mem']=new TrustMembershipService($obj[$k]['trust'],$r);$obj[$k]['identity']=$obj[$k]['fail']->exportIdentityBundle();}
    $clusterArt=$obj['p']['fail']->createCluster('cluster-phase30',[(array)$obj['a']['identity']['data'],(array)$obj['b']['identity']['data']],30,10,1,'CONFIGURE FAILOVER cluster-phase30');$cluster=(array)$clusterArt['data'];$obj['a']['fail']->importCluster($cluster);$obj['b']['fail']->importCluster($cluster);ok30(count((array)$cluster['members'])===3&&($cluster['quorum']??0)===2,'Ausgangscluster P/A/B mit Quorum 2');
    $leaseProposal=(array)$obj['p']['fail']->createLeaseProposal()['data'];$lp=(array)$obj['p']['fail']->acknowledgeLease($leaseProposal)['data'];$la=(array)$obj['a']['fail']->acknowledgeLease($leaseProposal)['data'];$lease=(array)$obj['p']['fail']->activateLease($leaseProposal,[$lp,$la],'ACTIVATE LEASE '.$obj['p']['local']['instanceId'].' EPOCH 1')['data'];$obj['a']['fail']->observeLease($lease);$obj['b']['fail']->observeLease($lease);ok30(($obj['p']['trust']->sign('phase30-before-reconfig')['algorithm']??'')==='Ed25519','PRIMARY besitzt vor Reconfiguration gültiges Lease');

    // Transition 1: add C as voting, retain B but demote it to non-voting.
    $bid=(string)$obj['b']['local']['instanceId'];$cid=(string)$obj['c']['local']['instanceId'];$pid=(string)$obj['p']['local']['instanceId'];$aid=(string)$obj['a']['local']['instanceId'];
    $proposal=(array)$obj['p']['mem']->createProposal([(array)$obj['c']['identity']['data']],[],[$cid=>true,$bid=>false],'PROPOSE MEMBERSHIP cluster-phase30 EPOCH 2')['data'];
    ok30(in_array($cid,(array)$proposal['payload']['newVoters'],true)&&!in_array($bid,(array)$proposal['payload']['newVoters'],true),'Zielmitgliedschaft nimmt C voting auf und setzt B non-voting');
    $ackP=(array)$obj['p']['mem']->acknowledgePrepare($proposal)['data'];$ackB=(array)$obj['b']['mem']->acknowledgePrepare($proposal)['data'];$insufficient=false;try{$obj['p']['mem']->activateJoint($proposal,[$ackP,$ackB],'ACTIVATE JOINT '.$proposal['transitionId']);}catch(Throwable $e){$insufficient=str_contains($e->getMessage(),'new=1');}ok30($insufficient,'Altes Quorum ohne neues Quorum reicht für Joint Consensus nicht');
    $ackC=(array)$obj['c']['mem']->acknowledgePrepare($proposal)['data'];$joint=(array)$obj['p']['mem']->activateJoint($proposal,[$ackP,$ackB,$ackC],'ACTIVATE JOINT '.$proposal['transitionId'])['data'];ok30(!empty($joint['active']),'Joint Consensus mit altem UND neuem Quorum aktiviert');
    foreach(['a','b','c'] as $k)$obj[$k]['mem']->importJoint($joint);
    $signBlocked=false;try{$obj['p']['trust']->sign('during-joint');}catch(Throwable $e){$signBlocked=str_contains($e->getMessage(),'Phase 30');}ok30($signBlocked,'Release-Signierung während Joint Consensus gefenced');
    $leaseBlocked=false;try{$obj['p']['fail']->createLeaseProposal();}catch(Throwable $e){$leaseBlocked=str_contains($e->getMessage(),'Reconfiguration');}ok30($leaseBlocked,'Leadership-Lease während Joint Consensus pausiert');
    $commitP=(array)$obj['p']['mem']->acknowledgeCommit($joint)['data'];$commitB=(array)$obj['b']['mem']->acknowledgeCommit($joint)['data'];$commitC=(array)$obj['c']['mem']->acknowledgeCommit($joint)['data'];$final=(array)$obj['p']['mem']->finalize($joint,[$commitP,$commitB,$commitC],'FINALIZE MEMBERSHIP '.$proposal['transitionId'])['data'];
    foreach(['a','b','c'] as $k)$obj[$k]['mem']->importFinalCluster($final);
    $st=$obj['p']['mem']->status();ok30(($st['membershipEpoch']??0)===2&&($st['quorum']??0)===2&&count((array)$st['members'])===4,'Membership-Epoche 2 aktiv: vier Mitglieder, drei Voting, Quorum 2');
    $bMember=null;foreach((array)$st['members'] as $m)if(($m['instanceId']??'')===$bid)$bMember=$m;ok30(is_array($bMember)&&empty($bMember['voting']),'Voting→Non-Voting Änderung für B aktiv');

    // New membership invalidates old lease; establish a fresh quorum lease P+A under epoch 2 membership.
    $lp2=(array)$obj['p']['fail']->createLeaseProposal()['data'];$ackP2=(array)$obj['p']['fail']->acknowledgeLease($lp2)['data'];$ackA2=(array)$obj['a']['fail']->acknowledgeLease($lp2)['data'];$lease2=(array)$obj['p']['fail']->activateLease($lp2,[$ackP2,$ackA2],'ACTIVATE LEASE '.$pid.' EPOCH 1')['data'];$obj['a']['fail']->observeLease($lease2);$obj['c']['fail']->observeLease($lease2);ok30(!empty($lease2['quorumVerified']),'Nach Reconfiguration neues Lease gegen neue Membership aufgebaut');

    // Transition 2: remove B completely. Voters remain P/A/C.
    $proposal2=(array)$obj['p']['mem']->createProposal([],[$bid],[],'PROPOSE MEMBERSHIP cluster-phase30 EPOCH 3')['data'];$pa=(array)$obj['p']['mem']->acknowledgePrepare($proposal2)['data'];$aa=(array)$obj['a']['mem']->acknowledgePrepare($proposal2)['data'];$joint2=(array)$obj['p']['mem']->activateJoint($proposal2,[$pa,$aa],'ACTIVATE JOINT '.$proposal2['transitionId'])['data'];foreach(['a','b','c'] as $k)$obj[$k]['mem']->importJoint($joint2);$pc=(array)$obj['p']['mem']->acknowledgeCommit($joint2)['data'];$ac=(array)$obj['a']['mem']->acknowledgeCommit($joint2)['data'];$final2=(array)$obj['p']['mem']->finalize($joint2,[$pc,$ac],'FINALIZE MEMBERSHIP '.$proposal2['transitionId'])['data'];foreach(['a','c'] as $k)$obj[$k]['mem']->importFinalCluster($final2);$removed=$obj['b']['mem']->importFinalCluster($final2);ok30(!empty($removed['removed']),'Entfernte Instanz erkennt finale Entfernung');
    $bLocal=json_decode((string)file_get_contents($roots['b'].'/storage/assistant/trust/instances/local.json'),true);ok30(($bLocal['role']??'')==='VERIFY_ONLY'&&($bLocal['status']??'')==='RETIRED','Entfernte Instanz wird lokal RETIRED/VERIFY_ONLY gefenced');
    $st2=$obj['p']['mem']->status();ok30(($st2['membershipEpoch']??0)===3&&count((array)$st2['members'])===3&&!array_filter((array)$st2['members'],fn($m)=>($m['instanceId']??'')===$bid),'Finale Membership-Epoche 3 enthält B nicht mehr');
    ok30(!empty($obj['p']['mem']->verifyAudit()['ok'])&&!empty($obj['a']['mem']->verifyAudit()['ok']),'Membership-Audit-Hashketten gültig');
    ok30($manager->getRegistry()->has('dataform.trust-membership'),'Phase-30-Assistent zentral registriert');
    echo "PHASE30_SMOKE_PASS\n";
}finally{rrmdir30($base);}
