<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;use EasyIT\Assistant\Module\ModuleInstallationRegistry;use EasyIT\Assistant\Module\ModuleDependencyService;use EasyIT\Assistant\Module\ModuleUpdateService;use EasyIT\Assistant\Module\ModuleMigrationService;use EasyIT\Assistant\Recovery\ProjectArchiveService;
function ok22(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr22(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr22($p):@unlink($p);}@rmdir($d);}function df22(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields22(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions22(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$src='phase22-src-'.bin2hex(random_bytes(3));$dst='phase22-dst-'.bin2hex(random_bytes(3));foreach([$src,$dst] as $p){@mkdir($root.'/projects/'.$p.'/config',0770,true);@mkdir($root.'/projects/'.$p.'/data/csv/'.$p,0770,true);}file_put_contents($root.'/projects/'.$dst.'/config/project.json',json_encode(['schema'=>'easyit.project.assistant.v1','project'=>['name'=>'Phase22','id'=>$dst,'path'=>'projects/'.$dst],'storage'=>['driver'=>'csv','mode'=>'local','localPath'=>'projects/'.$dst.'/data/csv/'.$dst]],JSON_PRETTY_PRINT));file_put_contents($root.'/projects/'.$dst.'/data/csv/'.$dst.'/base_table.csv',"id|name\n1|A\n2|B\n");
$store=new AssistantStateStore('easyit_assistant_phase22',$root);$df=df22('base_df','project-main','base_table');$scope=$src.'|base_df';$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields22('base_df','project-main','base_table',$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions22('base_df'),$scope);foreach([$src,$dst] as $p){$ds=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id','passwordRef'=>'PHASE22_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$store->putForProject('datasource.configure',$p,$ds,$p);}
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root);$inst=new ModuleInstallationRegistry($root);$deps=new ModuleDependencyService($ls,$lib,$inst,$root);$updates=new ModuleUpdateService($ls,$lib,$inst,$deps,new ProjectArchiveService($root),$root);$migrations=new ModuleMigrationService($store,$ls,$inst,$updates,new ProjectArchiveService($root),$root);$moduleId='';
try{
 $mod=$lib->createFromProject($src,'P22 Base','Migrationstest',['base_df'],false,true,'system',null);$moduleId=(string)$mod['id'];$lib->setRelease($moduleId,'system',null,'1.0.0',[]);$initial=$deps->prepare(['system::'.$moduleId],$dst,['global'=>[],'modules'=>[]],['global'=>[],'modules'=>[]],false,false);ok22(!empty($initial['prepared']),'Initialinstallation vorbereitet');$ia=$deps->applyPrepared($initial);ok22(!empty($ia['applied']),'Version 1.0.0 installiert');ok22(($inst->get($dst,$moduleId)['version']??'')==='1.0.0','Installationsregister enthält 1.0.0');
 $releaseMigrations=[
  ['id'=>'p22-add-column','from'=>'^1.0.0','to'=>'2.0.0','order'=>10,'phase'=>'pre','type'=>'csv.add_column','destructive'=>false,'description'=>'Statusspalte ergänzen','dataForm'=>'base_df','payload'=>['source'=>'base_table','column'=>'status','default'=>'new']],
  ['id'=>'p22-map-values','from'=>'^1.0.0','to'=>'2.0.0','order'=>20,'phase'=>'pre','type'=>'csv.map_values','destructive'=>false,'description'=>'Bestandsdaten normalisieren','dataForm'=>'base_df','payload'=>['source'=>'base_table','column'=>'name','mapping'=>['A'=>'Alpha']]],
  ['id'=>'p22-create-table','from'=>'^1.0.0','to'=>'2.0.0','order'=>30,'phase'=>'pre','type'=>'csv.create_table','destructive'=>false,'description'=>'Audit-Tabelle anlegen','payload'=>['source'=>'audit_table','columns'=>['id','event']]],
  ['id'=>'p22-add-field','from'=>'^1.0.0','to'=>'2.0.0','order'=>10,'phase'=>'post','type'=>'field.add','destructive'=>false,'description'=>'Statusfeld in DataForm ergänzen','dataForm'=>'base_df','payload'=>['field'=>['name'=>'status','label'=>'Status','type'=>'text','required'=>false,'readOnly'=>false,'default'=>'new']]],
  ['id'=>'p22-config','from'=>'^1.0.0','to'=>'2.0.0','order'=>20,'phase'=>'post','type'=>'config.set','destructive'=>false,'description'=>'Migrationsmarker setzen','dataForm'=>'base_df','payload'=>['assistantId'=>'dataform.actions','path'=>'ui.migrationVersion','value'=>'2.0.0']],
 ];
 $badThrown=false;try{$pkg->withReleaseMetadata($ls->packagePath($moduleId,'system',null),['version'=>'2.0.0','dependencies'=>[],'migrations'=>[['id'=>'bad-remove','from'=>'^1.0.0','to'=>'2.0.0','type'=>'field.remove','dataForm'=>'base_df','payload'=>['name'=>'name']]]]);}catch(InvalidArgumentException){$badThrown=true;}ok22($badThrown,'Destruktive Migration ohne destructive=true wird abgewiesen');
 $lib->setRelease($moduleId,'system',null,'2.0.0',[],$releaseMigrations);$meta=$lib->getScoped($moduleId,'system',null);ok22(count((array)($meta['release']['migrations']??[]))===5,'Release enthält fünf deklarative Migrationen');$inspect=$pkg->inspect($ls->packagePath($moduleId,'system',null));ok22(($inspect['ok']??false)&&count((array)($inspect['release']['migrations']??[]))===5,'Migrationen sind Bestandteil des geprüften Modulpakets');
 $up=$updates->prepare($dst,[$moduleId],[],[],true,false);ok22(($up['migrationCount']??0)===5&& !empty($up['requiresMigrationAssistant']),'Phase 21 erkennt migrationspflichtiges Update');$blocked=$updates->apply($up);ok22(empty($blocked['applied'])&&!empty($blocked['requiresMigrationAssistant']),'Direktes Phase-21-Upgrade mit Migrationen wird blockiert');
 $plan=$migrations->prepare($dst,[$moduleId],[],[],true,false);ok22(($plan['verdict']??'')!=='FAIL'&&!empty($plan['prepared']),'Migrationsplan ist nach Dry-Run ausführbar');ok22(($plan['migrationCount']??0)===5,'Dry-Run plant alle fünf Schritte');$phases=array_map(static fn($s)=>$s['phase'],$plan['steps']);ok22(array_slice($phases,0,3)===['pre','pre','pre']&&array_slice($phases,-2)===['post','post'],'Pre-/Post-Reihenfolge ist korrekt');
 $ap=$migrations->apply($plan);ok22(!empty($ap['applied'])&&!empty($ap['rollbackReady']),'Migration und Upgrade wurden mit Rollback-Backup ausgeführt');ok22(($inst->get($dst,$moduleId)['version']??'')==='2.0.0','Installationsregister wurde auf 2.0.0 aktualisiert');$csv=file($root.'/projects/'.$dst.'/data/csv/'.$dst.'/base_table.csv',FILE_IGNORE_NEW_LINES);ok22(is_array($csv)&&str_contains($csv[0]??'','status'),'CSV-Spalte status wurde ergänzt');ok22(str_contains($csv[1]??'','Alpha'),'CSV-Bestandsdaten wurden migriert');ok22(is_file($root.'/projects/'.$dst.'/data/csv/'.$dst.'/audit_table.csv'),'Neue CSV-Tabelle wurde angelegt');$fs=$store->getForProject('dataform.fields',$dst,$dst.'|base_df');ok22(in_array('status',array_map(static fn($f)=>(string)($f['name']??''),(array)$fs['fields']),true),'Post-Migration hat DataForm-Feld ergänzt');$act=$store->getForProject('dataform.actions',$dst,$dst.'|base_df');ok22(($act['ui']['migrationVersion']??'')==='2.0.0','Konfigurationsmigration wurde angewendet');$hist=$migrations->history($dst);ok22(count((array)($hist['applied']??[]))===5,'Migrationsregister protokolliert alle Schritte');$plan2=$migrations->prepare($dst,[$moduleId],[],[],true,false);ok22(($plan2['prepared']??false)===false||($plan2['migrationCount']??0)===0,'Nach erfolgreichem Upgrade werden Migrationen nicht erneut geplant');$manager=require $root.'/system/assistant/bootstrap.php';ok22($manager->getRegistry()->has('dataform.module-migrations'),'Phase-22-Assistent zentral registriert');echo "PHASE22_SMOKE_PASS\n";
}finally{rr22($root.'/projects/'.$src);rr22($root.'/projects/'.$dst);rr22($root.'/storage/assistant/module-update-rollbacks/'.$dst);$sys=$root.'/storage/assistant/modules';if($moduleId!==''){@unlink($sys.'/'.$moduleId.'.json');@unlink($sys.'/'.$moduleId.'.dataform-module.zip');rr22($sys.'/.versions/'.$moduleId);}foreach(glob($root.'/backups/projects/'.$dst.'-*.zip*')?:[] as $f)@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/exports/*')?:[] as $f)if(str_contains(basename($f),'P22_')||str_starts_with(basename($f),'release-'))@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/imports/*.zip')?:[] as $f)@unlink($f);}
