<?php
declare(strict_types=1);
$codeRoot=dirname(__DIR__,2);require $codeRoot.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;use EasyIT\Assistant\Module\ModuleInstallationRegistry;use EasyIT\Assistant\Module\ModuleDependencyService;use EasyIT\Assistant\Module\ModuleUpdateService;use EasyIT\Assistant\Module\ModuleMigrationService;use EasyIT\Assistant\Module\ModuleMigrationAuditService;use EasyIT\Assistant\Module\ModuleReleaseGateService;use EasyIT\Assistant\Module\ReleaseTrustStore;use EasyIT\Assistant\Module\ReleaseCatalogService;use EasyIT\Assistant\Recovery\ProjectArchiveService;
function ok25(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr25(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)&&!is_link($p)?rr25($p):@unlink($p);}@rmdir($d);}function df25(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields25(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions25(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$root=sys_get_temp_dir().'/easyit-phase25-'.bin2hex(random_bytes(5));@mkdir($root,0770,true);$src='p25-src';$ref='p25-ref';$moduleId='';
try{
 foreach([$src,$ref] as $p){@mkdir($root.'/projects/'.$p.'/config',0770,true);@mkdir($root.'/projects/'.$p.'/data/csv/'.$p,0770,true);file_put_contents($root.'/projects/'.$p.'/config/project.json',json_encode(['schema'=>'easyit.project.assistant.v1','project'=>['name'=>'Phase25','id'=>$p,'path'=>'projects/'.$p],'storage'=>['driver'=>'csv','mode'=>'local','localPath'=>'projects/'.$p.'/data/csv/'.$p]],JSON_PRETTY_PRINT));file_put_contents($root.'/projects/'.$p.'/config/datasource.json',json_encode(['schema'=>'easyit.datasource.assistant.v1','profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id']],JSON_PRETTY_PRINT));}
 file_put_contents($root.'/projects/'.$ref.'/data/csv/'.$ref.'/base_table.csv',"id|name\n1|A\n2|B\n");$store=new AssistantStateStore('easyit_assistant_p25',$root);$df=df25('base_df','project-main','base_table');$scope=$src.'|base_df';$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields25('base_df','project-main','base_table',$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions25('base_df'),$scope);foreach([$src,$ref] as $p){$ds=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$store->putForProject('datasource.configure',$p,$ds,$p);}
 $dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$trust=new ReleaseTrustStore($root);$catalog=new ReleaseCatalogService($ls,$pkg,$trust,$root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root,$catalog);$inst=new ModuleInstallationRegistry($root);$deps=new ModuleDependencyService($ls,$lib,$inst,$root);$archives=new ProjectArchiveService($root);$updates=new ModuleUpdateService($ls,$lib,$inst,$deps,$archives,$root);$audit=new ModuleMigrationAuditService($store,$inst,$archives,$root);$migrations=new ModuleMigrationService($store,$ls,$inst,$updates,$archives,$root,$audit);$gate=new ModuleReleaseGateService($store,$ls,$lib,$pkg,$inst,$deps,$updates,$migrations,$audit,$archives,$root,$catalog);
 ok25(function_exists('sodium_crypto_sign_keypair'),'ext-sodium/Ed25519 verfügbar');$key=$catalog->ensureKey();ok25(str_starts_with((string)$key['keyId'],'ed25519-'),'Aktiver Ed25519-Vertrauensschlüssel erzeugt');ok25(!isset($catalog->trustStatus()['keys'][0]['privateKey']),'Trust-Status enthält keinen privaten Schlüssel');
 $mod=$lib->createFromProject($src,'P25 Trust','Trust-Test',['base_df'],false,true,'system',null);$moduleId=(string)$mod['id'];$lib->setRelease($moduleId,'system',null,'1.0.0',[]);$initial=$deps->prepare(['system::'.$moduleId],$ref,['global'=>[],'modules'=>[]],['global'=>[],'modules'=>[]],false,false);ok25(!empty($deps->applyPrepared($initial)['applied']),'Legacy-Basisversion installiert');
 $mig=[['id'=>'p25-column','from'=>'^1.0.0','to'=>'2.0.0','order'=>10,'phase'=>'pre','type'=>'csv.add_column','destructive'=>false,'dataForm'=>'base_df','payload'=>['source'=>'base_table','column'=>'status','default'=>'new']]];$lib->setRelease($moduleId,'system',null,'2.0.0',[],$mig,true);$report=$gate->gate('system::'.$moduleId,$ref);ok25(in_array((string)$report['verdict'],['PASS','PASS_WITH_WARNINGS'],true),'Release-Gate bestanden');$approval=$gate->release('system::'.$moduleId,(string)$report['reportId'],$moduleId.'@2.0.0',true);ok25(!empty($approval['releaseCatalog']['signature']['signature']),'RELEASED wird automatisch Ed25519-signiert katalogisiert');
 $verify=$catalog->verifyLibraryRelease($moduleId,'system',null);ok25(!empty($verify['ok'])&&($verify['verdict']??'')==='PASS','Katalog, Paket-SHA, Fingerprint, Gate-SHA und Signatur stimmen');$entries=$catalog->entries();ok25(count($entries)===1,'Zentraler Release-Katalog enthält Release');
 $stage=$lib->stage($moduleId,'system',null);ok25(!empty($stage['token']),'Vertrauensgeprüftes RELEASED kann gestaged werden');
 $path=$ls->packagePath($moduleId,'system',null);$original=(string)file_get_contents($path);file_put_contents($path,"TAMPER",FILE_APPEND);$blocked=false;try{$lib->stage($moduleId,'system',null);}catch(Throwable $e){echo 'TAMPER-ERROR: '.$e->getMessage()."\n";$blocked=true;}ok25($blocked,'Byteweise verändertes Paket wird vor Staging blockiert');file_put_contents($path,$original);
 $old=(string)$catalog->trustStatus()['activeKeyId'];$new=$catalog->rotateKey('ROTATE '.$old);ok25((string)$new['keyId']!==$old&&(string)$new['previousKeyId']===$old,'Schlüsselrotation erzeugt verketteten neuen Key');ok25(!empty($catalog->trustStatus()['chainVerification']['ok']),'Kryptographische Schlüssel-Vertrauenskette ist nach Rotation gültig');$afterRotate=$catalog->verifyLibraryRelease($moduleId,'system',null);ok25(!empty($afterRotate['ok'])&&($afterRotate['keyId']??'')===$old,'Altes Release bleibt nach Rotation über alten Trusted Key verifizierbar');$recatalog=$catalog->catalogReleased($moduleId,'system',null);ok25(($recatalog['signature']['keyId']??'')===$new['keyId'],'Erneute Katalogisierung nutzt neuen aktiven Schlüssel');ok25(!empty($catalog->verifyLibraryRelease($moduleId,'system',null)['ok']),'Neu signierter Katalogeintrag verifiziert');
 $manager=require $codeRoot.'/system/assistant/bootstrap.php';ok25($manager->getRegistry()->has('dataform.release-catalog'),'Phase-25-Assistent zentral registriert');echo "PHASE25_SMOKE_PASS\n";
}finally{rr25($root);}
