<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;
function ok19(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr19(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr19($p):@unlink($p);}@rmdir($d);}function df19(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields19(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions19(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$src='phase19-src-'.bin2hex(random_bytes(3));$dst='phase19-dst-'.bin2hex(random_bytes(3));$other='phase19-other-'.bin2hex(random_bytes(3));foreach([$src,$dst,$other] as $p)@mkdir($root.'/projects/'.$p.'/config',0770,true);$store=new AssistantStateStore('easyit_assistant_phase19',$root);
$parent=df19('ed_ev','project-main','ev_table');$child=df19('ed_ev_info','project-main','ev_info');$relation=['relation'=>['name'=>'ev-info','type'=>'one_to_many'],'parent'=>['dataForm'=>'ed_ev','source'=>'ev_table','keyField'=>'id'],'child'=>['dataForm'=>'ed_ev_info','source'=>'ev_info','foreignKeyField'=>'to_ev_id'],'binding'=>['enabled'=>true,'valueSource'=>'parent.currentRecord','parentValueField'=>'id','childTargetField'=>'to_ev_id','fillOnNewRecord'=>true,'readOnly'=>true],'manyToMany'=>['junctionSource'=>'','parentForeignKeyField'=>'','childForeignKeyField'=>'','childKeyField'=>'id'],'display'=>['paginationPosition'=>'below-records']];
foreach(['ed_ev'=>$parent,'ed_ev_info'=>$child] as $id=>$df){$scope=$src.'|'.$id;$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields19($id,'project-main',(string)$df['source']['name'],$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions19($id),$scope);}$store->putForProject('dataform.relations',$src,$relation,$src.'|ed_ev');
$srcDs=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$src.'/data/csv/'.$src,'delimiter'=>'|','idField'=>'id','password'=>'SECRET19','passwordRef'=>'SRC19_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'ev_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'ev_info','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'ev_table']];$dstDs=['profile'=>['name'=>'customer-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$dst.'/data/csv/'.$dst,'delimiter'=>'|','idField'=>'id','passwordRef'=>'DST19_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'customer_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'customer_info','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'customer_table']];$store->putForProject('datasource.configure',$src,$srcDs,$src);$store->putForProject('datasource.configure',$dst,$dstDs,$dst);
$systemId=$copyId=$impId='';
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root);
try{
 $sys=$lib->createFromProject($src,'EV Funktionsmodul','Eltern-/Kindmodul',['ed_ev'],true,true,'system',null);ok19(($sys['library']['visibility']??'')==='system','Modul systemweit gespeichert');ok19(count((array)($sys['module']['dataForms']??[]))===2,'mehrere DataForms in Bibliotheksmodul');$systemId=(string)$sys['id'];$pp=$lib->exportPath($systemId,'system',null);ok19(is_file($pp),'echtes Modulpaket in Bibliothek gespeichert');$ins=$pkg->inspect($pp);ok19(!empty($ins['ok']),'gespeichertes Bibliotheksmodul erneut prüfbar');ok19(!isset($ins['datasource']['connection']['password']),'Klartext-Secret auch in Bibliothek entfernt');
 $copy=$lib->copy($systemId,'EV Projektmodul','system',null,'project',$src);ok19(($copy['library']['ownerProject']??'')===$src,'systemweites Modul projektbezogen kopiert');$copyId=(string)$copy['id'];$otherList=$lib->list($other);ok19(!in_array($copyId,array_column($otherList,'id'),true),'Projektmodul in anderem Projekt unsichtbar');
 $ren=$lib->rename($copyId,'EV Projektmodul V2','Neue Beschreibung','project',$src);ok19(($ren['name']??'')==='EV Projektmodul V2','Modul umbenannt');$hist=$lib->history($copyId,'project',$src);ok19(count($hist)>=2,'Versionsverlauf für Modul vorhanden');
 $moved=$lib->changeVisibility($copyId,'project',$src,'system',null);ok19(($moved['library']['visibility']??'')==='system','Projektmodul kann systemweit freigegeben werden');ok19($ls->getInScope($copyId,'project',$src)===[]&&$ls->getInScope($copyId,'system',null)!==[],'Freigabewechsel verschiebt aktives Modul');ok19(count($lib->history($copyId,'system',null))>=2,'Versionsverlauf bleibt beim Freigabewechsel erhalten');
 $imp=$lib->importPath($pp,'EV Importmodul','importiert','project',$src);ok19(($imp['library']['visibility']??'')==='project','Modulpaket in Bibliothek importiert');$impId=(string)$imp['id'];
 $stage=$lib->stage($systemId,'system',null);$dfMap=['ed_ev'=>'ed_customer','ed_ev_info'=>'ed_customer_info'];$refMap=['project-main'=>'customer-main','ev_table'=>'customer_table','ev_info'=>'customer_info'];$pre=$lib->previewInstall((string)$stage['token'],$dst,$dfMap,$refMap,false,false);ok19(($pre['verdict']??'')!=='FAIL','Bibliotheksmodul vor Installation diagnostisch gültig');$app=$lib->applyInstall((string)$stage['token'],$dst,$dfMap,$refMap,false,false);ok19(!empty($app['applied']),'Bibliotheksmodul in Zielprojekt eingespielt');ok19(count((array)($app['diagnosticReports']??[]))===2,'Diagnose für installierte DataForms erzeugt');$hstate=$store->history('dataform.create',$dst,$dst.'|ed_customer');ok19(!empty($hstate['entries']),'Installation über Phase-14-Historie versioniert');
 $del=$lib->softDelete($impId,'project',$src,'EV Importmodul');ok19(!empty($del['deleted']),'Modul kontrolliert gelöscht');ok19($lib->get($impId,$src)===[],'gelöschtes Modul nicht mehr in Bibliothek');ok19(is_dir((string)$del['trash']),'Modul-Papierkorb vorhanden');
 $manager=require $root.'/system/assistant/bootstrap.php';ok19($manager->getRegistry()->has('dataform.module-library'),'Modulbibliothek zentral registriert');
 echo "PHASE19_SMOKE_PASS\n";
}finally{rr19($root.'/projects/'.$src);rr19($root.'/projects/'.$dst);rr19($root.'/projects/'.$other);$sysDir=$root.'/storage/assistant/modules';if(is_dir($sysDir)){foreach(array_filter([$systemId,$copyId]) as $mid){@unlink($sysDir.'/'.$mid.'.json');@unlink($sysDir.'/'.$mid.'.dataform-module.zip');rr19($sysDir.'/.versions/'.$mid);}}foreach(glob($root.'/storage/assistant/module-transfers/exports/*phase19*')?:[] as $f)@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/imports/*.zip')?:[] as $f)@unlink($f);}
