<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;use EasyIT\Assistant\Module\ModuleInstallationRegistry;use EasyIT\Assistant\Module\ModuleDependencyService;use EasyIT\Assistant\Module\SemVersion;use EasyIT\Assistant\Recovery\ProjectArchiveService;
function ok20(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr20(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr20($p):@unlink($p);}@rmdir($d);}function df20(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields20(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions20(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$src='phase20-src-'.bin2hex(random_bytes(3));$dst='phase20-dst-'.bin2hex(random_bytes(3));$cycle='phase20-cycle-'.bin2hex(random_bytes(3));foreach([$src,$dst,$cycle] as $p)@mkdir($root.'/projects/'.$p.'/config',0770,true);$store=new AssistantStateStore('easyit_assistant_phase20',$root);
foreach(['base_df'=>'base_table','feature_df'=>'feature_table'] as $id=>$table){$df=df20($id,'project-main',$table);$scope=$src.'|'.$id;$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields20($id,'project-main',$table,$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions20($id),$scope);}
$srcDs=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$src.'/data/csv/'.$src,'delimiter'=>'|','idField'=>'id','password'=>'SECRET20','passwordRef'=>'SRC20_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'feature_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$targetDs=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$dst.'/data/csv/'.$dst,'delimiter'=>'|','idField'=>'id','passwordRef'=>'DST20_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'feature_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$cycleDs=$targetDs;$cycleDs['connection']['path']='projects/'.$cycle.'/data/csv/'.$cycle;$store->putForProject('datasource.configure',$src,$srcDs,$src);$store->putForProject('datasource.configure',$dst,$targetDs,$dst);$store->putForProject('datasource.configure',$cycle,$cycleDs,$cycle);
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root);$inst=new ModuleInstallationRegistry($root);$deps=new ModuleDependencyService($ls,$lib,$inst,$root);$baseId=$featureId=$importId='';
try{
 ok20(SemVersion::satisfies('1.5.0','^1.2.0'),'SemVer ^-Bereich');ok20(!SemVersion::satisfies('2.0.0','^1.2.0'),'SemVer Major-Grenze');ok20(SemVersion::satisfies('1.4.7','~1.4.0'),'SemVer ~-Bereich');ok20(SemVersion::satisfies('1.9.0','>=1.2.0 <2.0.0'),'SemVer Vergleichskette');
 $base=$lib->createFromProject($src,'Base Module','Basis',['base_df'],false,true,'system',null);$baseId=(string)$base['id'];$base=$lib->setRelease($baseId,'system',null,'1.2.0',[]);ok20(($base['release']['version']??'')==='1.2.0','Basis-Release 1.2.0 gespeichert');
 $feature=$lib->createFromProject($src,'Feature Module','Feature',['feature_df'],false,true,'system',null);$featureId=(string)$feature['id'];$feature=$lib->setRelease($featureId,'system',null,'2.0.0',[['moduleId'=>$baseId,'constraint'=>'^1.0.0','optional'=>false]]);ok20(($feature['release']['dependencies'][0]['moduleId']??'')===$baseId,'Feature-Abhängigkeit gespeichert');
 $ins=$pkg->inspect($lib->exportPath($featureId,'system',null));ok20(($ins['release']['version']??'')==='2.0.0','Release-Metadaten im Modulpaket enthalten');ok20(($ins['release']['dependencies'][0]['constraint']??'')==='^1.0.0','Abhängigkeit im transportablen Paket enthalten');
 $plan=$deps->plan(['system::'.$featureId],$dst);ok20(($plan['verdict']??'')!=='FAIL','Abhängigkeitsplan ist ausführbar');ok20(($plan['installModuleIds']??[])===[$baseId,$featureId],'Installationsreihenfolge Basis vor Feature automatisch ermittelt');
 $prepared=$deps->prepare(['system::'.$featureId],$dst,['global'=>[],'modules'=>[]],['global'=>[],'modules'=>[]],false,false);ok20(!empty($prepared['prepared']),'Gesamtplan vollständig vorgeprüft');$applied=$deps->applyPrepared($prepared);ok20(!empty($applied['applied']),'Abhängigkeitsplan vollständig installiert');$installed=$inst->all($dst);ok20(count($installed)===2,'zwei Module im Projekt-Installationsregister');ok20(($inst->get($dst,$baseId)['version']??'')==='1.2.0','Basisversion im Installationsregister');ok20(($inst->get($dst,$featureId)['version']??'')==='2.0.0','Featureversion im Installationsregister');
 $again=$deps->plan(['system::'.$featureId],$dst);ok20(($again['installOrder']??[])===[],'identischer bereits installierter Modulstand wird übersprungen');
 $feature=$lib->setRelease($featureId,'system',null,'2.0.1',[['moduleId'=>$baseId,'constraint'=>'^3.0.0','optional'=>false]]);$bad=$deps->plan(['system::'.$featureId],$dst);ok20(($bad['verdict']??'')==='FAIL','inkompatible Pflichtabhängigkeit wird blockiert');ok20(str_contains(implode(' ',(array)$bad['errors']),'erfüllt ^3.0.0 nicht'),'Versionskonflikt wird konkret benannt');
 $feature=$lib->setRelease($featureId,'system',null,'2.0.2',[['moduleId'=>'missing-optional','constraint'=>'^1.0.0','optional'=>true]]);$opt=$deps->plan(['system::'.$featureId],$dst);ok20(($opt['verdict']??'')==='PASS_WITH_WARNINGS','fehlende optionale Abhängigkeit erzeugt Warnung statt FAIL');
 $base=$lib->setRelease($baseId,'system',null,'1.3.0',[['moduleId'=>$featureId,'constraint'=>'^2.0.0','optional'=>false]]);$feature=$lib->setRelease($featureId,'system',null,'2.1.0',[['moduleId'=>$baseId,'constraint'=>'^1.0.0','optional'=>false]]);$cy=$deps->plan(['system::'.$featureId],$cycle);ok20(($cy['verdict']??'')==='FAIL','zyklische Modulabhängigkeit wird blockiert');ok20(str_contains(implode(' ',(array)$cy['errors']),'Zyklische Modulabhängigkeit'),'Zyklus wird konkret diagnostiziert');
 $pp=$lib->exportPath($featureId,'system',null);$imp=$lib->importPath($pp,'Feature Import','Import','project',$src);$importId=(string)$imp['id'];ok20(($imp['release']['version']??'')==='2.1.0','Import erhält Release-Version aus Paket');ok20(count((array)($imp['release']['dependencies']??[]))===1,'Import erhält Modulabhängigkeiten aus Paket');
 $manager=require $root.'/system/assistant/bootstrap.php';ok20($manager->getRegistry()->has('dataform.module-dependencies'),'Phase-20-Assistent zentral registriert');
 $backupRoot=sys_get_temp_dir().'/easyit_phase20_backup_'.bin2hex(random_bytes(4));$bp='muster-csv';$br='muster-restore';foreach(['config/assistant','data/csv/'.$bp,'storage','logs','backups'] as $dir)@mkdir($backupRoot.'/projects/'.$bp.'/'.$dir,0770,true);file_put_contents($backupRoot.'/projects/'.$bp.'/config/project.json',json_encode(['schema'=>'easyit.project.assistant.v1','project'=>['name'=>'Muster CSV','id'=>$bp,'path'=>'projects/'.$bp],'storage'=>['driver'=>'csv','mode'=>'local','localPath'=>'projects/'.$bp.'/data/csv/'.$bp]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));file_put_contents($backupRoot.'/projects/'.$bp.'/config/datasource.json',json_encode(['profile'=>['name'=>'main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$bp.'/data/csv/'.$bp,'delimiter'=>'|','header'=>true]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));file_put_contents($backupRoot.'/projects/'.$bp.'/data/csv/'.$bp.'/t.csv',"id|name\n1|Test\n");$bir=new ModuleInstallationRegistry($backupRoot);$bir->register($bp,['id'=>'local-module','version'=>'1.4.0','sourceLocator'=>'project::'.$bp.'::local-module','packageSha256'=>str_repeat('a',64),'dataForms'=>['x'],'dependencies'=>[]]);$bas=new ProjectArchiveService($backupRoot);$bak=$bas->backup($bp,true,false);ok20($bak->isOk(),'Backup mit Modulinstallationsregister wird erzeugt');$res=$bas->restore((string)$bak->getPath(),$br);ok20($res->isOk(),'Restore mit Modulinstallationsregister ist erfolgreich');$rid=new ModuleInstallationRegistry($backupRoot);$rent=$rid->get($br,'local-module');ok20(($rent['version']??'')==='1.4.0','Installierte Modulversion bleibt nach Restore erhalten');ok20(($rent['sourceLocator']??'')==='project::'.$br.'::local-module','Projektbezogener Modul-Locator wird beim Restore retargetet');rr20($backupRoot);
 echo "PHASE20_SMOKE_PASS\n";
}finally{rr20($root.'/projects/'.$src);rr20($root.'/projects/'.$dst);rr20($root.'/projects/'.$cycle);$sys=$root.'/storage/assistant/modules';foreach(array_filter([$baseId,$featureId]) as $id){@unlink($sys.'/'.$id.'.json');@unlink($sys.'/'.$id.'.dataform-module.zip');rr20($sys.'/.versions/'.$id);}foreach(glob($root.'/storage/assistant/module-transfers/exports/*')?:[] as $f)if(str_contains(basename($f),'Base_Module')||str_contains(basename($f),'Feature_Module')||str_starts_with(basename($f),'release-'))@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/imports/*.zip')?:[] as $f)@unlink($f);}
