<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;
use EasyIT\Assistant\DataSource\DataSourceRegistry;
use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;
use EasyIT\Assistant\Field\FieldTypeRegistry;
use EasyIT\Assistant\Action\DataFormActionRegistry;
use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;
use EasyIT\Assistant\Module\DataFormModulePackageService;
function ok18(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function rr18(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr18($p):@unlink($p);}@rmdir($d);}
$src='phase18-src-'.bin2hex(random_bytes(3));$dst='phase18-dst-'.bin2hex(random_bytes(3));foreach([$src,$dst] as $p)@mkdir($root.'/projects/'.$p.'/config',0770,true);
$store=new AssistantStateStore('easyit_assistant_phase18',$root);
function df18(string $name,string $profile,string $source):array{return ['source'=>['profile'=>$profile,'driver'=>'csv','connection'=>'profile:'.$profile,'name'=>$source],'identity'=>['dataFormName'=>$name,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}
function fields18(string $name,string $profile,string $source,array $fields):array{return ['context'=>['dataForm'=>$name,'sourceProfile'=>$profile,'sourceName'=>$source,'primaryKey'=>'id'],'fields'=>$fields,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}
function actions18(string $name):array{return ['dataForm'=>['name'=>$name],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$parent=df18('ed_ev','project-main','ev_table');$child=df18('ed_ev_info','project-main','ev_info');
$relation=['relation'=>['name'=>'ev-info','type'=>'one_to_many'],'parent'=>['dataForm'=>'ed_ev','source'=>'ev_table','keyField'=>'id'],'child'=>['dataForm'=>'ed_ev_info','source'=>'ev_info','foreignKeyField'=>'to_ev_id'],'binding'=>['enabled'=>true,'valueSource'=>'parent.currentRecord','parentValueField'=>'id','childTargetField'=>'to_ev_id','fillOnNewRecord'=>true,'readOnly'=>true],'manyToMany'=>['junctionSource'=>'','parentForeignKeyField'=>'','childForeignKeyField'=>'','childKeyField'=>'id'],'display'=>['paginationPosition'=>'below-records']];
foreach(['ed_ev'=>$parent,'ed_ev_info'=>$child] as $id=>$df){$scope=$src.'|'.$id;$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields18($id,'project-main',(string)$df['source']['name'],$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions18($id),$scope);} $store->putForProject('dataform.relations',$src,$relation,$src.'|ed_ev');
$srcDs=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$src.'/data/csv/'.$src,'delimiter'=>'|','idField'=>'id','password'=>'SECRET','passwordRef'=>'SRC_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'ev_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'ev_info','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'ev_table']];
$dstDs=['profile'=>['name'=>'customer-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$dst.'/data/csv/'.$dst,'delimiter'=>'|','idField'=>'id','passwordRef'=>'DST_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'customer_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'customer_info','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'customer_table']];
$store->putForProject('datasource.configure',$src,$srcDs,$src);$store->putForProject('datasource.configure',$dst,$dstDs,$dst);
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$svc=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);
try{
 $exp=$svc->export($src,'EV-Modul',['ed_ev'],true,true);ok18(!empty($exp['ok'])&&is_file((string)$exp['path']),'Modulpaket als ZIP erzeugt');ok18((int)$exp['moduleCount']===2,'transitives Kind-DataForm automatisch aufgenommen');ok18(count((array)$exp['graph']['edges'])===1,'Beziehungsgraph enthält 1:n-Kante');
 $ins=$svc->inspect((string)$exp['path']);ok18(!empty($ins['ok']),'Modulpaket vollständig prüfbar');ok18(count((array)$ins['modules'])===2,'zwei DataForms im Paket');ok18(!isset($ins['datasource']['connection']['password']),'Klartext-Secret aus Snapshot entfernt');ok18(($ins['datasource']['connection']['passwordRef']??'')==='SRC_DB_PASSWORD','Secret-Referenz bleibt erhalten');
 $tampered=sys_get_temp_dir().'/phase18-tampered-'.bin2hex(random_bytes(3)).'.zip';copy((string)$exp['path'],$tampered);$tp=new PharData($tampered);$tp->addFromString('unexpected.txt','X');unset($tp);$bad=$svc->inspect($tampered);ok18(empty($bad['ok']),'Unerwarteter ZIP-Eintrag wird abgewiesen');@unlink($tampered);
 $staged=$svc->stageUpload(['name'=>'module.zip','tmp_name'=>$exp['path'],'error'=>UPLOAD_ERR_OK,'size'=>filesize($exp['path'])]);ok18(strlen((string)$staged['token'])===16,'Modul-Upload sicher gestaged');
 $dfMap=['ed_ev'=>'ed_customer','ed_ev_info'=>'ed_customer_info'];$refMap=['project-main'=>'customer-main','ev_table'=>'customer_table','ev_info'=>'customer_info'];
 $pre=$svc->preview((string)$staged['token'],$dst,$dfMap,$refMap,false,false);ok18(($pre['verdict']??'')!=='FAIL','Modul-Import-Vorschau gültig');ok18(isset($pre['mappedModules']['ed_customer'],$pre['mappedModules']['ed_customer_info']),'beide Ziel-DataForms gemappt');ok18(($pre['mappedModules']['ed_customer']['dataform.relations']['child']['dataForm']??'')==='ed_customer_info','Kind-DataForm im Relationsgraph gemappt');ok18(($pre['mappedModules']['ed_customer_info']['dataform.create']['source']['name']??'')==='customer_info','Kind-Hauptquelle gemappt');
 $app=$svc->apply((string)$staged['token'],$dst,$dfMap,$refMap,false,false);ok18(!empty($app['applied']),'Modul vollständig übernommen');ok18(count((array)($app['diagnosticReports']??[]))===2,'Diagnose für jedes importierte DataForm erzeugt');
 $p=$store->getForProject('dataform.create',$dst,$dst.'|ed_customer');$c=$store->getForProject('dataform.create',$dst,$dst.'|ed_customer_info');ok18(($p['identity']['dataFormName']??'')==='ed_customer'&&($c['identity']['dataFormName']??'')==='ed_customer_info','mehrere dataform.create-Zustände parallel persistent');
 $h=$store->history('dataform.create',$dst,$dst.'|ed_customer');ok18(!empty($h['entries']),'Modulimport in Phase-14-Historie versioniert');
 $conf=$svc->preview((string)$staged['token'],$dst,$dfMap,$refMap,false,false);ok18(($conf['verdict']??'')==='FAIL','bestehende Modulziele ohne Bestätigung blockiert');$ov=$svc->preview((string)$staged['token'],$dst,$dfMap,$refMap,true,false);ok18(($ov['verdict']??'')==='PASS_WITH_WARNINGS','historisiertes Modul-Überschreiben nur mit Warnung zugelassen');
 echo "PHASE18_SMOKE_PASS\n";
}finally{rr18($root.'/projects/'.$src);rr18($root.'/projects/'.$dst);foreach(glob($root.'/storage/assistant/module-transfers/exports/*phase18*')?:[] as $f)@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/imports/*.zip')?:[] as $f)@unlink($f);}
