<?php
declare(strict_types=1);
$codeRoot=dirname(__DIR__,2);require $codeRoot.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;use EasyIT\Assistant\Module\ModuleInstallationRegistry;use EasyIT\Assistant\Module\ModuleDependencyService;use EasyIT\Assistant\Module\ModuleUpdateService;use EasyIT\Assistant\Module\ModuleMigrationService;use EasyIT\Assistant\Module\ModuleMigrationAuditService;use EasyIT\Assistant\Module\ModuleReleaseGateService;use EasyIT\Assistant\Module\ReleaseTrustStore;use EasyIT\Assistant\Module\ReleaseCatalogService;use EasyIT\Assistant\Recovery\ProjectArchiveService;
function ok26(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr26(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)&&!is_link($p)?rr26($p):@unlink($p);}@rmdir($d);}function df26(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields26(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions26(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$root=sys_get_temp_dir().'/easyit-phase26-'.bin2hex(random_bytes(5));@mkdir($root,0770,true);$src='p26-src';$ref='p26-ref';
try{
 foreach([$src,$ref] as $p){@mkdir($root.'/projects/'.$p.'/config',0770,true);@mkdir($root.'/projects/'.$p.'/data/csv/'.$p,0770,true);file_put_contents($root.'/projects/'.$p.'/config/project.json',json_encode(['schema'=>'easyit.project.assistant.v1','project'=>['name'=>'Phase26','id'=>$p,'path'=>'projects/'.$p],'storage'=>['driver'=>'csv','mode'=>'local','localPath'=>'projects/'.$p.'/data/csv/'.$p]],JSON_PRETTY_PRINT));file_put_contents($root.'/projects/'.$p.'/config/datasource.json',json_encode(['schema'=>'easyit.datasource.assistant.v1','profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id']],JSON_PRETTY_PRINT));}
 file_put_contents($root.'/projects/'.$ref.'/data/csv/'.$ref.'/base_table.csv',"id|name\n1|A\n2|B\n");$store=new AssistantStateStore('easyit_assistant_p26',$root);$df=df26('base_df','project-main','base_table');$scope=$src.'|base_df';$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields26('base_df','project-main','base_table',$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions26('base_df'),$scope);foreach([$src,$ref] as $p){$ds=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$store->putForProject('datasource.configure',$p,$ds,$p);}
 $dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$trust=new ReleaseTrustStore($root);$catalog=new ReleaseCatalogService($ls,$pkg,$trust,$root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root,$catalog);$inst=new ModuleInstallationRegistry($root);$deps=new ModuleDependencyService($ls,$lib,$inst,$root);$archives=new ProjectArchiveService($root);$updates=new ModuleUpdateService($ls,$lib,$inst,$deps,$archives,$root);$audit=new ModuleMigrationAuditService($store,$inst,$archives,$root);$migrations=new ModuleMigrationService($store,$ls,$inst,$updates,$archives,$root,$audit);$gate=new ModuleReleaseGateService($store,$ls,$lib,$pkg,$inst,$deps,$updates,$migrations,$audit,$archives,$root,$catalog);
 $mod=$lib->createFromProject($src,'P26 Trust','Trust Policy Test',['base_df'],false,true,'system',null);$id=(string)$mod['id'];$lib->setRelease($id,'system',null,'1.0.0',[]);$initial=$deps->prepare(['system::'.$id],$ref,['global'=>[],'modules'=>[]],['global'=>[],'modules'=>[]],false,false);$deps->applyPrepared($initial);$mig=[['id'=>'p26-column','from'=>'^1.0.0','to'=>'2.0.0','order'=>10,'phase'=>'pre','type'=>'csv.add_column','destructive'=>false,'dataForm'=>'base_df','payload'=>['source'=>'base_table','column'=>'status','default'=>'new']]];$lib->setRelease($id,'system',null,'2.0.0',[],$mig,true);$report=$gate->gate('system::'.$id,$ref);$gate->release('system::'.$id,(string)$report['reportId'],$id.'@2.0.0',true);
 $entry=$catalog->entries()[0];$keyId=(string)$entry['signature']['keyId'];ok26(!empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'RELEASE-Schlüssel erlaubt Installation');
 $catalog->suspendKey($keyId,'Incident-Prüfung','SUSPEND '.$keyId);ok26(empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'SUSPENDED blockiert Release-Verifikation/Installation');$blocked=false;try{$lib->stage($id,'system',null);}catch(Throwable $e){$blocked=true;}ok26($blocked,'SUSPENDED blockiert zentralen Stagingpfad');
 $catalog->reactivateKey($keyId,'Incident abgeschlossen','REACTIVATE '.$keyId);ok26(!empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'Reaktivierter Schlüssel erlaubt Release wieder');
 $catalog->setKeyTrustLevel($keyId,'VERIFY_ONLY','Nur historische Prüfung','TRUST '.$keyId.' VERIFY_ONLY');ok26(empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'VERIFY_ONLY blockiert neue Installation');$hist=$trust->verifyForPurpose(json_encode([]),'bad',$keyId,'historical');ok26(isset($hist['keyPolicy'])&&!empty($hist['keyPolicy']['ok']),'VERIFY_ONLY erfüllt historische Policy (Signatur selbst separat geprüft)');
 $catalog->setKeyTrustLevel($keyId,'RELEASE','Wieder für Releases freigegeben','TRUST '.$keyId.' RELEASE');ok26(!empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'RELEASE-Stufe wieder aktiv');
 $catalog->setKeyValidity($keyId,'2000-01-01T00:00:00Z','Ablauftest','VALIDITY '.$keyId);ok26(empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'Abgelaufener Schlüssel blockiert Signatur');$catalog->setKeyValidity($keyId,null,'Ablauf wieder aufgehoben','VALIDITY '.$keyId);ok26(!empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'Unbegrenzte Gültigkeit wiederhergestellt');
 $new=$catalog->rotateKey('ROTATE '.$keyId);$newId=(string)$new['keyId'];ok26($newId!==$keyId,'Administrierte Rotation erzeugt neuen Key');$catalog->revokeKey($keyId,'Schlüssel als kompromittiert markiert','REVOKE '.$keyId);ok26(empty($catalog->verifyLibraryRelease($id,'system',null)['ok']),'REVOKED blockiert historisches Release sofort');$irreversible=false;try{$catalog->reactivateKey($keyId,'nicht erlaubt','REACTIVATE '.$keyId);}catch(Throwable $e){$irreversible=true;}ok26($irreversible,'REVOKED ist irreversibel');ok26(empty($catalog->trustStatus()['chainVerification']['ok']),'Widerruf eines Chain-Ankers invalidiert abhängige Vertrauenskette');
 $events=$catalog->trustAudit();ok26(count($events)>=8,'Trust-Audit protokolliert Schlüsseloperationen');ok26(!empty($catalog->verifyTrustAudit()['ok']),'Hashverkettete Audit-Kette ist gültig');$auditPath=$root.'/storage/assistant/trust/audit.jsonl';$lines=file($auditPath,FILE_IGNORE_NEW_LINES)?:[];$tampered=json_decode($lines[0],true);$tampered['details']['tampered']=true;$lines[0]=json_encode($tampered,JSON_UNESCAPED_SLASHES);file_put_contents($auditPath,implode("\n",$lines)."\n");ok26(empty($catalog->verifyTrustAudit()['ok']),'Manipulierter Audit-Verlauf wird erkannt');
 $manager=require $codeRoot.'/system/assistant/bootstrap.php';ok26($manager->getRegistry()->has('dataform.trust-policy'),'Phase-26-Assistent zentral registriert');echo "PHASE26_SMOKE_PASS\n";
}finally{rr26($root);}
