<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;
use EasyIT\Assistant\DataSource\DataSourceRegistry;
use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;
use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;
use EasyIT\Assistant\Field\FieldTypeRegistry;
use EasyIT\Assistant\Action\DataFormActionRegistry;
use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;
use EasyIT\Assistant\Transport\DataFormPackageService;
function ok17(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function rr17(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr17($p):@unlink($p);}@rmdir($d);}
$src='phase17-src-'.bin2hex(random_bytes(3));$dst='phase17-dst-'.bin2hex(random_bytes(3));foreach([$src,$dst] as $p)@mkdir($root.'/projects/'.$p.'/config',0770,true);
$store=new AssistantStateStore('easyit_assistant_phase17',$root);
$df=['source'=>['profile'=>'project-main','driver'=>'csv','connection'=>'profile:project-main','name'=>'ev_table'],'identity'=>['dataFormName'=>'ed_ev','primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];
$fields=['context'=>['dataForm'=>'ed_ev','sourceProfile'=>'project-main','sourceName'=>'ev_table','primaryKey'=>'id'],'fields'=>$df['fields'],'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];
$relations=['relation'=>['name'=>'ev-info','type'=>'one_to_many'],'parent'=>['dataForm'=>'ed_ev','source'=>'ev_table','keyField'=>'id'],'child'=>['dataForm'=>'ed_ev_info','source'=>'ed_ev_info','foreignKeyField'=>'to_ev_id'],'binding'=>['enabled'=>true,'valueSource'=>'parent.currentRecord','parentValueField'=>'id','childTargetField'=>'to_ev_id','fillOnNewRecord'=>true,'readOnly'=>true],'manyToMany'=>['junctionSource'=>'','parentForeignKeyField'=>'','childForeignKeyField'=>'','childKeyField'=>'id'],'display'=>['paginationPosition'=>'below-records']];
$events=['context'=>['objectName'=>'dataFormContext','schema'=>'easyit.dataform.action-context.v1','includeOriginalRecord'=>true,'includeChanges'=>true,'includeRelationContext'=>true,'includePagination'=>true],'events'=>['beforeSave'=>['enabled'=>false,'handler'=>'','blocking'=>true],'afterSave'=>['enabled'=>true,'handler'=>'app.ev.afterSave','blocking'=>false],'beforeDelete'=>['enabled'=>false,'handler'=>'','blocking'=>true],'afterDelete'=>['enabled'=>false,'handler'=>'','blocking'=>false]],'runtime'=>['handlerResolution'=>'global-path','allowEval'=>false,'beforeEventFalseCancelsAction'=>true,'captureHandlerErrors'=>true]];
$actions=['dataForm'=>['name'=>'ed_ev'],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];
$srcDs=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$src.'/data/csv/'.$src,'delimiter'=>'|','idField'=>'id','password'=>'SECRET','passwordRef'=>'SRC_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'ev_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'ev_table']];
$dstDs=['profile'=>['name'=>'customer-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$dst.'/data/csv/'.$dst,'delimiter'=>'|','idField'=>'id','passwordRef'=>'DST_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'customer_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'customer_table']];
foreach(['dataform.create'=>$df,'dataform.fields'=>$fields,'dataform.relations'=>$relations,'dataform.events'=>$events,'dataform.actions'=>$actions] as $id=>$st){$scope=$id==='dataform.create'?$src:$src.'|ed_ev';$store->putForProject($id,$src,$st,$scope);} $store->putForProject('datasource.configure',$src,$srcDs,$src);$store->putForProject('datasource.configure',$dst,$dstDs,$dst);
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$svc=new DataFormPackageService($store,$dsreg,$ft,$ar,$diag,$root);
try{
 $exp=$svc->export($src,'ed_ev',true);ok17(!empty($exp['ok'])&&is_file((string)$exp['path']),'DataForm-Paket als ZIP erzeugt');ok17(strlen((string)$exp['sha256'])===64,'ZIP-SHA-256 erzeugt');
 $ins=$svc->inspect((string)$exp['path']);ok17(!empty($ins['ok']),'Exportpaket prüfbar');ok17(count((array)$ins['bundle'])===5,'fünf DataForm-Konfigurationsbereiche enthalten');ok17(!isset($ins['datasource']['connection']['password']),'Klartext-Secret aus Snapshot entfernt');ok17(($ins['datasource']['connection']['passwordRef']??'')==='SRC_DB_PASSWORD','Secret-Referenz bleibt erhalten');
 $tampered=sys_get_temp_dir().'/phase17-tampered-'.bin2hex(random_bytes(3)).'.zip';copy((string)$exp['path'],$tampered);$tp=new PharData($tampered);$tp->addFromString('unexpected.txt','X');unset($tp);$bad=$svc->inspect($tampered);ok17(empty($bad['ok']),'unerwarteter ZIP-Eintrag wird abgewiesen');@unlink($tampered);
 $staged=$svc->stageUpload(['name'=>'transport.zip','tmp_name'=>$exp['path'],'error'=>UPLOAD_ERR_OK,'size'=>filesize($exp['path'])]);ok17(strlen((string)$staged['token'])===16,'Upload sicher gestaged');
 $mapping=['project-main'=>'customer-main','ev_table'=>'customer_table','ed_ev_info'=>'ed_customer_info'];
 $pre=$svc->preview((string)$staged['token'],$dst,'ed_customer',$mapping,false,false);ok17(($pre['verdict']??'')!=='FAIL','Import-Vorschau vor Übernahme gültig');ok17(($pre['mappedBundle']['dataform.create']['identity']['dataFormName']??'')==='ed_customer','DataForm-Name gemappt');ok17(($pre['mappedBundle']['dataform.create']['source']['profile']??'')==='customer-main','Datenquellenprofil gemappt');ok17(($pre['mappedBundle']['dataform.create']['source']['name']??'')==='customer_table','Hauptquelle gemappt');ok17(($pre['mappedBundle']['dataform.relations']['child']['dataForm']??'')==='ed_customer_info','Relationsreferenz gemappt');
 $app=$svc->apply((string)$staged['token'],$dst,'ed_customer',$mapping,false,false);ok17(!empty($app['applied']),'Paket übernommen');ok17(isset($app['diagnosticReport']['verdict']),'Diagnose nach Import erzeugt');
 $got=$store->getForProject('dataform.create',$dst,$dst);ok17(($got['identity']['dataFormName']??'')==='ed_customer','Zielzustand persistent geschrieben');$h=$store->history('dataform.create',$dst,$dst);ok17(!empty($h['entries']),'Import in Phase-14-Historie versioniert');
 $conf=$svc->preview((string)$staged['token'],$dst,'ed_customer',$mapping,false,false);ok17(($conf['verdict']??'')==='FAIL','bestehendes Ziel ohne Bestätigung blockiert');$ov=$svc->preview((string)$staged['token'],$dst,'ed_customer',$mapping,true,false);ok17(($ov['verdict']??'')==='PASS_WITH_WARNINGS','historisiertes Überschreiben nur als Warnung zugelassen');
 echo "PHASE17_SMOKE_PASS\n";
} finally {rr17($root.'/projects/'.$src);rr17($root.'/projects/'.$dst);foreach(glob($root.'/storage/assistant/transfers/exports/*phase17*')?:[] as $f)@unlink($f);foreach(glob($root.'/storage/assistant/transfers/imports/*.zip')?:[] as $f)@unlink($f);}
