<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/system/assistant/bootstrap.php';
use EasyIT\Assistant\State\AssistantStateStore;use EasyIT\Assistant\DataSource\DataSourceRegistry;use EasyIT\Assistant\DataSource\Adapters\MySqlDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\SQLiteDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\CsvDataSourceAdapter;use EasyIT\Assistant\DataSource\Adapters\OracleDataSourceAdapter;use EasyIT\Assistant\Field\FieldTypeRegistry;use EasyIT\Assistant\Action\DataFormActionRegistry;use EasyIT\Assistant\Diagnostic\DataFormDiagnosticService;use EasyIT\Assistant\Module\DataFormModulePackageService;use EasyIT\Assistant\Module\DataFormModuleLibraryStore;use EasyIT\Assistant\Module\DataFormModuleLibraryService;use EasyIT\Assistant\Module\ModuleInstallationRegistry;use EasyIT\Assistant\Module\ModuleDependencyService;use EasyIT\Assistant\Module\ModuleUpdateService;use EasyIT\Assistant\Recovery\ProjectArchiveService;
function ok21(bool $v,string $m):void{if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}function rr21(string $d):void{if(!is_dir($d))return;foreach(array_diff(scandir($d)?:[],['.','..']) as $x){$p=$d.'/'.$x;is_dir($p)?rr21($p):@unlink($p);}@rmdir($d);}function df21(string $n,string $p,string $s):array{return ['source'=>['profile'=>$p,'driver'=>'csv','connection'=>'profile:'.$p,'name'=>$s],'identity'=>['dataFormName'=>$n,'primaryKey'=>'id'],'features'=>['fullTextSearch'=>true,'filter'=>true,'pagination'=>['enabled'=>true,'position'=>'below-records','pageSize'=>20,'windowLeft'=>2,'windowRight'=>2,'showFirst'=>true,'showLast'=>true]],'crud'=>['create'=>true,'show'=>true,'edit'=>true,'delete'=>true,'save'=>true],'fields'=>[['name'=>'id','label'=>'ID','type'=>'integer','required'=>true,'readOnly'=>true,'default'=>null],['name'=>'name','label'=>'Name','type'=>'text','required'=>true,'readOnly'=>false,'default'=>null]]];}function fields21(string $n,string $p,string $s,array $f):array{return ['context'=>['dataForm'=>$n,'sourceProfile'=>$p,'sourceName'=>$s,'primaryKey'=>'id'],'fields'=>$f,'lookups'=>[],'derivedEnums'=>[],'rules'=>['derivedEnumStorage'=>'comma-separated','derivedEnumDelimiter'=>',','trimValues'=>true,'deduplicateValues'=>true]];}function actions21(string $n):array{return ['dataForm'=>['name'=>$n],'actions'=>['new'=>true,'show'=>true,'edit'=>true,'save'=>true,'delete'=>true,'first'=>true,'previous'=>true,'next'=>true,'last'=>true],'ui'=>['buttonRegistry'=>'central','localTitlesAllowed'=>false,'localAriaLabelsAllowed'=>false,'cssBackgroundButtonsAllowed'=>false]];}
$src='phase21-src-'.bin2hex(random_bytes(3));$dst='phase21-dst-'.bin2hex(random_bytes(3));foreach([$src,$dst] as $p){@mkdir($root.'/projects/'.$p.'/config',0770,true);@mkdir($root.'/projects/'.$p.'/data/csv/'.$p,0770,true);}file_put_contents($root.'/projects/'.$dst.'/config/project.json',json_encode(['schema'=>'easyit.project.assistant.v1','project'=>['name'=>'Phase21','id'=>$dst,'path'=>'projects/'.$dst],'storage'=>['driver'=>'csv','mode'=>'local','localPath'=>'projects/'.$dst.'/data/csv/'.$dst]],JSON_PRETTY_PRINT));file_put_contents($root.'/projects/'.$dst.'/data/csv/'.$dst.'/base_table.csv',"id|name\n1|A\n");file_put_contents($root.'/projects/'.$dst.'/data/csv/'.$dst.'/feature_table.csv',"id|name\n1|B\n");
$store=new AssistantStateStore('easyit_assistant_phase21',$root);foreach(['base_df'=>'base_table','feature_df'=>'feature_table'] as $id=>$table){$df=df21($id,'project-main',$table);$scope=$src.'|'.$id;$store->putForProject('dataform.create',$src,$df,$scope);$store->putForProject('dataform.fields',$src,fields21($id,'project-main',$table,$df['fields']),$scope);$store->putForProject('dataform.actions',$src,actions21($id),$scope);}foreach([$src,$dst] as $p){$ds=['profile'=>['name'=>'project-main','driver'=>'csv'],'connection'=>['path'=>'projects/'.$p.'/data/csv/'.$p,'delimiter'=>'|','idField'=>'id','passwordRef'=>'PHASE21_DB_PASSWORD'],'test'=>['ok'=>true,'message'=>'ok'],'discovery'=>[['name'=>'base_table','type'=>'table','meta'=>['valid'=>true]],['name'=>'feature_table','type'=>'table','meta'=>['valid'=>true]]],'selection'=>['sourceName'=>'base_table']];$store->putForProject('datasource.configure',$p,$ds,$p);}
$dsreg=new DataSourceRegistry([new MySqlDataSourceAdapter(),new SQLiteDataSourceAdapter($root),new CsvDataSourceAdapter($root),new OracleDataSourceAdapter()]);$ft=new FieldTypeRegistry();$ar=new DataFormActionRegistry();$diag=new DataFormDiagnosticService($store,$dsreg,$ar,$ft);$pkg=new DataFormModulePackageService($store,$dsreg,$ft,$ar,$diag,$root);$ls=new DataFormModuleLibraryStore($root);$lib=new DataFormModuleLibraryService($ls,$pkg,$root);$inst=new ModuleInstallationRegistry($root);$deps=new ModuleDependencyService($ls,$lib,$inst,$root);$updates=new ModuleUpdateService($ls,$lib,$inst,$deps,new ProjectArchiveService($root),$root);$baseId=$featureId='';
try{
 $base=$lib->createFromProject($src,'P21 Base','Basis',['base_df'],false,true,'system',null);$baseId=(string)$base['id'];$lib->setRelease($baseId,'system',null,'1.0.0',[]);$feature=$lib->createFromProject($src,'P21 Feature','Feature',['feature_df'],false,true,'system',null);$featureId=(string)$feature['id'];$lib->setRelease($featureId,'system',null,'1.0.0',[['moduleId'=>$baseId,'constraint'=>'^1.0.0','optional'=>false]]);
 $initial=$deps->prepare(['system::'.$featureId],$dst,['global'=>[],'modules'=>[]],['global'=>[],'modules'=>[]],false,false);ok21(!empty($initial['prepared']),'Initialinstallation vorbereitet');$initApply=$deps->applyPrepared($initial);ok21(!empty($initApply['applied']),'Initialmodule installiert');ok21(($inst->get($dst,$baseId)['version']??'')==='1.0.0','Basis 1.0.0 installiert');ok21(($inst->get($dst,$featureId)['version']??'')==='1.0.0','Feature 1.0.0 installiert');ok21(isset($inst->get($dst,$featureId)['dataFormMapping']),'Installationsmapping wird für spätere Updates gespeichert');
 $lib->setRelease($baseId,'system',null,'2.0.0',[]);$scan=$updates->scan($dst);ok21(in_array($baseId,(array)$scan['updates'],true),'Update-Suche erkennt Basis 2.0.0');$blocked=$updates->prepare($dst,[$baseId],[],[],false,false);ok21(($blocked['verdict']??'')==='FAIL','Basis-Major-Upgrade wird bei inkompatiblem installiertem Feature blockiert');ok21(str_contains(implode(' ',(array)$blocked['errors']),'Feature')||str_contains(implode(' ',(array)$blocked['errors']),$featureId),'Reverse-Dependency-Konflikt wird konkret benannt');
 $lib->setRelease($featureId,'system',null,'2.0.0',[['moduleId'=>$baseId,'constraint'=>'^2.0.0','optional'=>false]]);$cascade=$updates->prepare($dst,[$baseId],[],[],true,false);ok21(($cascade['verdict']??'')!=='FAIL','Kaskadierender Upgrade-Plan ist ausführbar');ok21(in_array($baseId,(array)$cascade['selected'],true)&&in_array($featureId,(array)$cascade['selected'],true),'Feature wird wegen Reverse-Dependency automatisch mit aktualisiert');ok21(($cascade['compatibility']['versions'][$baseId]??'')==='2.0.0'&&($cascade['compatibility']['versions'][$featureId]??'')==='2.0.0','Zielversionssatz ist konsistent');
 $applied=$updates->apply($cascade);ok21(!empty($applied['applied']),'Upgrade wurde ausgeführt');ok21(!empty($applied['rollbackReady']),'Rollback-Checkpoint wurde vor Upgrade erzeugt');$backup=(array)($applied['rollbackCheckpoint']??[]);ok21(!empty($backup['ok'])&&is_file((string)($backup['path']??'')),'Rollback-Projektbackup existiert');ok21(is_file((string)($backup['path']??'').'.sha256'),'Rollback-SHA-Datei existiert');ok21(($inst->get($dst,$baseId)['version']??'')==='2.0.0','Basis auf 2.0.0 aktualisiert');ok21(($inst->get($dst,$featureId)['version']??'')==='2.0.0','Feature auf 2.0.0 aktualisiert');ok21(count($updates->checkpoints($dst))>=1,'Upgrade-Checkpoint-Metadaten gespeichert');$scan2=$updates->scan($dst);ok21(($scan2['status']??'')==='CURRENT','Nach Upgrade keine höheren Updates mehr offen');
 $manager=require $root.'/system/assistant/bootstrap.php';ok21($manager->getRegistry()->has('dataform.module-updates'),'Phase-21-Assistent zentral registriert');
 echo "PHASE21_SMOKE_PASS\n";
}finally{
 rr21($root.'/projects/'.$src);rr21($root.'/projects/'.$dst);rr21($root.'/storage/assistant/module-update-rollbacks/'.$dst);$sys=$root.'/storage/assistant/modules';foreach(array_filter([$baseId,$featureId]) as $id){@unlink($sys.'/'.$id.'.json');@unlink($sys.'/'.$id.'.dataform-module.zip');rr21($sys.'/.versions/'.$id);}foreach(glob($root.'/backups/projects/'.$dst.'-*.zip*')?:[] as $f)@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/exports/*')?:[] as $f)if(str_contains(basename($f),'P21_')||str_starts_with(basename($f),'release-'))@unlink($f);foreach(glob($root.'/storage/assistant/module-transfers/imports/*.zip')?:[] as $f)@unlink($f);
}
